### ISSUE TITLE
[Bug] : why rgba transfer hsla?

### ISSUE THREAD

**Issue by souoxs** [cssnano/cssnano#1002]
When i use `background: rgba(254, 255, 255, 0.6);`, cssnano will not change it, It is correct!

But,

When I use `background: rgba(255, 255, 255, 0.6);`, cssnano will change it to `background:hsla(0,0%,100%,.6)`,

But, I don't want this change!!!

Please Help!

I really don't want this transfer!!!

**Comment by alexander-akait** [comment]
Disable `colormin` https://cssnano.co/docs/what-are-optimisations/
