### ISSUE TITLE
[Feature Request] Make a version 4.0.3 of postcss-svgo

### ISSUE THREAD

**Issue by romain-trotard** [cssnano/cssnano#1024]
Hello guys,

In my project which is using `postcss-svgo` (not directly), I have a security issue that has been solved in your repository in this PR: https://github.com/cssnano/cssnano/pull/736 concerning `is-svg`.
I would like to know if it would be possible to make a version `4.0.3` of `postcss-svgo` not to have to fix the version of `is-svg` in my project ?

Thank you in advance.

**Comment by alexander-akait** [comment]
Fixed in rc

**Comment by ludofischer** [comment]
See reply to duplicate issue: https://github.com/cssnano/cssnano/issues/1019#issuecomment-802182732
