### ISSUE TITLE
[Feature Request] Provide API to use the package directly

### ISSUE THREAD

**Issue by jcubic** [cssnano/cssnano#1033]
**Is your feature request related to a problem? Please describe.**
It seems that new 5.0 RC version break everything you no longer can use the package directly. You need to use postcss. So this no longer work:

```javascript
var input = process.argv[2];
var output = process.argv[3];

var options = {
    preset: "default",
    map: {
        inline: false
    },
    discardUnused: false,
    from: input,
    to: output
};

var nano = require('cssnano');
fs.readFile(input, function(err, buffer) {
    nano.process(String(buffer), options).then(function(result) {
        fs.writeFile(output, result.css, function(err) {
            error(err);
            fs.writeFile(output + '.map', result.map.toString(), error);
        });
    }).catch(error);
});
```

I don't need any of Postcss i just want to compress single css file.

**Describe the solution you'd like**
Add back the API to use the package directly without postcss, 

**Describe alternatives you've considered**
I don't want to use postcss, add lot of package just to compress single css file.

**Additional context**

**Are you willing to work on this ?**
Sorry I have no idea how to add that API back.

**Comment by ludofischer** [comment]
You need to call `cssnano()`

```
cssnano().process
```

Actually I thought about removing the `process()`. That way you could install `postcss()` indipendently, since it just calls postcss under the hood.
