### ISSUE TITLE
[Bug] : No matching version found for postcss-svgo@4.0.3

### ISSUE THREAD

**Issue by nicolaszawada** [cssnano/cssnano#1037]
**Describe the bug**
Even though version 4.0.3 of postcss-svgo is published on the npm registry. There seems to be something wrong with it. It cannot be found.

**To Reproduce**

1. `npm install postcss-svgo@4.0.3`

_No matching version found for postcss-svgo@4.0.3_

**Expected behavior**
postcss-svgo version 4.0.3 must be installed

**Screenshots**

![2021-04-06_16-26-21](https://user-images.githubusercontent.com/9047816/113726885-e7330800-96f4-11eb-8027-bbd6a2e00445.png)

**Comment by alexander-akait** [comment]
Every time I get reported about it... You register did not get update from npm original register (you don't provide it) right now, sorry, won't fix on our side

**Comment by alexander-akait** [comment]
Please, check version on `npm` (https://www.npmjs.com/package/postcss-svgo) before posting the issue
