### ISSUE TITLE
How to turn cssnano on or off for different npm build scripts?

### ISSUE THREAD

**Issue by sm9** [cssnano/cssnano#1045]
I'm using Tailwind CSS as a PostCSS plugin with PurgeCSS and cssnano. I'm using npm scripts to run my build process and I've included my postcss.config.js and package.json files below.

At the moment, running `npm run build:cssmin` builds my Tailwind CSS file, including PurgeCSS and cssnano, and this bit is working fine. But I'm having issues with `npm run build:css` - I want this to build my Tailwind CSS, including PurgeCSS, but NOT minify the CSS with cssnano. Can anyone help me with this please? The end goal is to be able to run `npm run build:all` to build both a minified version and a non-minified version of my CSS at the same time for production (the non-minified version is useful for viewing diffs). Thanks in advance for any help. 

```javascript
// postcss.config.js
module.exports = {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
      cssnano: {},
    }
  }
```

```javascript
// package.json
{
  "scripts": {
    "build:cssmin": "NODE_ENV=production postcss src/css/main.css -o public_html/dist/css/main.min.css",
    "build:css": "NODE_ENV=production postcss src/css/main.css -o public_html/dist/css/main.css",
    "build:all": "npm run build:cssmin && npm run build:css"
  },
  "dependencies": {
    "autoprefixer": "^10.2.5",
    "tailwindcss": "^2.1.1"
  },
  "devDependencies": {
    "cssnano": "^4.1.10",
    "postcss": "^8.2.9",
    "postcss-cli": "^8.3.1"
  }
}
```

**Comment by alexander-akait** [comment]
you can set `NODE_ENV` and return different plugins, not related to cssnano, I think better ask this questions on stackoverflow

**Comment by ludofischer** [comment]
Can't solve this from inside cssnano, you can also ask for help on the PostCSS gitter chat https://gitter.im/postcss/postcss
