### ISSUE TITLE
[Bug] : cssnano v5 breaks on yarn/npm with --no-bin-links due to postinstall step for opencollective

### ISSUE THREAD

**Issue by proton-ab** [cssnano/cssnano#1046]
**Describe the bug**
cssnano v5 added forced dependency on `opencollective-postinstall` with `postinstall` which breaks on yarn/npm with `--no-bin-links`.

**To Reproduce**
```
$ yarn --frozen-lockfile --non-interactive --no-bin-links --production
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error /drone/src/node_modules/cssnano: Command failed.
Exit code: 127
Command: opencollective-postinstall
Arguments: 
Directory: /drone/src/node_modules/cssnano
Output:
/bin/sh: opencollective-postinstall: not found
```

**Expected behavior**
No issue during install in all environments supported by `cssnano`

**Additional context**
Generally acceptable solution here would be to use `node ./node_modules/opencollective-postinstall/index.js`.

`--no-bin-links` is a very useful option on filesystems where creating symlinks is not possible.

In addition note that the build failed on CI here despite the fact that `opencollective-postinstall` should have check for `process.env.CI`.

**Comment by ludofischer** [comment]
Thanks for the report.
I am afraid your suggestion breaks if someone uses Yarn 2 PnP as there will be no `node_modules`:
```
node ./node_modules/opencollective-postinstall/index.js
```
@alexander-akait what should we do here?
I think the issue is that it cannot find  the `opencollective-postinstall` script. That's why the process fails even if `opencollective-postinstall` checks for `process.env.CI`

**Comment by ludofischer** [comment]
I have opened a pull request to replace `opencollective-postinstall` (https://github.com/cssnano/cssnano/pull/1047) with the `funding` field, since I suspect always printing that message annoys people more than anything else, especially if it breaks their CI.

**Comment by ludofischer** [comment]
cssnano@5.0.1 is out which does not use `opencollective-postinstall` any more.
