### ISSUE TITLE
The website is outdated

### ISSUE THREAD

**Issue by stof** [cssnano/cssnano#1053]
The footer of the website says that 4.1.10 is the latest release, instead of 5.0.0:
![image](https://user-images.githubusercontent.com/439401/115549803-5be77400-a2a9-11eb-8793-0ec9ff9a78cd.png)

**Comment by stof** [comment]
And https://cssnano.co/docs/changelog does not have the 5.0 changelog either

**Comment by ludofischer** [comment]
> And https://cssnano.co/docs/changelog does not have the 5.0 changelog either

See https://github.com/cssnano/cssnano/pull/1022

**Comment by ludofischer** [comment]
Footer and changelog shoudl be updated: https://cssnano.co/
