### ISSUE TITLE
[Bug] : Disable feature in cssnano-preset-default looks not working

### ISSUE THREAD

**Issue by zaaack** [cssnano/cssnano#1055]
**Describe the bug**

Disable feature in cssnano-preset-default looks not working.

**To Reproduce**

1. Add `{discardDuplicates: false}` options in CssMinimizerPlugin/css nano playground,

**Expected behavior**
Should not discardDuplicates

**Screenshots**
[playground](https://cssnano.co/playground/#eyJpbnB1dCI6Ii8qIHdyaXRlIHlvdXIgY3NzIGJlbG93ICovXG5cbi5hYSB7XG4gIHBhZGRpbmctdG9wOiAxMHB4OyBcbiAgcGFkZGluZy10b3A6IGNhbGMoMTBweCArIGVudihzYWZlLWFyZWEtaW5zZXQtdG9wKSk7XG59IiwiY29uZmlnIjoiLy8gY3NzbmFubyBjb25maWdcbntcbiAgXCJwcmVzZXRcIiA6IFtcImRlZmF1bHRcIiwge1xuICBcImF1dG9wcmVmaXhlclwiOiBmYWxzZSxcbiAgXCJjc3NEZWNsYXJhdGlvblNvcnRlclwiOiBmYWxzZSxcbiAgXCJyYXdDYWNoZVwiOiBmYWxzZSxcbiAgXCJjYWxjXCI6IGZhbHNlLFxuICBcImNvbG9ybWluXCI6IGZhbHNlLFxuICBcImNvbnZlcnRWYWx1ZXNcIjogZmFsc2UsXG4gIFwiZGlzY2FyZENvbW1lbnRzXCI6IGZhbHNlLFxuICBcImRpc2NhcmREdXBsaWNhdGVzXCI6IGZhbHNlLFxuICBcImRpc2NhcmRFbXB0eVwiOiBmYWxzZSxcbiAgXCJkaXNjYXJkT3ZlcnJpZGRlblwiOiBmYWxzZSxcbiAgXCJkaXNjYXJkVW51c2VkXCI6IGZhbHNlLFxuICBcIm1lcmdlSWRlbnRzXCI6IGZhbHNlLFxuICBcIm1lcmdlTG9uZ2hhbmRcIjogZmFsc2UsXG4gIFwibWVyZ2VSdWxlc1wiOiBmYWxzZSxcbiAgXCJtaW5pZnlGb250VmFsdWVzXCI6IGZhbHNlLFxuICBcIm1pbmlmeUdyYWRpZW50c1wiOiBmYWxzZSxcbiAgXCJtaW5pZnlQYXJhbXNcIjogZmFsc2UsXG4gIFwibWluaWZ5U2VsZWN0b3JzXCI6IGZhbHNlLFxuICBcIm5vcm1hbGl6ZUNoYXJzZXRcIjogZmFsc2UsXG4gIFwibm9ybWFsaXplRGlzcGxheVZhbHVlc1wiOiBmYWxzZSxcbiAgXCJub3JtYWxpemVQb3NpdGlvbnNcIjogZmFsc2UsXG4gIFwibm9ybWFsaXplUmVwZWF0U3R5bGVcIjogZmFsc2UsXG4gIFwibm9ybWFsaXplU3RyaW5nXCI6IGZhbHNlLFxuICBcIm5vcm1hbGl6ZVRpbWluZ0Z1bmN0aW9uc1wiOiBmYWxzZSxcbiAgXCJub3JtYWxpemVVbmljb2RlXCI6IGZhbHNlLFxuICBcIm5vcm1hbGl6ZVVybFwiOiBmYWxzZSxcbiAgXCJub3JtYWxpemVXaGl0ZXNwYWNlXCI6IGZhbHNlLFxuICBcIm9yZGVyZWRWYWx1ZXNcIjogZmFsc2UsXG4gIFwicmVkdWNlSWRlbnRzXCI6IGZhbHNlLFxuICBcInJlZHVjZUluaXRpYWxcIjogZmFsc2UsXG4gIFwicmVkdWNlVHJhbnNmb3Jtc1wiOiBmYWxzZSxcbiAgXCJzdmdvXCI6IGZhbHNlLFxuICBcInVuaXF1ZVNlbGVjdG9yc1wiOiBmYWxzZSxcbiAgXCJ6aW5kZXhcIjogZmFsc2Vcbn1dXG59XG4ifQ==)

**Desktop (please complete the following information):**
- CSSNANO Version [e.g. 22]: 4.1.10
- Plugins/presets versions: cssnano-preset-default@4.0.7
- Add the output of `npx envinfo && npm ls cssnano` here

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 79.29 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.6.0 - /usr/local/bin/watchman
  Managers:
    Composer: 1.4.1 - /usr/local/bin/composer
    Homebrew: 3.0.3 - /usr/local/bin/brew
    Maven: 3.6.1 - /usr/local/bin/mvn
    pip2: 19.1 - /usr/local/bin/pip2
    pip3: 21.0.1 - /usr/local/bin/pip3
    RubyGems: 2.5.2.3 - /usr/bin/gem
  Utilities:
    CMake: 3.12.4 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.16.2 - /usr/local/bin/git
    Clang: 11.0.0 - /usr/bin/clang
    Subversion: 1.10.4 - /usr/bin/svn
    FFmpeg: 4.3.2 - /usr/local/bin/ffmpeg
  Servers:
    Apache: 2.4.34 - /usr/sbin/apachectl
  Virtualization:
    Docker: 19.03.12 - /usr/local/bin/docker
    VirtualBox: 6.1.18 - /usr/local/bin/vboxmanage
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Atom: 1.33.1
    Emacs: 22.1.1 - /usr/bin/emacs
    Nano: 2.0.6 - /usr/bin/nano
    Sublime Text: Build 3211
    Vim: 8.0 - /usr/bin/vim
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.11.4 - /usr/local/bin/go
    Java: 1.8.0_121 - /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.33 - /usr/bin/php
    Protoc: 3.15.3 - /usr/local/bin/protoc
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.2 - /usr/local/bin/python3
    Ruby: 2.3.7 - /usr/bin/ruby
  Databases:
    MySQL: 10.14 - /usr/local/bin/mysql
    SQLite: 3.22.0 - /Users/z/Library/Android/sdk/platform-tools/sqlite3
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0.1
    Safari: 13.1

(My Project)
└─┬ css-minimizer-webpack-plugin@1.3.0
  └── cssnano@4.1.10 

**Additional context**

**Comment by alexander-akait** [comment]
Please use `cssnano@5`, `cssnano@4` is deprecated and accept only security fixes

**Comment by zaaack** [comment]
@alexander-akait Hi,thank for quick reply.  I think the playground should be using the newest cssnano, but still cannot disable any plugins in the default preset, am I wrong about the config?

**Comment by alexander-akait** [comment]
Please provide example how you setup cssnano, we need to look, we have tests on this, and all is green

**Comment by zaaack** [comment]
[playground](https://cssnano.co/playground/#eyJpbnB1dCI6Ii8qIHdyaXRlIHlvdXIgY3NzIGJlbG93ICovXG5cbi5hYSB7XG4gIHBhZGRpbmctdG9wOiAxMHB4OyBcbiAgcGFkZGluZy10b3A6IGNhbGMoMTBweCArIGVudihzYWZlLWFyZWEtaW5zZXQtdG9wKSk7XG59IiwiY29uZmlnIjoiLy8gY3NzbmFubyBjb25maWdcbntcbiAgXCJwcmVzZXRcIiA6IFtcImRlZmF1bHRcIiwge1xuICBcImF1dG9wcmVmaXhlclwiOiBmYWxzZSxcbiAgXCJjc3NEZWNsYXJhdGlvblNvcnRlclwiOiBmYWxzZSxcbiAgXCJyYXdDYWNoZVwiOiBmYWxzZSxcbiAgXCJjYWxjXCI6IGZhbHNlLFxuICBcImNvbG9ybWluXCI6IGZhbHNlLFxuICBcImNvbnZlcnRWYWx1ZXNcIjogZmFsc2UsXG4gIFwiZGlzY2FyZENvbW1lbnRzXCI6IGZhbHNlLFxuICBcImRpc2NhcmREdXBsaWNhdGVzXCI6IGZhbHNlLFxuICBcImRpc2NhcmRFbXB0eVwiOiBmYWxzZSxcbiAgXCJkaXNjYXJkT3ZlcnJpZGRlblwiOiBmYWxzZSxcbiAgXCJkaXNjYXJkVW51c2VkXCI6IGZhbHNlLFxuICBcIm1lcmdlSWRlbnRzXCI6IGZhbHNlLFxuICBcIm1lcmdlTG9uZ2hhbmRcIjogZmFsc2UsXG4gIFwibWVyZ2VSdWxlc1wiOiBmYWxzZSxcbiAgXCJtaW5pZnlGb250VmFsdWVzXCI6IGZhbHNlLFxuICBcIm1pbmlmeUdyYWRpZW50c1wiOiBmYWxzZSxcbiAgXCJtaW5pZnlQYXJhbXNcIjogZmFsc2UsXG4gIFwibWluaWZ5U2VsZWN0b3JzXCI6IGZhbHNlLFxuICBcIm5vcm1hbGl6ZUNoYXJzZXRcIjogZmFsc2UsXG4gIFwibm9ybWFsaXplRGlzcGxheVZhbHVlc1wiOiBmYWxzZSxcbiAgXCJub3JtYWxpemVQb3NpdGlvbnNcIjogZmFsc2UsXG4gIFwibm9ybWFsaXplUmVwZWF0U3R5bGVcIjogZmFsc2UsXG4gIFwibm9ybWFsaXplU3RyaW5nXCI6IGZhbHNlLFxuICBcIm5vcm1hbGl6ZVRpbWluZ0Z1bmN0aW9uc1wiOiBmYWxzZSxcbiAgXCJub3JtYWxpemVVbmljb2RlXCI6IGZhbHNlLFxuICBcIm5vcm1hbGl6ZVVybFwiOiBmYWxzZSxcbiAgXCJub3JtYWxpemVXaGl0ZXNwYWNlXCI6IGZhbHNlLFxuICBcIm9yZGVyZWRWYWx1ZXNcIjogZmFsc2UsXG4gIFwicmVkdWNlSWRlbnRzXCI6IGZhbHNlLFxuICBcInJlZHVjZUluaXRpYWxcIjogZmFsc2UsXG4gIFwicmVkdWNlVHJhbnNmb3Jtc1wiOiBmYWxzZSxcbiAgXCJzdmdvXCI6IGZhbHNlLFxuICBcInVuaXF1ZVNlbGVjdG9yc1wiOiBmYWxzZSxcbiAgXCJ6aW5kZXhcIjogZmFsc2Vcbn1dXG59XG4ifQ==)  I cannot disable plugins in the playground.

**Comment by sigveio** [comment]
@zaaack I have tested and verified that disabling plugins works in the current version. However, please be aware that some times a different plugin than what you expect may produce the result you see.

For example, with:

```
.aa {
  padding: 2px;
}
.aa {
  padding: 2px;
}
```

Both `postcss-discard-duplicates` and `postcss-merge-rules` would act on it and produce

```
.aa{padding:2px}
``` 

And if you set `{ discardDuplicates: false }` , then `postcss-merge-rules` would still remove the duplicate when merging the adjacent rules. And could give you the impression that disabling does not work. But only `{ discardDuplicates: false, mergeRules: false }` in this case avoid them being merged.

Since there has not been further activity here in 3 months, I'm closing this issue. But feel free to re-open if you believe the above does not explain what you were seeing. In that case, I would ask you to please provide an example setup that we can test. So the input CSS, either code or configuration used to run cssnano, and what you expected the output to be. Thanks =)
