### ISSUE TITLE
[Bug] : `cssDeclarationSorter` doesn't work well with `all`

### ISSUE THREAD

**Issue by nstepien** [cssnano/cssnano#1068]
**Describe the bug**
`cssDeclarationSorter` moves `all` after `align-items` for example, which overrides `align-items`.

**To Reproduce**
```css
button {
  all: unset;
  display: flex;
  align-items: center;
}
```

**Expected behavior**
Nothing(?) should be moved before `all`.
Instead it roughly translates into:
```css
button {
  align-items: center;
  all: unset;
  display: flex;
}
```

**Screenshots**
N/A

**Desktop (please complete the following information):**
- CSSNANO Version 5.0.2
- Plugins/presets versions
  - cssnano is used in my webpack config like this:
    ```js
    optimization: {
      minimizer: ['...', new CssMinimizerPlugin()]
    },
     ```
- Add the output of `npx envinfo && npm ls cssnano` here

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (64) x64 AMD Ryzen Threadripper 3970X 32-Core Processor 
    Memory: 21.43 GB / 31.90 GB
  Binaries:
    Node: 16.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.11.1 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.30.0.
  IDEs:
    VSCode: 1.56.0 - C:\Users\s\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.51)

client@ D:\repos\client
└─┬ css-minimizer-webpack-plugin@2.0.0
  └── cssnano@5.0.2
```

**Additional context**
Disabling `cssDeclarationSorter` fixes my issue. 🤷‍♂️ 
Maybe anything before `all` should be wiped as well? Just don't sort it. 🤔

**Comment by Siilwyn** [comment]
Moving `all` to the top sounds like a good idea, will fix this. Also looking into the other issues, thanks for the cc @alexander-akait.
