### ISSUE TITLE
[Bug] : Merging border-top and border-color gives unexpected output

### ISSUE THREAD

**Issue by Siilwyn** [cssnano/cssnano#1100]
**Describe the bug**
Given `a{border-top:1px solid;border-color:purple}` results in `a{border-color:currentcolor purple purple;border-top:1px solid purple}`.

**To Reproduce**
Run a test like this:
```
test(
  'keep order of border properties, short- and longhand, right to left',
  passthroughCSS('a{border-top:1px solid;border-color:purple}')
);
```

**Expected behavior**
Expected output would I think be the same as the input so: `border-top:1px solid;border-color:purple`.

**Environment**
Node.js 14, cssnano on master `4d7fe367`.

**Additional context**
See https://github.com/cssnano/cssnano/pull/1071

**Comment by ludofischer** [comment]
I think this might be a duplicate of https://github.com/cssnano/cssnano/issues/1044

**Comment by alexander-akait** [comment]
We really need rewrite our merge on more stable solution, right now it is so complex

**Comment by Siilwyn** [comment]
Yes, let's close this as a duplicate of #1044.
