### ISSUE TITLE
[Bug] : Hashes (#) were added to the RGB color format

### ISSUE THREAD

**Issue by yumadilovtimur** [cssnano/cssnano#1115]
Hashes (#) were added to the RGB color format:
https://github.com/angular/angular-cli/issues/20869#issuecomment-845029637

Expected:
![image](https://user-images.githubusercontent.com/40427062/118975827-cfa29c80-b98d-11eb-8777-b2f3297743dc.png)

In fact:
![image](https://user-images.githubusercontent.com/40427062/118975854-d3ceba00-b98d-11eb-8a3d-bc1ba51e8905.png)

I set the values as in the first screenshot and expect to get them in the output.
We need such values so that we can further process them, for example, add transparency, like this: rgba(var(--gray-10), 0.3);
If it is just a variable with rgb(), then it will not work.

**Comment by alexander-akait** [comment]
@ludofischer We need be careful in future, a lot of regressions :disappointed:

**Comment by yumadilovtimur** [comment]
> @ludofischer We need be careful in future, a lot of regressions 😞

@alexander-akait Please let us know when the problem is resolved. I will be very grateful

**Comment by alexander-akait** [comment]
@yumadilovtimur You can help and send a PR with fix and test

**Comment by alan-agius4** [comment]
We have received multiple reports about similar issues: https://github.com/angular/angular-cli/issues/20870

**Comment by alexander-akait** [comment]
Yes, we will try to fix it asap

**Comment by scottieslg** [comment]
My `z-index: 100` is translating to `z-index: #100` in my Angular build as well.

**Comment by RettentoRectangle** [comment]
In our css file:

![cssfile](https://user-images.githubusercontent.com/42135870/119113431-62424a80-ba25-11eb-8d2c-b89667d599a5.png)

In browsers:

![customvariables](https://user-images.githubusercontent.com/42135870/119113241-2effbb80-ba25-11eb-82f0-8a91bb4d7aee.png)

Time to going back to scss variables?! :D

**Comment by victordc55** [comment]
The same is happening with stroke-dashoffset and stroke-dasharray with values like:
`.svg-element{
stroke-dashoffset:400;
stroke-dasharray:398 400}
`
being compiled to 
`
.svg-element{stroke-dashoffset:#400;stroke-dasharray:#398 #400}
`

**Comment by ludofischer** [comment]
> The same is happening with stroke-dashoffset and stroke-dasharray with values like:
> `.svg-element{ stroke-dashoffset:400; stroke-dasharray:398 400} `
> being compiled to
> `.svg-element{stroke-dashoffset:#400;stroke-dasharray:#398 #400}`

It's interpreting every sequence of 3/4/6/8 digits into a color

**Comment by victordc55** [comment]
Then why are font-weights staying the same? Are they processed diferently?

**Comment by RettentoRectangle** [comment]
Everything works fine after disabling colormin: 
(temporary fix).

require('cssnano')({
  preset: [
    'default',
    {    
      **colormin: false**
     }
  ]
})

**Comment by ludofischer** [comment]
> Then why are font-weights staying the same? Are they processed diferently?

That's a good question. I have looked into the code and it turns out the colormin skips font declaration explicitly:
https://github.com/cssnano/cssnano/blob/8a31ca38796e12e6fe52620cf8a545cb058fe295/packages/postcss-colormin/src/index.js#L86
So maybe there was an initial attempt at skipping declarations where a color cannot appear, but no one updated the list so it ended up relying on the color library failing to parse certain values.

**Comment by victordc55** [comment]
So a temporary fix would be adding more declarations to skip or use @RettentoRectangle  solution of disabling colormin.

**Comment by ludofischer** [comment]
> So a temporary fix would be adding more declarations to skip or use @RettentoRectangle solution of disabling colormin.

Disabling colormin fixes the problem without having to change the source code.
There's already a pull request with a fix https://github.com/cssnano/cssnano/pull/1118 It skips numbers if `colord` sees them as hex values but they don't start with `#`.
