### ISSUE TITLE
[Bug] : postcss-colormin change to colord parser breaks rgba colors with variable alpha

### ISSUE THREAD

**Issue by akoreh** [cssnano/cssnano#1120]
**Describe the bug**
Given the folowing color definition:

```
--tw-bg-opacity:0.5;
background-color:rgba(51,153,255,var(--tw-bg-opacity))
```

Parsing with the new `colord` package gives an alpha of 1 every time (this occurs if the variable is not included in the parse aswell).

` {parsed: Object {r: 51, g: 153, b: 255, a: 1}, rgba: Object {r: 51, g: 153, b: 255, a: 1}}`

This will then trigger the plugin to go through the normal flow and turn the rgba definition into hex:

```
if (parsed.isValid()) {    
    const alpha = parsed.alpha();   
    
    if (alpha === 1) {      
        const toHex = toShorthand(parsed.toHex());      
        const toName = parsed.toName();      

        if (toName && toName.length < toHex.length) {        
              return toName;     
        } else {       
              return toHex;     
        }
```

Essentially removing the entire logic with the variable opacity.

This did not occur previously because the package used for parsing (`color`) fails to parse colors such as:

`rgba(51,153,255,var(--tw-bg-opacity))`

This triggers the catch block to execute, returning the original color definition. This way the variable opacity logic stays intact.

As far as I can tell this was introduced with the following PR:

https://github.com/cssnano/cssnano/pull/1107/commits/1d36ad1df8d098e40dc25fc0a02724f87ba1e144

The color I gave as an example is generated by tailwindcss. This possibly affects a lot of projects.

**Comment by ludofischer** [comment]
Thank you for the bug report and sorry for the breakage. @omgovich I think this could be adressed at the colord level.

**Comment by omgovich** [comment]
Hey @ludofischer. Sorry for the headache. Colord was created for a bit different purposes and I didn't expect it will be used inside of CSS processing, but I will do my best to make it fit better to cssnano.

I am already working on parsers that will follow the specs. I am going to come back to you later today with some news, but I would recommend to release a small temporary workaround.

**Comment by ludofischer** [comment]
> Hey @ludofischer. Sorry for the headache. Colord was created for a bit different purposes and I didn't expect it will be used inside of CSS processing, but I will do my best to make it fit better to cssnano.
> 
> I am already working on parsers that will follow the specs. I am going to come back to you later today with some news, but I would recommend to release a small temporary workaround.

No worries. So far I think there are only two separate issues;

1. colord interpretes any sequence of 3/6/4/8 digits as a color
2. colord ignores CSS variables as if they were rando texts

https://github.com/cssnano/cssnano/pull/1118 should fix both now

**Comment by romainmenke** [comment]
Maybe just roll back the change? :)
Appreciating all the effort that is going into getting this resolved, but a roll back would stop the issue stream.

**Comment by ludofischer** [comment]
> Maybe just roll back the change? :)
> Appreciating all the effort that is going into getting this resolved, but a roll back would stop the stream of bug reports and unblock the main branch.
> 
> It would give everyone time to validate and test this update without the stress of knowing that it is broken for people.

That's also an option. @alexander-akait what do you think?

**Comment by omgovich** [comment]
Hey guys! I just made Colord's string parsers conforming to the CSS specs.
It's going to be even wiser than `color` you used to import before since `color` doesn't support some syntaxes like `"rgb(50% 50% 50%)"` which is absolutely valid color.

**Comment by alexander-akait** [comment]
@omgovich Big thanks for helping and great work
