### ISSUE TITLE
[Bug] : count property of `columns` shortand gets removed

### ISSUE THREAD

**Issue by m-e-h** [cssnano/cssnano#1123]
**Describe the bug**
`columns: 2 200px` gets transformed into `columns: 200px`, removing the 'count' property.
`columns: 200px 2` produces the same result.

**To Reproduce**

1. Run cssnano over the above CSS.

**Expected behavior**
I'd expect the count property to be preserved in the value.

**Screenshots**
If applicable, add screenshots to help explain your problem. (from [cssnano-playground](https://cssnano.co/playground/))

**Desktop (please complete the following information):**
- CSSNANO Version 5.0.3
- preset: 'default'
- Add the output of `npx envinfo && npm ls cssnano` here
```
  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 8.02 GB / 31.20 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    npm: 7.13.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Managers:
    Apt: 2.2.3 - /usr/bin/apt
    Composer: 2.0.13 - ~/.config/composer/composer
    pip3: 20.3.4 - /usr/bin/pip3
  Utilities:
    CMake: 3.20.2 - /snap/bin/cmake
    Make: 4.3 - /usr/bin/make
    GCC: 10.3.0 - /usr/bin/gcc
    Git: 2.30.2 - /usr/bin/git
    FFmpeg: 4.3.2 - /usr/bin/ffmpeg
  IDEs:
    Nano: 5.4 - /usr/bin/nano
    VSCode: 1.56.2 - /usr/bin/code
  Languages:
    Bash: 5.1.4 - /usr/bin/bash
    Perl: 5.32.1 - /usr/bin/perl
    PHP: 7.4.16 - /usr/bin/php
    Python3: 3.9.4 - /usr/bin/python3
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
```

**Additional context**

**Comment by ludofischer** [comment]
Thak you for the bug report! For once this does not seem related to colormin (I have tried to add a test for it on master and it passes).

**Comment by ludofischer** [comment]
I can reproduce it but I don't know yet which plugin is causing this.

**Comment by ludofischer** [comment]
Found it! `postcss-ordered-values` breaks the `columns` declaration.

**Comment by romainmenke** [comment]
Thank you @ludofischer ! 🎉
