### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by sigveio** [cssnano/cssnano#1157]
Could it be worth having a pull request template to help encourage/guide submitters to follow guidelines and provide relevant information?

I made a [suggestion/example](https://github.com/sigveio/cssnano/blob/9df673bfb1c0af2c7606e438eec9123dc48bf935/.github/pull_request_template.md) but thought I would ask for feedback before submitting a PR

**Comment by ludofischer** [comment]
I think it would be a good idea. I was also thinking the issue template could use some improvement. For example, it says to post screenshots so people end up posting a screenshot of the problematic code, which I think is worse than copy paste as it forces you to re-type it.

**Comment by sigveio** [comment]
Yeah I agree with you that they could also do with some tweaks.

For example using Markdown headings instead of bold for the various headings would be cleaner too.

```
<!-- also mention the version in which it was version (if any) -->
```
Do you know what this is intended to mean (from the bug template)?
