### ISSUE TITLE
[Feature Request] Is that possible to use cssnano cli directly without any config file?

### ISSUE THREAD

**Issue by sgon00** [cssnano/cssnano#1158]
Is that possible to do something like?

```
$ cssnano file.css file.min.css
```

I knew https://github.com/cssnano/cssnano/tree/master/packages/example-cli-usage

But I don't want to do that. 

I don't do any node.js programming too.

I am using `uglifyjs` and `html-minifier`. Both provide pure cli tool directly. 

Thanks a lot.

**Comment by sigveio** [comment]
To understand you better; could you explain why you do not wish to do what the `example-cli-usage` shows? 

If you use the `postcss.config.js` there, you should be able to do what you wish like this:

```
npx postcss input.css > output.css
```

**Comment by sigveio** [comment]
If you use Yarn, you could remove the input/output part of the script definition in `package.json` like this:

```
  "scripts": {
    "minify": "postcss"
  }, 
```

(And have the same `postcss.config.js` file so that cssnano is loaded as plugin)

And then run it like this:

```
yarn run minify input.css -o output2.css
```

**Comment by sgon00** [comment]
@sigveio Thank you very much for your quick reply.
The reason why I don't want to use it might because of personal preference and because I am not running nodejs projects.

1. I am using shell scripts to do website build automation. It's better not to have other `.js`, `.json` config files.
2. I don't do node.js programming. By looking at the config file, I don't understand the syntax `module.exports` etc..
3. I will just summarize all other reasons here. I just don't want to run `npm`, `yarn` etc. especially with extra config files. I just want a simple css minifier command line tool. That's all. People who are developing node.js projects are fine with any of `package.json`, `config.js`, `yarn`, `npx` etc.. But it doesn't look right to me when I am not doing any node.js.

With `uglifyjs` and `html-minifier`, I can simply use the command line. But not with `cssnano`.
I found `cssnano-cli` project, but the last update is 2016-09-22 and the github page is gone.
Maybe I will use `clean-css-cli` instead if `cssnano` does not provide a way.

Sorry about this question and Thanks a lot for your help.

**Comment by sigveio** [comment]
No problem @sgon00 - I only read the issue text and didn't see the "without any config file" from the title at first, so I just wanted to understand better why the CLI example wasn't suitable for you. :-) 

I believe you are either way using node under the hood with those other CLI tools you mention.

For example, when uglifyjs is installed as a global CLI tool you can see it's just a symlinked node module:
```zsh
❯ npm install uglify-js -g
❯ which uglifyjs
/home/node/.npm-global/bin/uglifyjs
❯ ls -la /home/node/.npm-global/bin | grep uglifyjs
(...) uglifyjs -> ../lib/node_modules/uglify-js/bin/uglifyjs
```

And you should be able to use [Postcss CLI](https://github.com/postcss/postcss-cli) in the same manner with the `-u` option:

```zsh
❯ cat input.css
.test {
  background: black;
}
❯ postcss input.css -o output.css -u cssnano
❯ cat output.css
.test{background:#000}
```

... as long as you don't need to pass any additional config options - such as using a preset. For that, there isn't any other option than using a config file as far as I know - unless you write your own wrapper script which runs postcss+cssnano with the appropriate options programmatically.

**Comment by sgon00** [comment]
@sigveio got it. Thank you very much for the detailed explanation and answer. 😀
