### ISSUE TITLE
[Feature Request] Playground pane labels + preset selection

### ISSUE THREAD

**Issue by sigveio** [cssnano/cssnano#1162]
## Is your feature request related to a problem? Please describe.

At the moment the config pane of the Playground shows squiggly error lines:

![Screenshot 2021-07-08 at 14 52 37](https://user-images.githubusercontent.com/6737410/124924921-393d3f80-dffc-11eb-929e-817fdb5527b1.png)

### Add labels

I propose adding a label above each of the 3 panes to indicate their function.

Something like this (quick mock up):

![proposal](https://user-images.githubusercontent.com/6737410/124938025-37797900-e008-11eb-96bf-0195e8a1d71c.png)

### Add easy preset switching

I'd also like to make it easy/convenient to switch between lite, default, and advanced.

This could be in the form of another button, or for example a drop down select menu or configure icon (like a gear or wrench) on the config pane label.

It would make it easier for someone to test without prior knowledge of cssnano or available presets/config options.

### Remove comments

With the labels and support for all the standard presets, there would be no need for comments inside the panes.

### Misc

- Set the output pane to `readOnly` as it has no input roles
- Add some missing error handling/feedback for the config pane
- Fix background around the carbon banner ad so it respects the site theme/darkmode

## Additional context / motivation

The Playground is a potential contact surface with new users, and can generally be practical to quickly test something out. I think these little tweaks could improve the experience.

## Are you willing to work on this ?

Yep! Happy to submit a PR 👍

**Comment by sigveio** [comment]
Super - thanks! 👍

**Comment by Siilwyn** [comment]
Now available in `css-declaration-sorter@6.1.0`, let me know if I can assist. :)
