### ISSUE TITLE
[Bug]: Postcss-SVGO warning during Gatsby Production build

### ISSUE THREAD

**Issue by gary-imotor** [cssnano/cssnano#1189]
### Describe the bug

These are produced as warnings, but it would still be nice to solve the issue. It happens only in Gatsby Production Build.
```shell
warn Css Minimizer Plugin: postcss-svgo:/Users/gatsby/website/styles.d31f5794aec20e60009d.css:165:5: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /Users/gatsby/website/styles.d31f5794aec20e60009d.css:1102:3318: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /Users/gatsby/website/styles.d31f5794aec20e60009d.css:1102:3654: TypeError: Cannot read property 'includes' of undefined
warn Css Minimizer Plugin: postcss-svgo: /Users/gatsby/website/styles.d31f5794aec20e60009d.css:1102:4123: TypeError: Cannot read property 'includes' of undefined
```

### Expected behaviour

No warnings

### Steps to reproduce

This will reproduce only one warning during gatsby build but the error message is the same as what I encountered in my commercial project.

1. Download the gatsby project from this url [https://github.com/gary-imotor/gatsby-starter](url)
2. Run the command `npm install` to install packages
3. Run `npx gatsby build` to to build the website
4. You should be able to see the warning in the console

![image](https://user-images.githubusercontent.com/67564469/132291274-4bba3d17-88d7-476b-9a83-ebaf02134328.png)

### Version
cssnano: 5.0.0

### Preset

(no preset)

### Environment

```shell
System:
  OS: macOS 11.5.2
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 5.96 GB / 32.00 GB
  Shell: 5.8 - /bin/zsh
```

### Package details

```shell
css-minimizer-webpack-plugin@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/css-minimizer-webpack-plugin/-/css-minimizer-webpack-plugin-2.0.0.tgz#3c42f6624ed4cf4780dd963e23ee649e5a25c1a8"
  integrity sha512-cG/uc94727tx5pBNtb1Sd7gvUPzwmcQi1lkpfqTpdkuNq75hJCw7bIVsCNijLm4dhDcr1atvuysl2rZqOG8Txw==
  dependencies:
    cssnano "^5.0.0"
    jest-worker "^26.3.0"
    p-limit "^3.0.2"
    postcss "^8.2.9"
    schema-utils "^3.0.0"
    serialize-javascript "^5.0.1"
    source-map "^0.6.1"
```

### Additional context
When I was reproducing the warning, I found that the warning comes with two CSS files imported from `slick-carousel`. Those two files are needed by `react-slick`. Once I comment the import statement out, the warning disappears. They are in `src/components/carousel.js` of this repo.

`
import 'slick-carousel/slick/slick.css'   
import 'slick-carousel/slick/slick-theme.css'
`

**Comment by gary-imotor** [comment]
> > Steps to reproduce
> > Having this issue in commercial project, unable to reproduce
> 
> Sorry, without example how we can reproduce it, we can't fix and help you, fill out this or we will close the issue

No problem, I will reproduce it and share the link soon.

**Comment by gary-imotor** [comment]
Hi @alexander-akait , I have reproduced the warning. Hope it helps.

**Comment by alexander-akait** [comment]
@gary-imotor PR welcome to fix an issue :+1:

**Comment by ludofischer** [comment]
The good news is that after updating https://github.com/gary-imotor/gatsby-starter to Gatsby 4 the warning disappears (and yes `npm why cssnano` and `npm why postcss-svgo` show it is still using cssnano and postcss-svgo).

**Comment by ludofischer** [comment]
Closing this since I think it depends on a combination of specific versions of cssnano, webpack and other software and the warning disappears if I upgrade Gatsby.
