### ISSUE TITLE
[Bug]: build version on create-react-app (using optimize-css-assets-webpack-plugin) replaces color names on variables

### ISSUE THREAD

**Issue by andres-upshow** [cssnano/cssnano#1246]
### Describe the bug

It is already reported here: https://github.com/facebook/create-react-app/issues/11685
Basically the resulting generated css after going through cssnano has some variables modified. For instance it replaces `--white` to `#fff` (if used inside a val() it will make that css property invalid)

### Expected behaviour

I would expect my css to keep variables as I want them to be used.

### Steps to reproduce

npx create-react-app
edit index.css add something like a background-color: var(--white);
build

### Version

^4.1.10

### Preset

default

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 23.75 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
```

### Package details

```shell
my-app@0.1.0 /Users/andres/temp/my-app
├─┬ css-loader@4.3.0
│ ├─┬ icss-utils@4.1.1
│ │ └── postcss@7.0.39
│ ├─┬ postcss-modules-extract-imports@2.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-modules-local-by-default@3.0.3
│ │ └── postcss@7.0.39
│ ├─┬ postcss-modules-scope@2.2.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-modules-values@3.0.0
│ │ └── postcss@7.0.39
│ └── postcss@7.0.39
├─┬ optimize-css-assets-webpack-plugin@5.0.4
│ └─┬ cssnano@4.1.11
│   ├─┬ cssnano-preset-default@4.0.8
│   │ ├─┬ css-declaration-sorter@4.0.1
│   │ │ └── postcss@7.0.39
│   │ ├─┬ cssnano-util-raw-cache@4.0.1
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-calc@7.0.5
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-colormin@4.0.3
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-convert-values@4.0.1
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-discard-comments@4.0.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-discard-duplicates@4.0.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-discard-empty@4.0.1
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-discard-overridden@4.0.1
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-merge-longhand@4.0.11
│   │ │ ├── postcss@7.0.39
│   │ │ └─┬ stylehacks@4.0.3
│   │ │   └── postcss@7.0.39
│   │ ├─┬ postcss-merge-rules@4.0.3
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-minify-font-values@4.0.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-minify-gradients@4.0.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-minify-params@4.0.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-minify-selectors@4.0.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-normalize-charset@4.0.1
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-normalize-display-values@4.0.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-normalize-positions@4.0.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-normalize-repeat-style@4.0.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-normalize-string@4.0.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-normalize-timing-functions@4.0.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-normalize-unicode@4.0.1
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-normalize-url@4.0.1
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-normalize-whitespace@4.0.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-ordered-values@4.1.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-reduce-initial@4.0.3
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-reduce-transforms@4.0.2
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-svgo@4.0.3
│   │ │ └── postcss@7.0.39
│   │ ├─┬ postcss-unique-selectors@4.0.1
│   │ │ └── postcss@7.0.39
│   │ └── postcss@7.0.39
│   └── postcss@7.0.39
├─┬ postcss-flexbugs-fixes@4.2.1
│ └── postcss@7.0.39
├─┬ postcss-loader@3.0.0
│ └── postcss@7.0.39
├─┬ postcss-normalize@8.0.1
│ ├─┬ postcss-browser-comments@3.0.0
│ │ └── postcss@7.0.39
│ └── postcss@7.0.39
├─┬ postcss-preset-env@6.7.0
│ ├─┬ autoprefixer@9.8.8
│ │ └── postcss@7.0.39
│ ├─┬ css-blank-pseudo@0.1.4
│ │ └── postcss@7.0.39
│ ├─┬ css-has-pseudo@0.10.0
│ │ └── postcss@7.0.39
│ ├─┬ css-prefers-color-scheme@3.1.1
│ │ └── postcss@7.0.39
│ ├─┬ postcss-attribute-case-insensitive@4.0.2
│ │ └── postcss@7.0.39
│ ├─┬ postcss-color-functional-notation@2.0.1
│ │ └── postcss@7.0.39
│ ├─┬ postcss-color-gray@5.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-color-hex-alpha@5.0.3
│ │ └── postcss@7.0.39
│ ├─┬ postcss-color-mod-function@3.0.3
│ │ └── postcss@7.0.39
│ ├─┬ postcss-color-rebeccapurple@4.0.1
│ │ └── postcss@7.0.39
│ ├─┬ postcss-custom-media@7.0.8
│ │ └── postcss@7.0.39
│ ├─┬ postcss-custom-properties@8.0.11
│ │ └── postcss@7.0.39
│ ├─┬ postcss-custom-selectors@5.1.2
│ │ └── postcss@7.0.39
│ ├─┬ postcss-dir-pseudo-class@5.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-double-position-gradients@1.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-env-function@2.0.2
│ │ └── postcss@7.0.39
│ ├─┬ postcss-focus-visible@4.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-focus-within@3.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-font-variant@4.0.1
│ │ └── postcss@7.0.39
│ ├─┬ postcss-gap-properties@2.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-image-set-function@3.0.1
│ │ └── postcss@7.0.39
│ ├─┬ postcss-initial@3.0.4
│ │ └── postcss@7.0.39
│ ├─┬ postcss-lab-function@2.0.1
│ │ └── postcss@7.0.39
│ ├─┬ postcss-logical@3.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-media-minmax@4.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-nesting@7.0.1
│ │ └── postcss@7.0.39
│ ├─┬ postcss-overflow-shorthand@2.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-page-break@2.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-place@4.0.1
│ │ └── postcss@7.0.39
│ ├─┬ postcss-pseudo-class-any-link@6.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-replace-overflow-wrap@3.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-selector-matches@4.0.0
│ │ └── postcss@7.0.39
│ ├─┬ postcss-selector-not@4.0.1
│ │ └── postcss@7.0.39
│ └── postcss@7.0.39
├─┬ postcss-safe-parser@5.0.2
│ └── postcss@8.4.2 deduped
├── postcss@8.4.2
└─┬ resolve-url-loader@3.1.4
  └── postcss@7.0.36
```

### Additional context

I know that this might be a bug of implementation and not on cssnano per se, but please let me know how I can configure it to avoid this behavior.

**Comment by andres-upshow** [comment]
I seems to be related to the `colormin` plugin, since I removed it from the source code of `cssnano-preset-default` and the issue goes away

**Comment by ludofischer** [comment]
Hi, thanks for the bug report. As far as I can see this bug does not affect the latest cssnano (5.0.11). Unfortunately create-react-app stable is stuck on cssnano 4. So I believe the best bet for now is to disable the colormin plugin (or, if you're brave, switch to create-react-app 5 alpha, which might have the latest cssnano).

**Comment by andres-upshow** [comment]
I completely agree that CRA is outdated, but on any case if cssnano is using semantic versioning and this is a breaking change, shouldn't the mayor version change when updating the plugin so it does not screw over builds all over the place?
If it is not a breaking change then it is a bug.

**Comment by alexander-akait** [comment]
Yes, it is bug, but we don't backport bugs to deprecated version, better to update cssnano, we don't have time on backporting, sorry

**Comment by ludofischer** [comment]
> cssnano is using semantic versioning and this is a breaking change, shouldn't the mayor version change when updating the plugin so it does not screw over builds all over the place?

I think there is a misunderstanding. We did not update the postcss-colormin 4.x recently. According to npm the last postcss-colormin in the 4.x line was published 3 years ago: https://www.npmjs.com/package/postcss-colormin

**Comment by jolwee** [comment]
I was using 4.1.10 and encountered the same issue. After upgrading to 5.0.12, still facing the same issue. var(--white-color) is replaced with var(#fff).

**Comment by ludofischer** [comment]
> I was using 4.1.10 and encountered the same issue. After upgrading to 5.0.12, still facing the same issue. var(--white-color) is replaced with var(#fff).

Can you post a link to a repository that reproduces the issue? I can't reproduce this with 5.0.12. There's even a test for it https://github.com/cssnano/cssnano/pull/1247/files that passes. Neither `--white` nor `--white-color` get replaced.

**Comment by kameas** [comment]
@ludofischer hi! i created test project on vue 2+, you can clone it, install packages (but at first, you need to clear npm global cache using `npm cache clean --force` command), then run `npm run build`, and as a result, in `dist/css `directory you can find css file with --foreground:var(#fff)

https://github.com/kameas/css-variables-bug

**Comment by ludofischer** [comment]
@kameas Thank you for creating the reproduction. Unfortunately the repository you've posted uses cssnano 4 and it seems that @vue/cli 4 requires cssnano 4. The issue with variables been fixed in cssnano 5. To work around your issue could try to disable the postcss-colormin plugin.

**Comment by kameas** [comment]
@ludofischer I have similar dependency in my project, i noticed this bug on friday, and now, after i cleared global cache again - everything looks great

maybe some child dependency has been updated twice during this time, thank you for reaction and help
