### ISSUE TITLE
Add a configuration option to `postcss-convert-values` to disable converting 0% to 0

### ISSUE THREAD

**Issue by davepeck** [cssnano/cssnano#1258]
### What should be improved?

Converting from `0%` to `0`, _even in cases where `0` is valid_, may break behavior in some browsers.

Consider the following CSS used to animate the `padding-height` property:

```css
.item {
    padding-height: 0%;
}

.item.active {
    padding-height: 100%;
    transition: padding 200ms ease-in;
}
```

Converting the `0%` to `0` breaks the animation in the latest builds of Safari (macOS and iOS), because Safari sees the start and end state as having incompatible units. 

### Describe the solution you would like

Consider adding an option to `convertValues(...)` that disables conversion of zero-valued percentages into plain zero. 

Or: consider adding an option that disables conversion of _any_ zero values with units into plain zero.

### Possible alternatives

Alternatively: I might also consider this a bug; I'm not sure. 

And if it _is_ a bug, I'm further not sure whether it should be considered a bug with `postcss-convert-values` or with Safari! The behavior I describe above does _not_ reproduce in (for example) Chrome; whether Safari's behavior is more correct, or Chrome's, I'm genuinely not sure.

### Additional context

The difference between Safari and (for instance) Chrome's behavior is surprising.

### Are you willing to work on this?

- [X] Yes, I would like to help

**Comment by ludofischer** [comment]
I am sorry if I am missing something obvious, but I cannot find the `padding-height` CSS property in your example anywhere on the web. According to the commit log, `postcss-convert-values` has accumulated a list of exceptions over the years to work around some browser bugs, so we could add another one for this case, but if you're using some kind of proprietary or custom property you might be better of turning `postcss-convert-values` off completely.
From a cursory web search, it seems Safari does not handle transitions when the units have different values (see the WebKit bug report https://bugs.webkit.org/show_bug.cgi?id=79487 but there are others in their Bugzilla)

**Comment by ludofischer** [comment]
Closing since I can't find the CSS property in the issue (`padding-height`) mentioned anywhere else on the web and we've received no further information from the person who opened the issue.
