### ISSUE TITLE
Running the playground locally does not work

### ISSUE THREAD

**Issue by Siilwyn** [cssnano/cssnano#1361]
Hi! I'd like to test a new version for css-declaration-sorter locally with the cssnano playground however I can't get the playground to run.

After cloning, I ran (`master@b012425c`):
```sh
pnpm install
cd site
pnpm install
pnpm build:metadata
pnpm start
```

Opening the playground on localhost gives 404 on JS files, both in Firefox and Chromium (the latter only shows 404 errors and not the MIME type ones):
![image](https://user-images.githubusercontent.com/5701149/158068104-98dd27ef-7705-43cc-bf22-3d69a825e0d6.png)

The 'editor' hangs on "Loading CSS editor…".

**Comment by ludofischer** [comment]
You need to run webpack to build the playground JavaScript bundle:

```
pnpm webpack
```

**Comment by Siilwyn** [comment]
Ah cheers!
