### ISSUE TITLE
[Bug]: An unhandled exception occurred: Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by bmaraboi** [cssnano/cssnano#1379]
### Describe the bug

I am using angular 11 and when running prod command 'ng build --prod --build-optimizer --vendor-chunk' getting toLowerCase null error. 

As per logs it showing error in postcss-merge-longhand.js at line 740. 

The local run and build of project is working fine but when going for prod publish getting this error. Looks it is library issue and need to solve so posting a bug.

Any suggestion have on this, it will help lot. 

Thanks.

### Expected behaviour

Need to build project with prod command.

### Steps to reproduce

for angular prod command getting this issue,

### Version

5.0.6

### Preset

default

### Environment

```shell
Windows OS
```

### Package details

```shell
cssnano@5.0.6,
postcss@8.3.5
```

**Comment by ludofischer** [comment]
To solve this issue we need at least the input CSS, otherwise it's impossible to find out why the error happens.

**Comment by ludofischer** [comment]
It would better to try the latest cssnano version (5.1.5), the bug report says 5.0.6.

> I will check how I can share my project css files here as I need to take permission for that before sharing any file.

Are you able to reduce it to just the portion of CSS that triggers the error? There's no need to share the whole project.

If you're stuck you've got access to the cssnano configuration you can deactivate the `mergeLonghand` transform by passing
`{ mergeLonghand: false }` to cssnano.

**Comment by ludofischer** [comment]
I think it's going to be impossible to investigate this further, since not even the input CSS is provided in the issue and the error happens with Angular CLI , so with likely many transformations of the source besides cssnano.
