### ISSUE TITLE
[Bug]: `border-color` fallback incorrectly removed by `mergeLonghand`

### ISSUE THREAD

**Issue by david-crespo** [cssnano/cssnano#1396]
### Describe the bug

On the default preset, `border-color` is incorrectly having a fallback removed, while `background-color` does not. This does not happen on the `lite` preset in the Playground. I was able to narrow it down to `mergeLonghand` locally (turning it off fixes this) but I have not put together a proper repro proving that that's the cause.

### Input

```
.border-grey-1000 {
  border-color: rgb(37, 45, 49);
  border-color: color(display-p3 0.1451 0.1765 0.1922 / 1);
}

.bg-green-500 {
  background-color: rgb(72, 213, 151);
  background-color: color(display-p3 .2824 .8353 .5922 / 1);
}
```

### Output (whitespace added back in for readability):

```
.border-grey-1000 {
  border-color: color(display-p3 .1451 .1765 .1922/1)
}

.bg-green-500{
  background-color: #48d597;
  background-color: color(display-p3 .2824 .8353 .5922/1)
}
```

### Expected behaviour

I expect to see the `border-color` fallback left in place.

### Steps to reproduce

See [Playground](https://cssnano.co/playground/#eyJpbnB1dCI6Ii5ib3JkZXItZ3JleS0xMDAwIHtcbiAgYm9yZGVyLWNvbG9yOiByZ2IoMzcsIDQ1LCA0OSk7XG4gIGJvcmRlci1jb2xvcjogY29sb3IoZGlzcGxheS1wMyAwLjE0NTEgMC4xNzY1IDAuMTkyMiAvIDEpO1xufVxuXG4uYmctZ3JlZW4tNTAwIHtcbiAgYmFja2dyb3VuZC1jb2xvcjogcmdiKDcyLCAyMTMsIDE1MSk7XG4gIGJhY2tncm91bmQtY29sb3I6IGNvbG9yKGRpc3BsYXktcDMgLjI4MjQgLjgzNTMgLjU5MjIgLyAxKVxufSIsImNvbmZpZyI6ImNzc25hbm8tcHJlc2V0LWRlZmF1bHQifQ==)

### Version

Whatever is running in the Playground, probably 5.1.8

### Preset

default

### Environment

```shell
Playground
```

### Package details

```shell
Playground
```

**Comment by ludofischer** [comment]
Confirmed
