### ISSUE TITLE
[Bug]: constant() values are removed from output using default or advanced presets

### ISSUE THREAD

**Issue by jmlee2k** [cssnano/cssnano#1410]
### Describe the bug

constant() values are removed from the emitted css:

ex.
`border-top: constant(safe-area-inset-top) solid #000;`
becomes 
`border-top: solid #000`

### Expected behaviour

`constant()` values should be included as-is in the emitted css.  `env()` values (the standards-compliant ver of `constant()`) are included in the emitted css as expected.

### Steps to reproduce

playground using advanced preset
![image](https://user-images.githubusercontent.com/7396545/171045249-f0554cce-8ede-4b97-b28e-604a4d84031e.png)

playground using default preset
![image](https://user-images.githubusercontent.com/7396545/171045276-783ea6f5-e2e8-4aea-93dd-78254e3931bb.png)

### Version

5.1.10

### Preset

advanced

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 11.78 GB / 31.73 GB
```

### Package details

```shell
cssnano@5.1.10
postcss@8.4.14
```

### Additional context

source css:

```
#ui
{
    border-top: constant(safe-area-inset-top) solid #000;
    border-right: constant(safe-area-inset-right) solid #000;
    border-bottom: constant(safe-area-inset-bottom) solid #000;
    border-left: constant(safe-area-inset-left) solid #000;
}
````

**Comment by jmlee2k** [comment]
I believe I've narrowed this down to the `orderedValues` plugin:

source css:
```
#test
{
	border-top: constant(safe-area-inset-top) solid #000;
}
```

output using `preset: ['default']`
```
#test{border-top:solid #000}
```

output using `preset: ['default',{orderedValues:false}]`
```
#test{border-top:constant(safe-area-inset-top) solid #000}
```

**Comment by jmlee2k** [comment]
I've only done a quick investigation of the source, but it looks like `'constant'` should be added to this line: https://github.com/cssnano/cssnano/blob/master/packages/postcss-ordered-values/src/index.js#L75.

I'm happy to make a PR if someone with more familiarity with the source can confirm.

**Comment by alexander-akait** [comment]
Yes, PR welcome

**Comment by anrananran** [comment]
issue still here, not solved
