### ISSUE TITLE
[Bug]: Handling of 0% to 0 conversion

### ISSUE THREAD

**Issue by kyogreSS** [cssnano/cssnano#1434]
### Describe the bug

height:0% should not be converted to height:0. But in the latest version, it will be converted to 0.
For example: 
```
.test {
    height: 0%;
}
```
will be converted to
```
.orxMcomC{height:0}
```

### Expected behaviour

Should keep 0% for `height` 

### Steps to reproduce

1. Given a `height: 0%`
2. Run build
3. Check the output

### Version

5.1.13

### Preset

(no preset)

### Environment

```shell
System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.01 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
```

### Package details

```shell
├─┬ css-loader@5.2.7
│ └── postcss@8.4.16  deduped
├── cssnano@5.1.13 
├── postcss@8.4.16 
└─┬ stylelint@13.13.1
  ├─┬ autoprefixer@9.8.6
  │ └── postcss@7.0.36  deduped
  ├── postcss@7.0.36 
  ├─┬ postcss-less@3.1.4
  │ └── postcss@7.0.36 
  ├─┬ postcss-safe-parser@4.0.2
  │ └── postcss@7.0.36 
  ├─┬ postcss-sass@0.4.4
  │ └── postcss@7.0.36 
  ├─┬ postcss-scss@2.1.1
  │ └── postcss@7.0.36 
  └─┬ sugarss@2.0.0
    └── postcss@7.0.36
```

**Comment by ludofischer** [comment]
Why should it preserve the `%` sign? If the number is 0, CSS allows to omit the unit (see https://drafts.csswg.org/css-values/#lengths). Is this a browser compatibility issue?

**Comment by ludofischer** [comment]
I am going to close this since as far as I can see `height: 0` should be the same as `height: 0%` and I could not find a reference to a browser bug that would require to preserve the `%` either. Feel free to reopen if you have more information.

**Comment by yisibl** [comment]
> % is not a unit, and never generates a <length>; omitting it flips you into <length> territory (implying 0px or the equivalent), which can definitely be a behavior change in some circumstances.

https://github.com/sass/sass/issues/649#issuecomment-314894242
