### ISSUE TITLE
[Bug]: apostrophes and quotes are stripped from font-family

### ISSUE THREAD

**Issue by dovholuknf** [cssnano/cssnano#1438]
### Describe the bug

Made a css class using `font-family:"Russo one"` but after docusaurus miniified the css these quotes were stripped. That caused chrome browsers to not render the font correctly (Firefox did render correctly still). 

https://developer.mozilla.org/en-US/docs/Web/CSS/font-family states "Font family names must either be given quoted as strings, or unquoted as a sequence of one or more identifiers". That seems to me to mean those chars shouldn't be stripped.

I tried filling this big with docusaurus, the project actually using cssnano, but they couldn't be bothered to file this bug, so I'm not the "actual" dev using cssnano. See https://github.com/facebook/docusaurus/issues/8205

### Expected behaviour

Expected quotes or apostrophes to not be stripped

### Steps to reproduce

I'm not able to provide you reasonable steps to reproduce since I'm filling this bug on behalf of docusaurus (see https://github.com/facebook/docusaurus/issues/8205)

Hopefully it's clear anyway

### Version

I don't know

### Preset

(no preset)

### Environment

```shell
Linux, bash, docusaurus
```

### Package details

```shell
I'm on my mobile. I'll run this if you need me to
```

**Comment by slorber** [comment]
Docusaurus maintainer, can't really tell if removing quotes is legit or not, but the MDN link says it's not even though in practice it seems quotes can be removed (at least it works for me on Chrome/Firefox)

We use Webpack / cleancss / cssnano:

```js
new CssMinimizerPlugin<[CssNanoOptions, CustomOptions]>({
        minimizerOptions: [
          // CssNano options
          {
            preset: require.resolve('@docusaurus/cssnano-preset'),
          },
          // CleanCss options
          {
            inline: false,
            level: {
              1: {
                all: false,
                removeWhitespace: true,
              },
              2: {
                all: true,
                restructureRules: true,
                removeUnusedAtRules: false,
              },
            },
          },
        ],
        minify: [
          CssMinimizerPlugin.cssnanoMinify,
          CssMinimizerPlugin.cleanCssMinify,
        ],
      }),
```

I can confirm it's cssnano that removes the quotes, not cleancss)

Our CSS nano preset:

```js
import advancedBasePreset from https://github.com/cssnano/cssnano;
import postCssSortMediaQueries from https://github.com/solversgroup/postcss-sort-media-queries;
import postCssRemoveOverriddenCustomProperties from ['./remove-overridden-custom-properties'](https://github.com/facebook/docusaurus/blob/3558a091c64834b89189cfb30ea7e25b64b87d19/packages/docusaurus-cssnano-preset/src/remove-overridden-custom-properties/index.ts);

const preset: typeof advancedBasePreset = function preset(opts) {
  const advancedPreset = advancedBasePreset({
    autoprefixer: {add: false},
    discardComments: {removeAll: true},
    /* cSpell:ignore zindex */
    zindex: false,
    ...opts,
  });

  advancedPreset.plugins.unshift(
    [postCssSortMediaQueries, undefined],
    [postCssRemoveOverriddenCustomProperties, undefined],
  );

  return advancedPreset;
};
```

https://github.com/facebook/docusaurus/tree/main/packages/docusaurus-cssnano-preset

**Comment by alexander-akait** [comment]
@slorber Can you provide source code, removing quotes is allowed in some cases by spec (it is not recommend to do in source code, but it is valid for minication purposes), so you need investigate

**Comment by dovholuknf** [comment]
Yep - works fine in firefox, but failed in Brave. I don't know where the "authoritative" spec is for CSS but I'll try to find it to see if it's rigid about these quotes or not. the one mozilla link I found seemed pretty firm that they were mandatory...

https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
States, "Font family names must either be given quoted as strings, or unquoted as a sequence of one or more identifiers.” so stripping the quotes is a bug. I'll try filling it in the repo you indicate.

**Comment by alexander-akait** [comment]
https://www.w3.org/TR/css-fonts-4/#family-name-syntax

> Quotes are required around font-family names when they are not [valid CSS identifiers](https://www.w3.org/TR/CSS2/syndata.html#value-def-identifier). For example, a font family name requires quotes around it if it contains $, ! or /, but does not require quotes just because it contains spaces or a (non-initial) number or underscore. You can probably bet that almost every font family name you use will be a valid CSS identifier.

Ref: https://stylelint.io/user-guide/rules/list/font-family-name-quotes/

I think we need report about it in `Brave`, some minifier can do the same because it is valid by spec

**Comment by dovholuknf** [comment]
:| I have tried all the same steps as I did yesterday. Confirmed the unquoted style, and yet today brave behaves properly as does chrome. I'll close this issue now. If it comes back I'll post a bug to brave first with the w3.org link above referenced. Thanks @alexander-akait. Also thanks to @slorber for popping onto this issue. cheers.
