### ISSUE TITLE
[Bug]: prefixed css rules will be merged before `all` 

### ISSUE THREAD

**Issue by manniL** [cssnano/cssnano#1469]
### Describe the bug

Similar to https://github.com/cssnano/cssnano/issues/824.

> Regarding merging, `all` should forbid any other rule (except direction and unicode-bidi) of this selector to move accross it.

In this case, it happens for prefixed attributes like `-webkit-box-orient: vertical;`

### Expected behaviour

`-webkit-box-orient: vertical;` should not move before `all: unset;`

### Steps to reproduce

1. [Open the reproduction](https://cssnano.co/playground/#eyJpbnB1dCI6Ii5jbGFzcyB7XG4gIGFsbDogdW5zZXQ7XG4gIC13ZWJraXQtYm94LW9yaWVudDogdmVydGljYWw7XG4gIGNvbG9yOiAnYmxhY2snO1xufSIsImNvbmZpZyI6ImNzc25hbm8tcHJlc2V0LWRlZmF1bHQifQ==)
2. Push `minimize`
3. See `'.class{-webkit-box-orient:vertical;all:unset;color:"black"}`
4. Expected: `'.class{all:unset;-webkit-box-orient:vertical;color:"black"}

### Version

5.1.15

### Preset

default

### Environment

```shell
Website environment
```

### Package details

```shell
None as I used the playground
```

**Comment by ludofischer** [comment]
> This is fixed with `cssnano@6.0.2`.

It is fixed if I use the CLI but not in the playground but I think we can mark it as fixed as the playground version is known to be inconsistent (many modules are not meant to run in the browser).
