### ISSUE TITLE
[Feature Request]: Drop YAML config file support

### ISSUE THREAD

**Issue by ludofischer** [cssnano/cssnano#1473]
### What should be improved?

Stop shipping an entire YAML parser. 

### Describe the solution you would like

Remove the YAML config file support.

### Additional context

YAML support is not documented and it's probably not used by almost anyone. It came in as side-effect of the previous configuration library (cosmiconfig) which supported YAML by default. Removing YAML support drops one of the largest and most complex dependencies, which is probably also almost never used.

### Are you willing to work on this?

- [X] Yes, I would like to help

**Comment by alexander-akait** [comment]
I am :+1:
