### ISSUE TITLE
[Bug]: csscano combines two different @container queries

### ISSUE THREAD

**Issue by beldur** [cssnano/cssnano#1489]
### Describe the bug

cssnano combines these two different css selectors:

```
.mobile {
  @container (min-width: 200px) {
     display: none;
  }
}

.notMobile {
  @container (max-width: 100px) {
     display: none;
  }
}
```

The output becomes:

```
.mobile, .notMobile {
  @container (max-width: 100px) { display:none }
}
```

### Expected behaviour

cssnano should not combine these two selectors as they are different.

### Steps to reproduce

1. Open the playground (https://cssnano.co/playground/)
2. Add the following selectors
```
.mobile {
  @container (min-width: 200px) {
     display: none;
  }
}

.notMobile {
  @container (max-width: 100px) {
     display: none;
  }
}
```
4. click "minimize" and check the output

### Version

6.0.0

### Preset

default

### Environment

```shell
CSSNano Playground
```

### Package details

```shell
CSSNano Playground
```

**Comment by alexander-akait** [comment]
@beldur Yeah, sounds like a bug, do you want to send a PR?

**Comment by ludofischer** [comment]
Disabling `mergeRules` seems to solve it. I am surprised it does not skip or fail completely since when it was designed there were no container queries so having something looking like an `AtRule` inside a `Rule` would be unexpected.

**Comment by ludofischer** [comment]
@beldur Are you sure the snippet you've posted is the correct syntax for container queries? I have been looking at the spec and it seems that you cannot place a container query inside a rule, it should be:

```css
@container (min-width: 200px) {
  .mobile {
     display: none;
  }
}
@container (max-width: 100px) {
  .notMobile {
     display: none;
  }
}

```

**Comment by alexander-akait** [comment]
@ludofischer it is possible but it is in nested spec (stage is 0 or 1 currently)
