### ISSUE TITLE
[Bug]: calc() is removed when it contains unnecessary encompassing brackets

### ISSUE THREAD

**Issue by haditschRewe** [cssnano/cssnano#1490]
### Describe the bug

the calc() function from this declaration. is removed because of the encompassing bracket pair that is not necessary:

`stroke-dasharray: calc((var(--circumference) / var(--number-of-segments)))`

it works when the brackets are removed:
`stroke-dasharray: calc(var(--circumference) / var(--number-of-segments))`

### Expected behaviour

The calc function works regardless of an unnecessary bracket pair

### Steps to reproduce

1. paste this line of code into the cssnano playground (https://cssnano.co/playground/):
`stroke-dasharray: calc((var(--circumference) / var(--number-of-segments)))`
2. Click on `Minimize`
3. Observe that the calc() is removed from the minified line of code

### Version

nuxt 2.16.3

### Preset

(no preset)

### Environment

```shell
System:
    OS: macOS 13.3
    CPU: (12) arm64 Apple M2 Pro
    Memory: 1.80 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
```

### Package details

```shell
cssnano@5.1.15
postcss@8.2.15
```

**Comment by ludofischer** [comment]
Confirmed, it is an issue with postcss-calc: https://github.com/postcss/postcss-calc/issues/181
