### ISSUE TITLE
YAML vulnerability 

### ISSUE THREAD

**Issue by TannerS** [cssnano/cssnano#1495]
In response to https://github.com/cssnano/cssnano/issues/1494

will there be a fix in v5?

**Comment by ludofischer** [comment]
I am not planning a new 5.x release at the moment, because upgrading between 5.x and 6.x should be [fairly easy](https://github.com/cssnano/cssnano/releases/tag/cssnano%406.0.0). Besides, the vulnerability report does not concern the YAML version that was used by cssnano. The affected version of the YAML dependency is [>= 2.0.0-5 ](https://github.com/advisories/GHSA-f9xv-q969-pqx4), but cssnano was [still using YAML 1.x](https://github.com/cssnano/cssnano/commit/39a20405239191344b244df3a4326f3b3f87f246).

**Comment by TannerS** [comment]
We got multiple security scans and they say below that is vulnerability while above is the fixed version.



Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TannerS** [comment]
Correct, I think if u Google it it also says update to version 2, please correct me if I'm wrong

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TannerS** [comment]
I can't honestly speak about it. All I know multiple services security scans are showing it and for our service it has to be fixed or else we have to figure something else out lol but hopefully it is and other reporting tools show this

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TannerS** [comment]
For us, it's a dep of another dep of another dep so for us it's multiple levels deep so we can't control the versions other deps.use but if it's fixed at the lower level I'm hoping it can propagate up to the top level dep lol but it was worth a shot haha

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alexander-akait** [comment]
@TannerS please run `npm ls cssnano`

**Comment by TannerS** [comment]
<img width="839" alt="image" src="https://user-images.githubusercontent.com/8866319/234953192-5d8ad43a-db50-4d31-9c61-f3e45fdabd3c.png">

this is the secruity scan 

https://github.com/advisories/GHSA-f9xv-q969-pqx4

and our npm ls yaml 

```
├─┬ css-minimizer-webpack-plugin@3.4.1
│ └─┬ cssnano@5.1.15
│   └── yaml@1.10.2
└─┬ husky@4.3.8
  └─┬ cosmiconfig@7.1.0
    └── yaml@1.10.2 deduped


```

**Comment by TannerS** [comment]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/8866319/234955007-e08a8f61-80cd-440d-b125-a60da708cb4d.png">

**Comment by alexander-akait** [comment]
You can update `css-minimizer-webpack-plugin` very easy, just update `css-minimizer-webpack-plugin` to the latest stable version, `husky` is also easy to update

**Comment by TannerS** [comment]
Sure I'll look into that :)

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ludofischer** [comment]
I hope we can close this as they've corrected the affected range on the source website: https://huntr.dev/bounties/4b494e99-5a3e-40d9-8678-277f3060e96c/

**Comment by TannerS** [comment]
Cool thank you

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
