### ISSUE TITLE
[Feature Request]: Regular Expression Denial of Service (ReDOS) 

### ISSUE THREAD

**Issue by juztinlazaro** [cssnano/cssnano#1505]
### What should be improved?

Fixing security vul `Regular Expression Denial of Service (ReDOS) ` in `color-string

cssnano@4.1.10 requires color-string@^1.6.0 via a transitive dependency on color@3.2.1`

### Describe the solution you would like

![image](https://github.com/cssnano/cssnano/assets/10995629/2052bb50-3eea-4724-9f78-81e3762f8373)

### Possible alternatives

got issue when i tried resolutions

### Additional context

![image](https://github.com/cssnano/cssnano/assets/10995629/2052bb50-3eea-4724-9f78-81e3762f8373)

### Are you willing to work on this?

- [ ] Yes, I would like to help

**Comment by ludofischer** [comment]
Is there something preventing you from updating to a more recent cssnano version? cssnano 5.x and 6.x do not depend on `color` and  `color-string`. The last cssnano 4.x version was 4.1.11 almost two years ago, I don't think we're going to update the dependencies for that.

**Comment by juztinlazaro** [comment]
@ludofischer thanks updating to v5.x or v6.x

**Comment by ludofischer** [comment]
@juztinlazaro You probably also need to update PostCSS to [PostCSS 8](https://github.com/postcss/postcss/releases/tag/8.0.0).
