### ISSUE TITLE
`node`s without throw an error [discard-duplicates]

### ISSUE THREAD

**Issue by brandonpittman** [cssnano/cssnano#1510]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `postcss-discard-duplicates@5.1.0` for the project I'm working on.

I'm importing a package that exports Vanilla Extract sprinkles and imports them into a Remix app. I seem to be running into an issue where nodes have no length.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/postcss-discard-duplicates/src/index.js b/node_modules/postcss-discard-duplicates/src/index.js
index 28ca2ca..ff1983d 100644
--- a/node_modules/postcss-discard-duplicates/src/index.js
+++ b/node_modules/postcss-discard-duplicates/src/index.js
@@ -69,7 +69,7 @@ function equals(nodeA, nodeB) {
   }
 
   if (a.nodes) {
-    if (a.nodes.length !== b.nodes.length) {
+    if (a.nodes?.length !== b.nodes?.length) {
       return false;
     }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by alexander-akait** [comment]
@brandonpittman Hello, do you want to send a PR?

**Comment by brandonpittman** [comment]
@alexander-akait 

Sure thing. Created one [here](https://github.com/brandonpittman/cssnano/pull/1).
