### ISSUE TITLE
[Bug]: cssnano.co is down

### ISSUE THREAD

**Issue by ludofischer** [cssnano/cssnano#1569]
### Describe the bug

The website at cssnano.co has been inaccessible for a few days

### Expected behaviour

It should be possible to load the website

### Steps to reproduce

No settings have been changed on the GitHub pages side. `dig` returns no more A records for cssnano.co

### Version

all

### Preset

(no preset)

### Environment

```shell
Not relevent
```

### Package details

```shell
Not relevant
```

### Additional context

I haven't got any access to the domain registration, so I don't think I can fix this on my own.

**Comment by ludofischer** [comment]
We could also host the website on the github.io domain.

**Comment by alexander-akait** [comment]
@ludofischer Yeah, good idea

**Comment by ludofischer** [comment]
> @ludofischer Yeah, good idea

I've removed the custom domain, so now the site is here: https://cssnano.github.io/cssnano/ (broken likely because of wrong assets path). I think it would be better to get it under https://cssnano.github.io/ without the subdirectory if possible.

**Comment by alexander-akait** [comment]
Thank you for your help

**Comment by ludofischer** [comment]
If we want to publish the website without a subdirectory, we need to create a new repository in the cssnano organization: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites Since the playground website is pulling cssnano from the source files in the repository, I think I will stick with cssnano.github.io/cssnano

**Comment by alexander-akait** [comment]
@ludofischer fixed
