### ISSUE TITLE
[Bug]: Column gap gets overridden by gap

### ISSUE THREAD

**Issue by alexander-akait** [cssnano/cssnano#1588]
### Bug report

Sorting the CSS attributes causes the wrong styles to take precedence

### Actual Behavior

Class written like that
```
.card {
   gap: 0;
   column-gap: 10px;
   row-gap: 15px;
}
```

is processed to the following output
```
.card {
  column-gap: 10px;
  gap: 0px;
  row-gap: 15px;
}
```

Causing column-gap to be overridden by gap

### Expected behaviour

```css
.card {
  gap: 10px 15px;
}
```

### Steps to reproduce

Just run

### Version

latest

### Preset

default

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 75.31 MB / 16.00 GB
  Binaries:
    Node: 20.10.0 - /opt/homebrew/opt/nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - /opt/homebrew/opt/nvm/versions/node/v20.10.0/bin/npm
```

### Package details

```shell
latest
```

### Additional context

https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/259

**Comment by ludofischer** [comment]
It might because https://github.com/Siilwyn/css-declaration-sorter/blob/master/src/core/shorthand-data.mjs is missing the `gap` property.

**Comment by ludofischer** [comment]
Opened https://github.com/Siilwyn/css-declaration-sorter/issues/380
