### ISSUE TITLE
[Bug]: Build is breaking since release 7.0.2

### ISSUE THREAD

**Issue by jay8t6** [cssnano/cssnano#1630]
### Describe the bug

The build is failing with the following incompatibility error:

error cssnano@7.0.2: The engine "node" is incompatible with this module. Expected version "^18.12.0 || ^20.9.0 || >=22.0". Got "21.7.3"
error Found incompatible module.

### Expected behaviour

No error when building the project.

### Steps to reproduce

Install the latest cssnano as a dependency and try to build the project with node 21 image.

### Version

7.0.2

### Preset

(no preset)

### Environment

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 613.22 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
```

### Package details

```shell
└─┬ nuxt@3.11.2
  └─┬ @nuxt/vite-builder@3.11.2
    └── cssnano@7.0.2
```

**Comment by ludofischer** [comment]
Hello, we explicitly do not support Node.js 21 as it is currently unsupported and has never been a long term support release ('LTS' see https://github.com/nodejs/Release). Is there a specific reason you need to use Node.js 21?

**Comment by FrancescoMussi** [comment]
Getting same error. 
`error cssnano@7.0.2: The engine "node" is incompatible with this module. Expected version "^18.12.0 || ^20.9.0 || >=22.0". Got "16.20.2"`

Is node v16 not supported anymore?

**Comment by ludofischer** [comment]
> Getting same error. `error cssnano@7.0.2: The engine "node" is incompatible with this module. Expected version "^18.12.0 || ^20.9.0 || >=22.0". Got "16.20.2"`
> 
> Is node v16 not supported anymore?

No, it is not supported anymore.

**Comment by tuannguyenminh2086** [comment]
I also have same issue: `error cssnano-preset-default@7.0.2: The engine "node" is incompatible with this module. Expected version "^18.12.0 || ^20.9.0 || >=22.0". Got "20.5.0"` 

What can I do now?

**Comment by ludofischer** [comment]
> I also have same issue: `error cssnano-preset-default@7.0.2: The engine "node" is incompatible with this module. Expected version "^18.12.0 || ^20.9.0 || >=22.0". Got "20.5.0"`
> 
> What can I do now?

You could move to Node.js 20.14 .  Or depending on your package manager there might be a flag to ignore the engines in `package.json`.
