### ISSUE TITLE
[Bug]: Unclosed comment

### ISSUE THREAD

**Issue by tiennguyen1293** [cssnano/cssnano#1640]
### Describe the bug

I'm facing this issue when building an app with Webpack 5. 
```javascript
[
  ...
  new CssMinimizerPlugin(),
  ...
]

``` 

### Expected behaviour

It should build successfully after I removed all comments from the SCSS file. Thank you very much

### Steps to reproduce

run `yarn build`

<img width="275" alt="image" src="https://github.com/cssnano/cssnano/assets/26110369/ae444c38-b2ed-4095-922f-f94e7e2074ba">
<img width="275" alt="image" src="https://github.com/cssnano/cssnano/assets/26110369/aeadc2af-a1e7-4c0b-8ef4-2c7e99b24c19">

![image](https://github.com/cssnano/cssnano/assets/26110369/8109d5e9-40f0-42c1-aff7-5f8d50245f9e)

### Version

cssnano "^7.0.1"

### Preset

default

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 62.22 MB / 16.00 GB
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
  Browsers:
    Brave Browser: 126.1.67.116
    Chrome: 126.0.6478.63
    Edge: 126.0.2592.68
    Safari: 17.5
```

### Package details

```shell
Packages:
    babel-loader: ^8.2.3 => 8.3.0
    case-sensitive-paths-webpack-plugin: 2.4.0 => 2.4.0
    css-loader: 6.5.1 => 6.5.1
    css-minimizer-webpack-plugin: ^7.0.0 => 7.0.0
    eslint-webpack-plugin: ^3.1.1 => 3.2.0
    file-loader: ^6.2.0 => 6.2.0
    git-revision-webpack-plugin: ^5.0.0 => 5.0.0
    html-webpack-plugin: ^5.5.0 => 5.6.0
    pnp-webpack-plugin: 1.6.4 => 1.6.4
    postcss-loader: ^6.2.1 => 6.2.1
    react-s3-uploader: ^5.0.0 => 5.0.0
    resolve-url-loader: ^4.0.0 => 4.0.0
    sass-loader: ^12.3.0 => 12.6.0
    source-map-loader: ^3.0.0 => 3.0.2
    style-loader: ^3.3.1 => 3.3.4
    terser-webpack-plugin: ^5.3.10 => 5.3.10
    webpack: ^5.64.4 => 5.92.0
    webpack-dev-server: 4.15.2 => 4.15.2
    webpack-manifest-plugin: ^4.0.2 => 4.1.1
    workbox-webpack-plugin: ^6.4.1 => 6.6.1
```

**Comment by ludofischer** [comment]
I cannot reproduce this with just this information. Can you add a minimal reproduction? Are you transforming the Sass files into CSS before attempting to minimize them?

**Comment by tiennguyen1293** [comment]
Hi @ludofischer , thank you for your quick response.

> I cannot reproduce this with just this information. Can you add a minimal reproduction?
- I tried, but I cannot reproduce on sample minimal.

> Are you transforming the Sass files into CSS before attempting to minimize them?
- Yes, I'm transforming the Sass files into CSS before attempting to minimize them.

Could there be any clues from my transformation from Sass?

**Comment by ludofischer** [comment]
> Could there be any clues from my transformation from Sass?

Sure, I cannot say without seeing any of the Sass or CSS being processed. I also do not use Sass, so I cannot really advise you here.

**Comment by ludofischer** [comment]
Using cssnano alone does not reproduce this issue, at this point I cannot understand whether it is an issue with cssnano or the other tools.

**Comment by tiennguyen1293** [comment]
Thank for your support. i will investigate more
