### ISSUE TITLE
[Bug]: discardDuplicates does not work properly

### ISSUE THREAD

**Issue by Javlon721** [cssnano/cssnano#1649]
### Describe the bug

I have this webpack code 
`{
    loader: "postcss-loader",
    options: {
      postcssOptions: {
        plugins: [
          [
            "cssnano",
            {
              preset: 'default'
            }
          ],
          [
            "postcss-sort-media-queries",
            {
              sort: "desktop-first"
            }
          ],
          [
            "postcss-preset-env",
            {
              env: isDev ? 'development' : "production"
            }
          ],
        ],
      },
    },
  };
`
so after postcss-preset-env plugin resolved on this css code
`:fullscreen {
	a {
		display: none;
	}
}`
i have this 
`
:-webkit-full-screen a {
	display: none;
}
:-ms-fullscreen a {
	display: none;
}
:fullscreen a {
	display: none;
}
`
which i want to be grouped because they are same like this
`
:-webkit-full-screen a,
:-ms-fullscreen a,
:fullscreen a {
	display: none;
}
`
cssnano works perfectly with handwrite css code but when it comes to created via plugin postcss-preset-env which does autoprefix things it does not work

### Expected behaviour

i expect this code
`:-webkit-full-screen a {
	display: none;
}
:-ms-fullscreen a {
	display: none;
}
:fullscreen a {
	display: none;
}`

look like this

`:-webkit-full-screen a,
:-ms-fullscreen a,
:fullscreen a {
	display: none;
}`

### Steps to reproduce

i use this code with latest versions of all loaders/plugins etc

`
    loader: "postcss-loader",
    options: {
      postcssOptions: {
        plugins: [
          [
            "cssnano",
            {
              preset: 'default'
            }
          ],
          [
            "postcss-sort-media-queries",
            {
              sort: "desktop-first"
            }
          ],
          [
            "postcss-preset-env",
            {
              env: isDev ? 'development' : "production"
            }
          ],
        ],
      },
    },
  };`

### Version

7.0.4

### Preset

default

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 92.00 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
```

### Package details

```shell
├─┬ css-minimizer-webpack-plugin@7.0.0
│ └── cssnano@7.0.4 deduped
└── cssnano@7.0.4
```

**Comment by ludofischer** [comment]
This also happens when you add the browser prefixes manually, it might have been done on purpose. Maybe sometimes combining the browser prefixed properties leads to undesirable results?

**Comment by ludofischer** [comment]
The reason cssnano does not combine rules with prefixed selectors is that browsers will ignore the whole rule if they don't support one of the selectors (https://www.w3.org/TR/CSS21/syndata.html#rule-sets), so I don't think this is a bug.
