### ISSUE TITLE
Better handling of 0% to 0 conversion.

### ISSUE THREAD

**Issue by ben-eb** [cssnano/cssnano#229]
So I'd like to continue on a conversation that I had last week from Twitter;

https://twitter.com/briankardell/status/750420488837619712

In essence we discussed that the `0%` to `0` conversion is _not_ an optimisation which we can apply to any arbitrary property/value pair. In general, the policy is that when `<percentage>` can be turned into `<length>`, then `0% == 0`. It's just not always possible to apply this policy, so semantically the values can be different, _depending on the property_.

Up until this point I have followed clean-css' behaviour for `0%`—there's a [nice issue pointing out the differences](https://github.com/jakubpawlowicz/clean-css/issues/635)—but it's clear that we should handle this better in future. I'm willing to change the behaviour from a [blacklist of properties](https://github.com/ben-eb/postcss-convert-values/blob/d94d7d39d076f5dfa531f8c8161fe92008f11370/src/index.js#L34-L42) to a whitelist, but I need input from the community as to what properties I should be adding to this list.

This is the kind of thing that could benefit from browser testing, so please, if you have had problems in the past with this kind of conversion and would like to see the behaviour changed, your feedback would be really appreciated.

**Comment by bkardell** [comment]
How much does this particular class of optimization really save?  I have trouble imagining that it is worth it to ever do it.  Either you are only using it a very few times, in which case it's a few characters at best or you do _really a lot_.  If you do it really a lot, gzip is probably equally your friend whether it is 0 or 0%.  Ultimately, it just seems like it is likely super negligible to me, I'd skip it altogether as an optimization I think.

**Comment by tabatkins** [comment]
Specifically, cases like `height` are problematic - % heights are resolvable to lengths if and only if the containing block has a definite height.  In the common case (`height: auto`), the % instead gets turned into `auto`.

I don't have the time to give you an explicit list, but if you can produce a list of things that use %s, I'm happy to review it and tell you which ones can be problematic.

**Comment by ben-eb** [comment]
@bkardell It's true that gzip has more impact in terms of overall file size, but it isn't enough to simply gzip a file. More compression can be achieved by doing this work, as you can see with modules such as [css-size](https://github.com/ben-eb/css-size). Indeed, you can probably make this argument against most optimisations—for example [postcss-normalize-url](https://github.com/ben-eb/postcss-normalize-url) offers path resolution `/foo/../bar/baz` => `/bar/baz`—but even very edge case optimisations like this one [have their place](https://github.com/giakki/uncss/issues/156), and fits in cssnano's remit of trying to compress a CSS file as much as possible.

My position has always been that if there is a shorter *equivalent* way of writing some CSS then it is worth writing a transform that can make this possible. That counts for `0%` to `0` as much as `0.5s` to `.5s`. Our problem here is that `0%` to `0` is not always possible, not the one character difference. 😄 

@tabatkins No problem, I appreciate any input! I did a very quick review of the integration tests and turned off percentage removal; here's a list of "real world" CSS definitions that did use `0%` which were converted to `0`;

```css
.rules {
  transform: translateX(0%);
  transform: translateY(0%);
  transform: translate3d(0%, -100%, 0);
  top: 0%;
  right: 0%;
  left: 0%;
  width: 0%;
  margin: 0% 1rem;
  margin-right: 0%;
  padding-right: 0%;
  padding-left: 0%;
  background-image: linear-gradient(90deg, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.0001));
}
```

Note that we currently don't transform `height` or `min-height` when they are defined as `0%`.

**Comment by tabatkins** [comment]
All of those are safe to simplify, iirc.

**Comment by bkardell** [comment]
@ben-eb I meant specifically shortening 0% to 0, not all of the css nano stuff... it just doesn't seem like that big an optimization and you'll potentially just have to keep tweaking it as new things are added... I'm not suggesting it's bad that you do it, I just was suggesting that in this case it might just make more sense not to.

**Comment by ben-eb** [comment]
I don't mind. 😄

**Comment by andyjansson** [comment]
Looks like we're already handling all of these cases safely and correctly.

**Comment by yisibl** [comment]
> Looks like we're already handling all of these cases safely and correctly.

No, I strongly oppose omitting the unit of percentage, as this is unsafe.

The current proposal misinterprets the specification and is overly fixated on removing this single character.

See: https://github.com/sass/sass/issues/649#issuecomment-314891286
https://codepen.io/judowalker/pen/xrMxWj
