### ISSUE TITLE
Feature: focus

### ISSUE THREAD

**Issue by marcobiedermann** [cssnano/cssnano#237]
Remove `:focus` state from all elements which are not `a`, `button` or `input`.
Using `:focus` on `div` or `li` won't have any effect at all.

Input:

```
.dropdown li:focus > ul,
.dropdown li:hover > ul {
  ...
}
```

Optimized to:

```
.dropdown li:hover > ul {
  ...
}
```

**Comment by ben-eb** [comment]
Not *quite* accurate. Focus styles affect `textarea` also, and are also applied to `contenteditable` elements.


```html
<div contenteditable>
  Focus styles are triggered when editing the content here.
</div>

<div contenteditable="true">
  Focus styles are triggered when editing the content here. (alternate syntax)
</div>
```

Seems like a niche use case to me...

**Comment by delorge** [comment]
Assuming that one could use [focus plugin](https://github.com/postcss/postcss-focus), adding this kind of functionality is reasonable

**Comment by andyjansson** [comment]
Closing this since this feature is of dubious value and it's very unlikely that we'll implement it.
