### ISSUE TITLE
Cssnano is reordering overridden properties and breaking the style

### ISSUE THREAD

**Issue by duncanawoods** [cssnano/cssnano#242]
I am using a shared base class in less and then overriding properties when needed. I am finding that cssnano is reordering the overridden properties which breaks the style.

A simplified example .less looks like this:

```
.cell-label {
    font-size: 11px;
}
.heading-label-cell {
    .cell-label;
    color: @heading-colour;
    font-size: 13px;
}
.question-label-cell {
    .cell-label;
    color: @question-colour;
}
```

Which is then expanded to css looking like:

```
.heading-label-cell {
  font-size: 11px;
  font-size: 13px;
  color:#616161;
}
.question-label-cell {
  font-size: 11px;
  color: #0073d6;
}
```

But cssnano then does the following which has reordered the font-size property:

```
.heading-label-cell {
    color:#616161;
    font-size:13px
}
.heading-label-cell,.question-label-cell {
    font-size:11px;
}
.question-label-cell {
    color:#0073d6
}
```

Stripping out duplicate rules from a class before trying to merge classes seems like an easy first-pass optimisation that would avoid this bug.

**Comment by ben-eb** [comment]
For declaration merging (which is in the pipeline after css-values is completed), see https://github.com/ben-eb/cssnano/issues/86.

**Comment by andyjansson** [comment]
This doesn't seem to be an issue anymore.
