### ISSUE TITLE
Feature: Reduce custom property identifiers (unsafe)

### ISSUE THREAD

**Issue by ben-eb** [cssnano/cssnano#262]
Input:

``` css
:root {
  --foo: red;
}
```

Output:

``` css
:root {
  --a: red;
}
```

**Comment by sylvainpolletvillard** [comment]
Beware of overriding: http://codepen.io/sylvainpv/pen/WpQYbg

**Comment by chriseppstein** [comment]
This will need configuration to leave some idents alone if they are set via js or inline styles.

**Comment by andyjansson** [comment]
Closing this since we are now only focusing on safe optimisations.

**Comment by muuvmuuv** [comment]
For anyone who wants something like that but for manual use, I have made a simple little script:

https://github.com/muuvmuuv/reduce-custom-properties
