### ISSUE TITLE
Minifying keyframes name.

### ISSUE THREAD

**Issue by dangreen** [cssnano/cssnano#317]
IE11 on Windows 7 ignores case in keyframes name, thus `W` detects as `w` keyframe.

**Comment by ben-eb** [comment]
Ahh, that's unfortunate. Does this affect Edge too?

**Comment by dangreen** [comment]
@ben-eb 
Windows 7 IE 11 - not ok
Windows 8 IE 11 - not ok
Windows 10 IE 11 and Edge - ok

I can't test edge on windows 8 and 10. For testing I use BrowserStack.

**Comment by ben-eb** [comment]
Okay, thanks for the info. 👍 

For now you can override the encoding function, which will suffice until we can find out a better way to handle browser support (thinking about browserslist for this, see https://github.com/ben-eb/cssnano/issues/80); this one will produce no uppercase characters. 😄 

```js
function encoder (val, num) {
    let base = 26;
    let characters = 'abcdefghijklmnopqrstuvwxyz';
    let character = num % base;
    let result = characters[character];
    let remainder = Math.floor(num / base);
    if (remainder) {
        base = 38;
        characters = characters + '0123456789-_';
        while (remainder) {
            character = remainder % base;
            remainder = Math.floor(remainder / base);
            result = result + characters[character];
        }
    }
    return result;
};
```

https://github.com/ben-eb/postcss-reduce-idents#encoder

The usage in cssnano should be:

```js
cssnano.process(css, {
  reduceIdents: {encoder}
}).then(result => console.log(result.css));
```

**Comment by dangreen** [comment]
I already use `reduceIdents: false`, thanks!

**Comment by ben-eb** [comment]
Sure, that works too. 😄

**Comment by ludofischer** [comment]
Closing this as according to the original report the problem only occurs on IE 11 on Windows versions before Windows 10, but Microsoft ended mainstream support for those in 2018 (https://docs.microsoft.com/en-us/lifecycle/products/windows-81). The encode option is also documented now: https://github.com/cssnano/cssnano/tree/master/packages/postcss-reduce-idents#encoder
