### ISSUE TITLE
escaped CSS

### ISSUE THREAD

**Issue by tomhodgins** [cssnano/cssnano#322]
```css
\64 \69 \76 { \63 \6f \6c \6f \72 : \72 \67 \62 \61 \28 \32 \35 \35 \2c \30 \2c \30 \2c \2e \37 \35 \29 }
```

## correct minification

```css
\64\69\76{\63\6f\6c\6f\72:\72\67\62\61\28\32\35\35\2c\30\2c\30\2c\2e\37\35\29}
```

- optional single whitespace allowed after CSS character escapes, in selectors, property names, and values

## CSSnano output

```css
\64 \69 \76{\63:\72 \67 \62 \61 \28 \32 \35 \35 \2c \30 \2c \30 \2c \2e \37 \35 \29}
```

- didn't minify optional whitespace
- truncated property name from `\63\6f\6c\6f\72` to `\63`

**Comment by tomhodgins** [comment]
A second example of a very similar thing:

```css
\64 \69 \76 ::\62 \65 \66 \6f \72 \65 {
  \63 \6f \6e \74 \65 \6e \74 : '\48 \45 \4c \50 \20 \4d \45 \20 \45 \53 \43 \41 \50 \45 \20 \54 \48 \49 \53 \20 \43 \53 \53'
}
```

## correct minification

```css
\64\69\76:\62\65\66\6f\72\65{\63\6f\6e\74\65\6e\74:'\48\45\4c\50\20\4d\45\20\45\53\43\41\50\45\20\54\48\49\53\20\43\53\53'}
```

- optional single whitespace allowed after CSS character escapes, in selectors, property names, and values

## CSSnano output

```css
\64 \69 \76 ::\62 \65 \66 \6f \72 \65{\63:"\48 \45 \4c \50 \20 \4d \45 \20 \45 \53 \43 \41 \50 \45 \20 \54 \48 \49 \53 \20 \43 \53 \53"}
```

- didn't minify optional whitespace
- truncated property name from `\63\6f\6e\74\65\6e\74` to `\63`

**Comment by ben-eb** [comment]
https://github.com/postcss/postcss/issues/933

**Comment by andyjansson** [comment]
Doesn't look like there's any truncation anymore. Closing.
