### ISSUE TITLE
cssnano - ignore code?

### ISSUE THREAD

**Issue by s10wen** [cssnano/cssnano#344]
Wondering if there is an option like this:

```
/* cssnano:start - ignore this code */
.test {
  colour: #ffffff;
};
/* cssnano:finish - ignore this code */
```

So the output css would remain as `#ffffff` in this instance.

**Comment by ben-eb** [comment]
No, nothing like this right now. It would require a revamp of the codebase to be able to do this, as comments are currently stripped out.

**Comment by s10wen** [comment]
@ben-eb thanks Ben. For now then, I can create a new `gulp` task with different options.

**Comment by andyjansson** [comment]
Closing the issue since it's unlikely that we will implement something like this.
