### ISSUE TITLE
Deprecate wrapper modules in favour of PostCSS runners?

### ISSUE THREAD

**Issue by ben-eb** [cssnano/cssnano#364]
Once version 4 lands, I want to deprecate all of the wrapper modules and recommend that people use the appropriate PostCSS runner instead. I have a few reasons:

_Reasons for deprecation:_

* Less maintenance; we don't need to update each runner every time a new major release is cut.
* Benefit of shared ecosystem; we automatically benefit from new features as they are added to
PostCSS runners. PostCSS CLI is much more robust than our own for instance.
* One place for issues; the CLI & gulp module are common places to report issues that are not really meant to go there. I would prefer that users open issues here and so I get a lot of duplication when they do not.
* Performance: Recommending PostCSS runners instead of maintaining our own mean that people can use a single tool to apply many PostCSS plugins alongside cssnano in one pass.

_Reasons against deprecation:_

* Simplicity; installing cssnano-cli is much easier than having to worry about configuration. But I plan to solve this with a getting started guide for PostCSS CLI that includes a simple config.

Copying in @dlepaux (https://github.com/dlepaux/cssnano-brunch) & @sindresorhus (https://github.com/sindresorhus/broccoli-cssnano, https://github.com/sindresorhus/grunt-cssnano)

**Comment by sindresorhus** [comment]
Sounds good to me. Just mention me again here when I need to do so.

**Comment by evilebottnawi** [comment]
Looks we already improve documentation. Feel free deprecated all `cssnano` wrappers. Thanks!
