### ISSUE TITLE
Disable optimization in v4.0.0-rc.1

### ISSUE THREAD

**Issue by michaelbull** [cssnano/cssnano#391]
Hi, I'm trying to use the advanced preset as I would like the majority of the optimizations it offers, however I need to disable a specific optimization (to avoid it renaming keyframes).

I'm using the following configuration and it doesn't seem to be disabling the `postcss-reduce-idents` optimization:

```
            'preset': [
                'advanced',
                {
                    'autoprefixer': { 'add': true },
                    'postcss-reduce-idents': false
                }
            ]
```

Please can you advise? Thanks.

**Comment by andyjansson** [comment]
Try the following:

```js

            preset: ['advanced', {
                reduceIdents: false,
            }],
```

**Comment by michaelbull** [comment]
Thanks @andyjansson. Is there a list of keys that correspond to the various optimizers?

**Comment by andyjansson** [comment]
Not to my knowledge. The documentation hould definitely be updated with that. The rule is to remove the "postcss-" part and then just camelcase the rest.

**Comment by michaelbull** [comment]
Thanks again @andyjansson. I'll defer self-closing this issue to hopefully shine a light on the missing documentation.

**Comment by ben-eb** [comment]
It's covered in the presets guide but the information architecture could be clearer still. 😄 

http://cssnano.co/guides/presets/#options-syntax

**Comment by michaelbull** [comment]
Thanks for the response @ben-eb!

**Comment by andyjansson** [comment]
The optimisations are now listed according to their keys. Closing.
