### ISSUE TITLE
Policy Change: No more unsafe optimizations.

### ISSUE THREAD

**Issue by chriseppstein** [cssnano/cssnano#424]
There's a class of optimizations that cssnano has done, historically, that are provably unsafe for some constructed documents using the css selectors being optimized. The cascade is finicky optimizations that are safe for one application might not be safe for another, or even safe for the same application at a later point in time as it evolves. Optimization is fundamentally a user-experience feature, but seeing the webpage as expected, is a more important end-user experience concern that should not take precedence.

Many such optimizations can be made safely only when the templates/markup using them are taken into account. I'm currently writing a css optimizer (named `OptiCSS`) that is driven by template-analysis. It will be open sourced early next year. In the meantime, I will be closing any unsafe optimization feature requests for cssnano and linking them to this issue -- when that project is publicly released, we'll port any issues that makes sense to that project.

OptiCSS is harder to adopt than cssnano because it requires a more intrusive build integration, but it is able to do much more aggressive optimizations. The data I'm seeing on one real-world application shows that adding OptiCSS saves 30% *after brotli compression*, on top of what you get with css minifiers like cssnano -- and this is before all of the planned optimizations have been implemented in OptiCSS.

![optimization comparison table](https://user-images.githubusercontent.com/1839/32809796-27280718-c94d-11e7-8825-68ef6c45b0ff.png)

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/linkedin/opticss, thanks for new tool
