### ISSUE TITLE
postcss-merge-longhead@4.0.0-rc.2: invalid `border` output

### ISSUE THREAD

**Issue by jrencz** [cssnano/cssnano#429]
I'm using cssnano with `default preset`

with `mergeLonghand` set to `false` the output does not break the styles.

I noticed that the problem is the fact that `postcss-merge-longhead` produces something like this:

```css
border: #c9d8e6 currentColor;
```

when original is:

```css
border: 1px solid #c9d8e6;
```

**Comment by evilebottnawi** [comment]
Please test with latest `cssnano` version and feel fre to create new issue if problem still exists, thanks!
