### ISSUE TITLE
Add postcss-css-variables to unsafe list

### ISSUE THREAD

**Issue by clarcharr** [cssnano/cssnano#441]
This will, under the assumption that the CSS variables in the file aren't referenced anywhere else, inline the variables directly into the definitions. Perhaps modifications can be made to ensure that the resulting CSS is smaller, but I think that a transformation like this would be great to add to cssnano.

**Comment by WDD-Marv** [comment]
postcss-custom-properties already does this ?

**Comment by andyjansson** [comment]
Custom properties are dependent upon the cascade. It's unsafe to inline the variables, and goes against our policy change to only accept safe optimisations. If you want to inline custom properties, use [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties).
