### ISSUE TITLE
Remove impossible selectors

### ISSUE THREAD

**Issue by clarcharr** [cssnano/cssnano#443]
I use partial selectors in SASS which sometimes produces impossible selectors if you're not careful. These selectors are valid syntax but can never match an element, so, can safely be removed.

A few examples I thought of:

* `tag:not(tag)`
* `:matches(h1):matches(h2)`
* `html html` (assuming well-formed HTML)
* `p div` (again, assuming well-formed HTML)
* ...

**Comment by chrisdothtml** [comment]
Do you really have enough impossible selectors in your codebase to notice a bundle size benefit from removing them?

**Comment by clarcharr** [comment]
@chrisdothtml yes. `:not` especially, as I use `%partial:not(%other)` in a few places. Sure, there are ways of getting around this and I have also suggested removing these during compilation in sass, but I think that having the option of removing these in minification tools is also a good idea, even if not enabled by default.

**Comment by andyjansson** [comment]
Closing this due to being an issue which is likely difficult to implement and which provides very little value.
