### ISSUE TITLE
Simplify :matches and :not selectors

### ISSUE THREAD

**Issue by clarcharr** [cssnano/cssnano#445]
A few examples:

* `:matches(h1, h2):matches(h1)` => `:matches(h1)`
* `p:not(p.tag)` => `p:not(.tag)`

**Comment by Justineo** [comment]
These are unsafe optimization because specificity will change.

**Comment by andyjansson** [comment]
Closing this due to being of dubious value and, as @Justineo mentioned, unsafe, which is against our current policy of only accepting safe optimisations.
