### ISSUE TITLE
Update deps, especially autoprefixer

### ISSUE THREAD

**Issue by bminer** [cssnano/cssnano#447]
Can we update the deps for this project?  Does cssnano still depend on autoprefixer?  If so, can you push to autoprefixer@8?  The Bootstrap package.json file has a `browserslist` key that has filters that only work in autoprefixer@>7.

Since I'm using parcel-bundler (depends on cssnano), I get weird errors in the build.

**Comment by Siilwyn** [comment]
@ben-eb do you need help maintaining? I can definitely do this.

**Comment by Zashy** [comment]
Even with the local browserslist updated in cssnano it requires postcss-merge-rules which has caniuse-api at such a low version that browserslist is at version 1 in that package, and is causing my build to fail. I am trying to use browserslist new extends config `extends browserslist-config-mycompany`. Only workaround I can use for now is switching to csso :(

**Comment by awkaiser** [comment]
Echoing @Zashy, I arrived at this issue after trying Browerslist `extends` in **package.json**:
```
"browserslist": [
  "extends browserslist-config-google/modern"
],
```
... with [**optimize-css-assets-webpack-plugin**](https://github.com/NMFR/optimize-css-assets-webpack-plugin) and **cssnano** (`browserslist@1.7.7`).

> `extends` support was added in [Browserslist 2.5](https://github.com/ai/browserslist/blob/master/CHANGELOG.md#25)

**Comment by decksterr** [comment]
Arrived after ejecting from [create-react-app](https://github.com/facebook/create-react-app) and trying ```alt-*``` and ```>=``` in browserslist of **package.json**

Turns out webpack's [css-loader](https://www.npmjs.com/package/css-loader) depends on this package, actually pretty annoying not to be able to use the ```minimize``` option with browserslists v2+ configs in package.json, please someone fix this ?

**Comment by evilebottnawi** [comment]
@maksugr a lot of deps already updated right now

**Comment by maksugr** [comment]
@evilebottnawi I see this in the master branch
```
❯◯ all-contributors-cli          latest  4.8.1   ❯  4.11.2  https://github.com/jfmengels
/all-contributors-cli#readme
 ◯ babel-plugin-module-resolver  latest  2.7.1   ❯  3.1.1   https://github.com/tleunen/b
abel-plugin-module-resolver#readme
 ◯ camelcase                     latest  4.1.0   ❯  5.0.0   https://github.com/sindresor
hus/camelcase#readme
 ◯ coveralls                     latest  2.13.3  ❯  3.0.1   https://github.com/nickmerwi
n/node-coveralls#readme
 ◯ eslint                        latest  3.19.0  ❯  4.19.1  https://eslint.org
 ◯ eslint-plugin-babel           latest  3.3.0   ❯  5.1.0   https://github.com/babel/esl
int-plugin-babel#readme
 ◯ gh-pages                      latest  0.11.0  ❯  1.2.0   https://github.com/tschaub/g
h-pages
 ◯ nyc                           latest  11.9.0  ❯  12.0.2  https://github.com/istanbulj
s/nyc#readme
 ◯ remark                        latest  7.0.1   ❯  9.0.0   http://remark.js.org
 ◯ remark-cli                    latest  3.0.1   ❯  5.0.0   http://remark.js.org
 ◯ remark-html                   latest  6.0.1   ❯  7.0.0   https://github.com/wooorm/re
mark-html#readme
 ◯ remark-toc                    latest  4.0.1   ❯  5.0.0   https://github.com/remarkjs/
remark-toc#readme
 ◯ tomlify-j0.4                  latest  2.2.1   ❯  3.0.0   https://github.com/jakwings/
tomlify-j0.4
 ◯ unist-util-remove             latest  0.2.1   ❯  1.0.1   https://github.com/syntax-tr
ee/unist-util-remove#readme
```

**Comment by evilebottnawi** [comment]
@maksugr it is dev deps, also they require node@6 minimum

**Comment by maksugr** [comment]
@evilebottmawi and don’t you want to update them?

**Comment by evilebottnawi** [comment]
@maksugr already do it:
1. https://github.com/ben-eb/cssnano/pull/499
2. Drop `node@4`
3. Update **all** deps
