### ISSUE TITLE
Pass another file as an argument for plugin

### ISSUE THREAD

**Issue by egorvoronov** [cssnano/cssnano#457]
Hey there, thanks for amazing job.

I have a two css files, one parent.css and chunk.css, and chunk.css file has some rules that are already inside parent.css that I would like to remove from chunk.css. I started thinking that applying postcss-discard-duplicates would help here but it works only for 1 file.

So, is there any way i could pass parent css file as an argument for plugin? That way i could compare parent and chunk and remove duplicate rules from chunk (I already implemented that type of logic but it would be great if I could do this in a proper plugin way to be able to use it during the webpack build step).

Thanks

**Comment by andyjansson** [comment]
I believe this would be something better handled by a bundler, such as webpack.
