### ISSUE TITLE
mergeRules is unsafe in some cases

### ISSUE THREAD

**Issue by vxsx** [cssnano/cssnano#458]
Consider following file:

```
.x {
	all: initial;
	font-size: 20px;
}
.y {
	all: initial;
	font-size: 10px;
}
```

after cssnano processes things it becomes:
```
.x{font-size:20px}.x,.y{all:initial}.y{font-size:16px}
```

After transformation `x` doesn't apply `font-size: 20px` anymore because `all: initial` of the next declaration overrides it.

**Comment by andyjansson** [comment]
Reopening this since #479 didn't correctly solve the issue.

**Comment by evilebottnawi** [comment]
@andyjansson looks issue already solved? Playground:
```css
.x,.y{all:initial}.x{font-size:20px}.y{font-size:10px}
```

**Comment by andyjansson** [comment]
It's solved incorrectly, which is why I reopened the issue. I have a branch with a rewrite which still needs some tweaks for optimal output, but which fixes the issue entirely.

**Comment by fracmak** [comment]
Another scenario that's unsafe. When using the postcss [focus-visible](https://github.com/jonathantneal/postcss-focus-visible) plugin,
```
a:focus-visible {
  outline: none;
}
```
**becomes**
```
a.focus-visible {
  outline: none;
}
a:focus-visible {
  outline: none;
}
```

mergeRules combines those roles back together into this
```
a.focus-visible, a:focus-visible {
  outline: none;
}
```
The browser ends up dropping the whole style because of the unknown :focus-visible, so even the .focus-visible doesn't work

**Comment by evilebottnawi** [comment]
@fracmak it is bug in polyfill not in `cssnano`, we use standard logic for `css`, polyfill should looks on all selectors

**Comment by fracmak** [comment]
I've tested this without the polyfill and without the postcss plugin. The browser does drop the styles of unknown pseudo-selectors

**Comment by evilebottnawi** [comment]
@fracmak works fine https://codepen.io/evilebottnawi/pen/EdEJpO

**Comment by fracmak** [comment]
Here's my example:

https://codepen.io/anon/pen/ZqxNEq

This is what I see in chrome

![image](https://user-images.githubusercontent.com/378178/47170937-6e962200-d2d5-11e8-9664-35889a16eb5f.png)

**Comment by andyjansson** [comment]
@fracmak That's fair. We should see to it that `mergeRules` takes into account browser support when merging rules. 

Could you create a separate issue for this?

**Comment by evilebottnawi** [comment]
@andyjansson @fracmak with `.green` in `.green, .green:focus-visible` it is still doesn't work

**Comment by fracmak** [comment]
I'm not certain this is browser specific. I've tried it in Safari 12, Firefox 60, Chrome 69, Edge 16 with the same behavior.

**Comment by evilebottnawi** [comment]
@andyjansson hm looks it is happens only when you use invalid class, it is will be hard to fix

**Comment by fracmak** [comment]
You could just not merge pseudo selectors

**Comment by evilebottnawi** [comment]
@fracmak bad idea, need investigate how we can solve this, please create new issue

**Comment by fracmak** [comment]
New issue created #642

**Comment by andyjansson** [comment]
>I'm not certain this is browser specific.

It's  a property which is still in WD. No browser has this, except for Chrome behind an experimental flag. 

>@andyjansson hm looks it is happens only when you use invalid class, it is will be hard to fix

Nah, this is how browsers handle CSS. Whenever a browser encounters something it does not understand, it'll ignore it fully. Like fracmak said, we shouldn't merge stuff which our supported browser range does not understand.

**Comment by evilebottnawi** [comment]
Original issue was solved.
