### ISSUE TITLE
New maintainer requested.

### ISSUE THREAD

**Issue by chriseppstein** [cssnano/cssnano#476]
Hi folks,

I thought I would have time to maintain this project for Ben but I need to be realistic and admit that I don't have the cycles. I have given npm publish permissions to @ai (except for the `postcss-svgo` and `postcss-zindex` packages that I didn't have permissions on, @ben-eb will need to handle those).

Hopefully, a new primary maintainer can be found and development can proceed apace.

Chris

**Comment by ai** [comment]
A few benefits of maintaining cssnano:

* It is default CSS minifier in webpack.
* It has a unique modular design.
* There are many ways to improve it. Especially with a modular design. For example, you can provide presets (like if you are using BEM, take this not 100% safe, but safe for BEM optimizations).
* It has 2M downloads every month
* 2M downloads and webpack make you a welcome speaker to any CSS conference

**Comment by evilebottnawi** [comment]
@ai :+1: Awesome!

Need solve problem with `postcss-svgo` and `postcss-zindex`. Also maybe we can move repo in `cssnano` org to avoid this problem in future.

**Comment by evilebottnawi** [comment]
@ai `cssnano@4-rc*` already monorepo (look in repo) :smile: . It is just idea. Priority to release stable `cssnano@4`

**Comment by evilebottnawi** [comment]
@ai friendly ping, request on permissions, thanks :+1:

**Comment by ai** [comment]
@evilebottnawi I don’t have npm permissions fo `postcss-svgo` and `postcss-zindex`.

Do we need them for cssnano@4? I thought Ben Briggs moved them to monorepo.

If we need it, we can ask @TrySound to give us permission (or to accept our PR, if they are not part of cssnano).

**Comment by evilebottnawi** [comment]
@ai Yes we need permissions for `postcss-svgo` and `postcss-zindex`. They are part of cssnano https://github.com/ben-eb/cssnano/tree/master/packages/postcss-svgo and https://github.com/ben-eb/cssnano/tree/master/packages/postcss-zindex

**Comment by TrySound** [comment]
@evilebottnawi npm access granted.

**Comment by evilebottnawi** [comment]
@TrySound Thanks!

**Comment by TrySound** [comment]
@evilebottnawi Which ones?

**Comment by evilebottnawi** [comment]
@TrySound i can't close issue and merge PR, also can release `cssnano` in npm

**Comment by TrySound** [comment]
@ben-eb can you share github access with evilebottnawi? I already did it in npm.

**Comment by evilebottnawi** [comment]
@TrySound @ben-eb is unavailable (he left open source), @ai and @chriseppstein have github permissions

**Comment by ai** [comment]
@evilebottnawi I don’t have access too. I asked Ben Briggs by email.

**Comment by evilebottnawi** [comment]
@ai ping me when we resolve this problem, in my plans release `4` stable version in the middle of the month

**Comment by evilebottnawi** [comment]
@ai looks like we lose time, any ideas how we solve this if @ben-eb not answer

**Comment by andyjansson** [comment]
@evilebottnawi he was on gitter a few days ago. I believe he assigned @chriseppstein with the appropriate access rights.

**Comment by ai** [comment]
@evilebottnawi Been Briggs answered me in Gitter

**Comment by evilebottnawi** [comment]
@ai what is answer? :smile:

**Comment by ai** [comment]
He said that he will lock at weekend. I ping him again.

**Comment by evilebottnawi** [comment]
@chriseppstein @ai @ben-eb @TrySound thanks all for helping, problem solved, now i am contributor of `cssnano` :+1: 

Due to the fact that I am alone, i will create PR and wait 72 hours before merging if no one will review/ask question/etc and will merge PR. If somebody want participate in review just says me here and i always will be request review from you. Thanks!

**Comment by ai** [comment]
@evilebottnawi is everything going well to 4.0 release? I can send you developers from Cult of Martians.

**Comment by ai** [comment]
@evilebottnawi to send a people from Cult I need a exact issues or exact steps to do

**Comment by evilebottnawi** [comment]
@ai List:
1. Update deps (https://github.com/ben-eb/cssnano/issues/447) to latest version where it is possible, some package can change public api and it is require fix usage in code.
2. https://github.com/ben-eb/cssnano/issues/448 - don't remove first `declaration` (aka fallback) is we using `var(--foo)`.

I will analyze issues right now in `cssnano` and added new issue to this list. I will ping you when i done this work :+1:

**Comment by ai** [comment]
@evilebottnawi perfect tasks for new developers. Will try to create Cult tasks today.

**Comment by evilebottnawi** [comment]
@ai i will update issues list :+1:

**Comment by EECOLOR** [comment]
Guys it's great to see things are moving again. Thank you all for putting time and effort into this. It's often overlooked how hard it is to keep a project going without the original creator.

Thanks again!
