### ISSUE TITLE
postcss-normalize-unicode causes bugs in IE11 and early versions of Edge browser

### ISSUE THREAD

**Issue by vitaliymaz** [cssnano/cssnano#524]
**postcss-normalize-unicode** plugin forces transformation to  lowercase 'u'.
For example: ` unicode-range: U+30-39; ` would be ` unicode-range: u+30-39; `

That is a known issue for IE11 and early versions of Edge browser. See "Known Issues" tab here https://caniuse.com/#search=unicode-range

My proposal is stop forcing lovercase or even better force uppercase to make the plugin working well with all browser. Ready to create PR after making decision.

**Comment by evilebottnawi** [comment]
@vitaliymaz thanks for issue

**Comment by vitaliymaz** [comment]
@evilebottnawi You're welcome. Can I make a PR to fix that?

**Comment by evilebottnawi** [comment]
@vitaliymaz Yep :+1: Feel free to send a PR
