### ISSUE TITLE
postcss-minify-params can creat query selector which is invalid in IE11

### ISSUE THREAD

**Issue by patric-eberle** [cssnano/cssnano#528]
This is probably an edge case but when `postcss-minify-params` is `true` the following CSS

```
@media all {
  color: red;
}
```

creates the following output

```
@media {
  color: red;
}
```

because it just deletes the 'all' query, which leads to an empty one.

**Comment by evilebottnawi** [comment]
Already fixed in `cssnano@next`, thanks for PR
