### ISSUE TITLE
BrowserslistError: Unknown version 67 of android

### ISSUE THREAD

**Issue by wroughtec** [cssnano/cssnano#537]
Going from `4.0.0-rc.2` to `4.0.0` I get the following error:

```
ERROR in ./app.scss (./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./node_modules/import-glob-loader!./src/client/app.scss)
Module build failed (from ./node_modules/postcss-loader/lib/index.js):
BrowserslistError: Unknown version 67 of android
    at Function.select (./node_modules/caniuse-api/node_modules/browserslist/index.js:622:17)
    at ./node_modules/caniuse-api/node_modules/browserslist/index.js:151:33
    at Array.reduce (<anonymous>)
    at resolve (./node_modules/caniuse-api/node_modules/browserslist/index.js:132:18)
    at browserslist (./node_modules/caniuse-api/node_modules/browserslist/index.js:224:16)
    at isSupported (./node_modules/caniuse-api/dist/index.js:62:37)
    at ./node_modules/cssnano-preset-default/node_modules/postcss-reduce-initial/dist/index.js:39:60
    at initializePlugin (./node_modules/cssnano/dist/index.js:35:51)
    at <anonymous>
 @ ./app.scss 2:14-215 21:1-42:3 22:19-220
 @ multi webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000 react-hot-loader/patch ./index.jsx ./app.scss
```
When compiling with webpack. My browerslist config is as follows:
```
{
  "browserslist": [
    "last 2 version",
    "> 1%"
  ]
}
```

**Comment by evilebottnawi** [comment]
@wroughtec try to update you dependencies and lock file

**Comment by wroughtec** [comment]
ok combinging in the lock file seems to have resolved:
```
caniuse-db@^1.0.30000864, caniuse-db@^1.0.30000529, caniuse-db@^1.0.30000634, caniuse-db@^1.0.30000639:
  version "1.0.30000864"
  resolved "https://registry.yarnpkg.com/caniuse-db/-/caniuse-db-1.0.30000864.tgz#35a4b2325a8d4553a46b516dbc233bf391d75555"

caniuse-lite@^1.0.0, caniuse-lite@^1.0.30000792, caniuse-lite@^1.0.30000815, caniuse-lite@^1.0.30000817, caniuse-lite@^1.0.30000819, caniuse-lite@^1.0.30000805, caniuse-lite@^1.0.30000844, caniuse-lite@^1.0.30000851, caniuse-lite@^1.0.30000859, caniuse-lite@^1.0.30000864:
  version "1.0.30000864"
  resolved "https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30000864.tgz#7a08c78da670f23c06f11aa918831b8f2dd60ddc"
```

**Comment by evilebottnawi** [comment]
@wroughtec problem still exists?

**Comment by ai** [comment]
Seems like Browserslist used in wrong way `browserslist(browserslist))`.

I will look on weekend.

**Comment by ai** [comment]
The problem is here: https://github.com/cssnano/cssnano/blob/8d8a8e7875c2619cb02463985ea8e8d0979a3cfd/packages/postcss-reduce-initial/src/index.js#L18

First, you use Browserslist A to generate browsers. Then you pass these browsers for `caniuse-api` with Browserslist B. Browserslist A and Browserslist B could have different versions and use different `caniuse-lite` DBs.

I am thinking about the solution.

**Comment by ai** [comment]
I think, the best way will be:

```diff
- const initialSupport = isSupported('css-initial-value', browsers);
+ const initialSupport = isSupported('css-initial-value');
```

But `env` and `stats` options will not work. In other hand, people should use env variables `BROWSERSLIST_STATS=path npx gulp css`, since anyway most of toools doesn’t support this options.

**Comment by evilebottnawi** [comment]
@ai can you send fix?

**Comment by ai** [comment]
@evilebottnawi sure https://github.com/cssnano/cssnano/pull/538

**Comment by wroughtec** [comment]
@evilebottnawi yes I managed to resolve if I pointed to the latest versions of canIuse db and lite. But a bit of a manual process, hopefully #538 resolves without the need to do this

**Comment by sailei1** [comment]
the same problem, how to  fix?

**Comment by ai** [comment]
@sailei1 update to `css-loader` 1.0.

**Comment by ylemkimon** [comment]
@sailei1 Try to dedupe the `caniuse-lite` version using `npm dedupe` or manually editing `package-lock.json` or `yarn.lock`.

**Comment by ylemkimon** [comment]
@ai Correct me if I'm wrong, but does `cssnano` use `caniuse-lite`?

**Comment by ai** [comment]
@ylemkimon some of `cssnano` plugins use `browserslist` and this `browserslist` uses `caniuse-lite`

**Comment by ylemkimon** [comment]
@ai Ah, then I think `caniuse-lite` should be peer dependency of them.

**Comment by ai** [comment]
@ylemkimon, unfortunately, it will not fix the conflict. Look how people uses Browseslist:

1. `css-loader` → `cssnano` → `browserslist` → `caniuse-lite`
2. `autoprefixer` → `caiuse-lite`

So there are many deep branches in npm dependencies tree to `caniuse-lite`. It is just impossible to add `peerDependency` to every tool inside branches. Just send them a PR with `ignoreUnknownVersions` option (Browserslist already support it, they just need to send it to Browserslist)

**Comment by selfagency** [comment]
i'm having this same issue, using cssnano@4.0.0-rc.2 and 4.0.0. where should a PR be submitted? i don't see broswerslist in the package.json for caniuse-lite. so who should be getting passed an option where?

**Comment by ai** [comment]
@selfagency use `npm ls` to check your dependencies. Try to find any dependency branch with Browserslist < 3.0.

**Comment by ai** [comment]
Oops, this is a different issue 😅

Nope, this issue was not solved. My PR is still open.

**Comment by evilebottnawi** [comment]
Sorry, don't have fix it right now, a lot of regular work, feel free to send a PR

**Comment by ai** [comment]
@evilebottnawi PR is not a problem (I sent it already). Main problem is to make the right way :(.

We need changes from `caniuse-api` (adding `ignoreUnknownVersions` and update Browserslist). But maintainer didn’t respond.

**Comment by evilebottnawi** [comment]
@ai who is unavailable?

**Comment by ai** [comment]
@Nyalab the maintainer of [`caniuse-api`](https://github.com/Nyalab/caniuse-api)

**Comment by selfagency** [comment]
@ai i just hit him up on twitter

**Comment by Nyalab** [comment]
i just release `caniuse-api@3.3.0`, let me know if this works for you now

@selfagency i did not receive anything, i think you hit the wrong guy 😄 

sorry for the delay guys, i just had my second baby, time passes very quickly these days, anyway, i'm back for good now, tell me if i can do more to help you

**Comment by selfagency** [comment]
@Nyalab not you?
![screenshot 2018-07-10 11 36 04](https://user-images.githubusercontent.com/2541728/42520893-72696b60-8435-11e8-8d90-4a145b8f13e4.png)

**Comment by Nyalab** [comment]
omg that is me indeed! but as you can see my last mention is from the 2nd of july, is twitter broken or what?
<img width="956" alt="screen shot 2018-07-10 at 17 37 55" src="https://user-images.githubusercontent.com/721993/42521025-14971ce8-8468-11e8-9c68-5083b8dd6e06.png">

**Comment by selfagency** [comment]
do you happen to have the quality filter on?

**Comment by Nyalab** [comment]
yes, i had it on, wtf is that setting, you actually may be the type of mention i want to show, not to hide!

**Comment by selfagency** [comment]
it hides people from your mentions that have received past temporary suspensions

**Comment by selfagency** [comment]
anywho this solved the problem with cssnano, but @ai, now there's a problem with postcss-merge-rules which uses caniuse-api@2.0.0 and pixrem@4.0.1 which uses browserslist@2.11.3.

**Comment by ai** [comment]
@selfagency thanks for PR 👍

**Comment by evilebottnawi** [comment]
@ai updating `caniuse-api` to latest version should solve problem?

**Comment by ai** [comment]
1. Update `caniuse-api`
2. Call it with `ignoreUnkownVersions: true`

**Comment by ai** [comment]
@selfagency `postcss-merge-rules` is in cssnano repo https://github.com/cssnano/cssnano/blob/e12db214a481ba286eff0b3365f9cdbc1c804a5f/packages/postcss-merge-rules/README.md

**Comment by selfagency** [comment]
@ai oh i submitted my pr [here](https://github.com/ben-eb/postcss-merge-rules/pull/60) which i thought was the source

**Comment by webcarrot** [comment]
For yarn users - add this to "main" package.json (yolo mode but work well):
```json
  "resolutions": {
    "browserslist": "4.0.0"
  }
```

**Comment by evilebottnawi** [comment]
Somebody can test with `cssnano@4.0.1` version and confirm what bug was fixed?

**Comment by mo** [comment]
I upgraded a mid-size webapp to css-loader 1.0 with cssnano 4.0.1 now and everything went smoothly (43 E2E tests passing and CSS minifications works as expected when I deploy to my staging server). I ran into the "version 67 of android" on my previous attempt to upgrade this project so from what I can see this bug fix is working properly.

**Comment by JaZo** [comment]
I can also confirm that updating to `cssnano@4.0.1` solves this issue. Thanks for the fix!

**Comment by evilebottnawi** [comment]
Looks fixed. Feel free to feedback, thanks!
