### ISSUE TITLE
Warnings after upgrading to 4.0.0

### ISSUE THREAD

**Issue by virzak** [cssnano/cssnano#541]
Getting these warnings. Not sure why:

```
 WARNING  Compiled with 4 warnings                                                           20:01:42
 warning  in ./node_modules/is-resolvable/index.js

11:2-9 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

 warning  in ./node_modules/cssnano/dist/index.js

75:31-42 Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/cssnano/dist/index.js

80:31-45 Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/cosmiconfig/dist/loaders.js

8:17-34 Critical dependency: the request of a dependency is an expression

```

**Comment by evilebottnawi** [comment]
@virzak reinstall you dependecies and update lock file, `rm -r package-lock.json && rm -r node_modules && npm cache clear --force && npm i`. Feel free to feedback.

**Comment by virzak** [comment]
The issue us still there. I ran 

```bash
$ rm -rf node_modules/ yarn.lock
$ yarn cache clean
$ yarn
```

**Comment by evilebottnawi** [comment]
@virzak can you create minimum reproducible test repo?

**Comment by evilebottnawi** [comment]
Please try to install `cssnano@4.0.1`

**Comment by virzak** [comment]
cssnano@4.0.1 has the same issue. A bit short on time to create a minimum repo. Will try on the weekend.

**Comment by andyjansson** [comment]
Is this a webpack issue? How are you using it?

**Comment by evilebottnawi** [comment]
Looks on `critical` plugin, but i can't know why use this plugin on `node_modules`

**Comment by virzak** [comment]
Using it similarly to this:

```js
const cssnano = require('cssnano');
const minifier = postcss([cssnano]);
...
    if (process.env.NODE_ENV === 'production') {
      const result1 = await prefixer.process(css, {from: undefined});
      css = result1.css;
      const result2 = await minifier.process(css, {from: undefined});
      css = result2.css;
    }
```

From: https://github.com/mui-org/material-ui/blob/master/pages/_document.js

**Comment by virzak** [comment]
Here is the minimal demo:

https://github.com/virzak/cssnano-issue-541

It is based on this example:
https://github.com/zeit/next.js/tree/canary/examples/with-typescript

Warnings disappear when you roll back to version 3.10.0

A few additional issues:
I am forced to add these lines to next.config.js:

https://github.com/virzak/cssnano-issue-541/blob/81903dab459db3b96c58ab5a15165c81de743a13/next.config.js#L8
since cssnano depends on fs even on client side.

Also are there any plans for typescript support?

**Comment by andyjansson** [comment]
Did you manage to solve this issue @virzak  ?

**Comment by virzak** [comment]
@andyjansson Seems to work fine now!
