### ISSUE TITLE
Changelog mentions customizing caniuse browser selection; not documented anywhere

### ISSUE THREAD

**Issue by nikwen** [cssnano/cssnano#566]
According to the CHANGELOG, the following holds true:

> cssnano now makes much better use of Browserslist. `postcss-colormin` &
  `postcss-reduce-initial` were enhanced with different behaviour depending
  on which browsers are passed.

However, I could not find any documentation on how to customize "which browsers are passed".

Could this please be documented and in the meantime be explained briefly in this issue?

**Comment by evilebottnawi** [comment]
@nikwen it is internal change, you should just put `.browserslist` in your project and all

**Comment by nikwen** [comment]
@evilebottnawi Thank you for your reply! I think that this should be documented somewhere. :+1: 

As for my use-case, I will consider that option. I have a monorepo with multiple directories being built separately but using the same build process and thus I have avoided copying `.browserlistrc` files into each directory that I build (autoprefixer has a `browsers` option that I pass my browserlist config to). I'll see if I can get around that and use only one config file.

**Comment by nikwen** [comment]
I got around this personally by just placing `.browserlistrc` and `.postcssrc.js` files in the root directory of my project. The documentation part remains.

**Comment by evilebottnawi** [comment]
Don't think we should documented this, anyway feel free to send a PR if you think otherwise
