### ISSUE TITLE
Wrong output when using css variables with border

### ISSUE THREAD

**Issue by lukapopijac** [cssnano/cssnano#572]
input:
```
.a {
  border: 6px solid red;
  border-top: 6px solid var(--mycolor);
}
```

output (clearly wrong):
```
.a{border-style:solid;border-top:6px solid red;border-top:6px solid var(--mycolor);border-width:6px}
```

**Comment by andyjansson** [comment]
Looking into this.

**Comment by lukapopijac** [comment]
This is still not fixed in 4.0.5

**Comment by andyjansson** [comment]
One of the subpackages hasn't been published properly, that's the issue. Give us a moment.

**Comment by evilebottnawi** [comment]
@andyjansson what package?

**Comment by evilebottnawi** [comment]
I can release new version only tomorrow

**Comment by andyjansson** [comment]
@evilebottnawi it's already been published with the help of @ai. 

@lukapopijac If you update your `postcss-merge-longhand` dependency to `4.0.4`, you'll see that it's working now. You can also test it here: https://cssnano.co/playground/

**Comment by lukapopijac** [comment]
It works now. Thanks!
