### ISSUE TITLE
Can't disable minification

### ISSUE THREAD

**Issue by selipasha** [cssnano/cssnano#576]
How can I disable minification? I don't need that and have no Idea how to turn it off

**Comment by evilebottnawi** [comment]
@selipasha what you mean? Just don't use plugin

**Comment by selipasha** [comment]
I mean I like the other feature of this plugin except minification

**Comment by evilebottnawi** [comment]
@selipasha what features?

**Comment by andyjansson** [comment]
@selipasha You can disable optimisations by passing options to the preset, as documented here: 
https://cssnano.co/guides/presets#excluding-transforms

The optimisations enabled in each preset are listed here: 
https://cssnano.co/guides/optimisations

For what reason do you wish to disable the optimisations, if you don't mind me asking? Did you run into a bug?

**Comment by selipasha** [comment]
I can't see any option that disable minification. I have already an extesnion in Visual Studio Code that already minify css files, and I don't need another one. I just need disable cssnano minification in my gulpfile! I see that you barely understand me. I'm sorry my English isn't the best

**Comment by andyjansson** [comment]
https://cssnano.co/optimisations/normalizewhitespace

**Comment by selipasha** [comment]
I don't understand how to disable this, it's very hard and unclear. Here's a part of my code from my gulpfile, what should I type to disable "normalizeWhitespace" ?

```
gulp.task('postcss', function () {
	return gulp.src('assets/css/*.css')
		.pipe(postcss([autoprefixer(['last 5 versions']), cssnano(['normalizeWhitespace: false'])]))
		.pipe(gulp.dest('assets/css/'))
})
```

**Comment by Janne252** [comment]
@selipasha I ran into the same issue. Based on the documentation you have to pass in a preset object in order to be able to override rules:
```js
require('cssnano')({
    preset: ['default', {
        normalizeWhitespace: false
    }]
})
```
This worked for me; Whitespace is no longer being normalized.
