### ISSUE TITLE
Docs: optimizations configuration keys not clear.

### ISSUE THREAD

**Issue by amatiasq** [cssnano/cssnano#581]
I've been reading [the optimizations documentation](https://cssnano.co/guides/optimisations) (which is just a table with [examples](https://cssnano.co/optimisations/discardduplicates)).

My intention was to disable `postcss-discard-duplicates`. I passed `{ "postcss-discard-duplicates": false }` and `{ postcssDiscardDuplicates: false }`. I knew I had to pass `false` to disable it but I couldn't find the key.

After hours diving in [`OptimizeCssAssetsWebpackPlugin`](https://github.com/NMFR/optimize-css-assets-webpack-plugin) (the tool I'm using), then inside `cssnano` and finally inside `cssnano-preset-default` I found [this line](https://github.com/cssnano/cssnano/blob/master/packages/cssnano-preset-default/src/index.js#L81) which gave me the answer I was looking for.

I think a information as basic as this one (the key used in the configuration object for each plugin) should be part of the optimizations page and it should be clear.

I've already lost so much time looking for this I can't open a PR so I leave this issue.

**Comment by andyjansson** [comment]
it's `discardDuplicates`.

**Comment by amatiasq** [comment]
@andyjansson I see, that's what I mean with it being clear. That's kind of buried down inside the Guides section. I think that having the keys nearer to the optimizations documentation (where plugins are listed) will give it at first glance instead of reading the text in the guide to look for it.

**Comment by andyjansson** [comment]
I agree that the documentation could be clearer. I *am* planning on redoing things on the website to improve readability and comprehension, but there's simply other things that take priority.

**Comment by andyjansson** [comment]
The optimisations are now listed by their key. Closing.
