### ISSUE TITLE
padding fallback was discarded

### ISSUE THREAD

**Issue by minocoko** [cssnano/cssnano#597]
it can reproduce form https://cssnano.co/playground/

input css:
body {
  padding: 20px 10px;
  padding: 2rem 1rem;
  
  font-size: 16px;
  font-size: 1.6rem;
}

output css:
body{font-size:16px;font-size:1.6rem;padding:2rem 1rem}

font-size works well, but padding fallback to px was discarded.

please look into this issue
thanks a lot

**Comment by andyjansson** [comment]
I don't see how this is an issue. What browser do you have which doesn't support `rem`?

**Comment by minocoko** [comment]
I use chrome, the latest versiocorrect output should be
body{font-size:16px;font-size:1.6rem;padding: 20px 10px;padding:2rem 1rem}

`padding: 20px 10px;`  was discarded

**Comment by andyjansson** [comment]
Yes, because `padding:2rem 1rem` takes precedence over `padding: 20px 10px`. This is by design. 

I ask again, why do you want a `px` fallback if it makes no difference to the browsers? What browser do you target which doesn't support `rem`?

**Comment by minocoko** [comment]
ie9

I don't know why `font-size:16px;` exists in output.
maybe I should target to ie11 to avoid this issue, and don't fallback to px anymore.
