### ISSUE TITLE
Issue with overriding preset

### ISSUE THREAD

**Issue by smashercosmo** [cssnano/cssnano#600]
Having the following postcss config:
```
module.exports = {
  plugins: {
    cssnano: {
      preset: [
        'default',
        {
          normalizeUrl: true,
        },
      ],
    },
  },
}
```
I noticed, that any normalizeUrl value, no matter 'true' or 'false', switches this rule off. Removing overrides object completely makes this rule enabled. I tested 'convertValues' rule and it behaves the same way. Probably relevant for all other rules. I assume, that I'm doing something wrong, but can't figure out what exactly.

P.S. I'm using cssnano@4.1.0

**Comment by andyjansson** [comment]
Also see: https://github.com/cssnano/cssnano/issues/410#issuecomment-416648484

**Comment by smashercosmo** [comment]
@andyjansson do you want me to try 'exclude' option?

**Comment by andyjansson** [comment]
Go ahead and try it.
