### ISSUE TITLE
css modules Can't resolve url

### ISSUE THREAD

**Issue by ZurrTum** [cssnano/cssnano#616]
>ERROR in ./src/style.css (./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/src??ref--5-2!./src/style.css)
Module not found: Error: Can't resolve 'share.png' in 'C:\Users\ZurrT\Desktop\postcss-cssnano-issue\src'
 @ ./src/style.css (./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/src??ref--5-2!./src/style.css) 7:83-103
 @ ./src/style.css
 @ ./src/index.js
error Command failed with exit code 2.

I have prepared a repo.
`git clone https://github.com/ZurrTum/postcss-cssnano-issue.git`
`cd postcss-cssnano-issue`
run `npm install && npm run build`

- File **webpack.config.js**
```javascript
module.exports = {
  module: {
    rules: [
      {
        test: /\.png$/,
        use: 'file-loader',
      },
      {
        test: /\.css$/,
        use: [
          'style-loader',
          {loader: 'css-loader', options: {modules: true, importLoaders: 1}},
          {
            loader: 'postcss-loader',
            options: {
              plugins: [
                require('cssnano')(), //If this line is removed, there will be no errors.
              ],
            },
          }
        ],
      },
    ],
  },
}
```
- File **index.js**
```javascript
import './style.css';
```
- File **style.css**
```css
.share {
  background-image: url(./share.png);
}
```

- Directory
├── package.json     
├── src              
│   ├── index.js     
│   ├── share.png    
│   └── style.css    
└── webpack.config.js

Can anyone help me?
I don't know what caused this error.

**Comment by evilebottnawi** [comment]
@ZurrTum How it is related to `cssnano`? Try to remove `cssnano` and run again

**Comment by ZurrTum** [comment]
@evilebottnawi I certainly confirmed that it can run normally without cssnano.

**Comment by andyjansson** [comment]
I believe this is more of a css-loader issue than a cssnano issue.

**Comment by ZurrTum** [comment]
@andyjansson You are right.
in the css-loader/lib/**processCss.js**  -155
```javascript
rewriteUrl: function(global, url) {  // url = share.png
  if(parserOptions.url){
    url = url.trim();

    if(!url.replace(/\s/g, '').length || !loaderUtils.isUrlRequest(url)) {
      return url;
    }
    if(global) {  /* options.modules unset */
      return loaderUtils.urlToRequest(url);  /* ./share.png */
    }
  }  /* options.modules == true */
  return url;  /* share.png */
}
```

cssnano  `=>`  **share.png**
if unset options.modules  `=>`  has global  `=>`  **./share.png**  `=>`  PASS
has options.modules  `=>`  has local  `=>`  **share.png**  `=>`  ERROR

I do not know why.
The cssnano input to the css-loader is the same string, but the css-loader uses a different parsing method.
Who can give a solution? I don't want to abandon css-modules.

**Comment by ZurrTum** [comment]
hey!

**Comment by ZurrTum** [comment]
I solved it,By using cssnano indirectly.
optimize-css-assets-webpack-plugin

**Comment by ZurrTum** [comment]
```javascript
optimization: {
  minimizer: [
    new UglifyJsPlugin({
      cache: true,
      parallel: true,
      sourceMap: true,
    }),
    new OptimizeCSSAssetsPlugin({}),
  ],
}
```
It works for me

**Comment by infctr** [comment]
Thnx for bringing that up!

I've changed the default config to `cssnano({ preset: ['default', { normalizeUrl: false }] })` to make that work

**Comment by thompk2** [comment]
@infctr That works for me!

Css Modules assumes that anything imported _without_ a leading `./` is imported from node modules. See here: https://github.com/css-modules/css-modules#css-modules

> All URLs (url(...)) and @imports are in module request format (./xxx and ../xxx means relative, xxx and xxx/yyy means in modules folder, i. e. in node_modules).

So when cssnano normalizes URLs **before** being sent to the css-loader, they'll be interpreted as relative to node_modules. I assume the `optimize-css-assets-webpack-plugin` works because it runs cssnano **after** the css-loader. Not sure which is the better solution. Ideally https://github.com/cssnano/cssnano/tree/master/packages/postcss-normalize-url could have an option to not normalize relative URLs.
