### ISSUE TITLE
Speed improvement in postcss-merge-rules (124s to 16s)

### ISSUE THREAD

**Issue by mareolan** [cssnano/cssnano#631]
We use cssnano and autoprefixer in webpack for building ~20 color schemes, each resulting in a standalone CSS file of ~300kB. The build takes really long - 124s on i5-6600 @ 3.3Ghz. CSS selectors heavily use pseudo-classes, such as :not(), etc.

Profiling shows that 112s (90%) of the time is spent on using `caniuse.isSupported()` API in **`postcss-merge-rules/dist/lib/ensureCompatibility.js`**. Replacing the `isSupported` call with cached variant dropped it to 4s so total build time dropped from 124s to 16s.

The cached variant replaced all `isSupported` calls by `isSupportedCached` in `ensureCompatibility.js`:
```js
let cache = new Map();
function isSupportedCached(feature, browsers) {
    let browsersSubCache = cache.get(feature);
    if (browsersSubCache === undefined) {
        browsersSubCache = new Map();
        cache.set(feature, browsersSubCache);
    }
    let result = browsersSubCache.get(browsers);
    if (result === undefined) {
        result = isSupported(feature, browsers);
        browsersSubCache.set(browsers, result);
    }
    return result;
}
```

The above is just an example of caching and might leak memory as it's not clearing the cache. There's `compatibilityCache` variable in the surrounding code which might be intended for this stuff but I didn't check in detail.

Right now I don't have public runnable example but I might prepare one if needed.

Profiles (can be opened in dev tools of Chrome using dev tools Settings => More Tools => Javascript Profiler => Load): [profiles.zip](https://github.com/cssnano/cssnano/files/2466795/profiles.zip)

Uncached:
![image](https://user-images.githubusercontent.com/4648469/46771667-e623ea00-ccf4-11e8-95f5-380a68e73b77.png)

Cached: 
![image](https://user-images.githubusercontent.com/4648469/46771715-2c794900-ccf5-11e8-933b-d2e415ba0924.png)

webpack@4.20.2
postcss-loader@3.0.0
autoprefixer@9.1.5
cssnano@4.1.4 (default preset)

**Comment by evilebottnawi** [comment]
@mareolan great job, can you send a PR?
