### ISSUE TITLE
update post-css-calc

### ISSUE THREAD

**Issue by kelly-tock** [cssnano/cssnano#636]
recently published a fix for an ios issue, but this is pinned to `^6.0.0`. possible to update to 7?

https://github.com/cssnano/cssnano/issues/578#issuecomment-428539932

https://www.npmjs.com/package/postcss-calc

**Comment by kelly-tock** [comment]
this is down the chain in `optimize-css-assets-plugin` I believe.

**Comment by andyjansson** [comment]
Yes, we'll look into updating cssnano tomorrow.

**Comment by bencripps** [comment]
It would be great to get this released!

**Comment by evilebottnawi** [comment]
Today in near future i will release new version

**Comment by evilebottnawi** [comment]
Done in https://github.com/cssnano/cssnano/releases/tag/v4.1.5
