### ISSUE TITLE
TypeError: Cannot read property 'search' of undefined

### ISSUE THREAD

**Issue by PanJiaChen** [cssnano/cssnano#639]
When I upgrade to v4.1.5, the following error occurs.

![image](https://user-images.githubusercontent.com/8121621/47132495-aea9d480-d2d6-11e8-8ebd-9be5cb368080.png)

I guess it can be caused by the following code:

https://github.com/cssnano/cssnano/blob/1ebc3192629adbcb0e513452b4a9c1035730081e/packages/postcss-merge-longhand/src/lib/decl/borders.js#L376-L379

**Comment by andyjansson** [comment]
Can you provide a minimal set of code to reproduce the issue?

**Comment by PanJiaChen** [comment]
@andyjansson [online demo](https://github.com/PanJiaChen/cssnano-test)

**Comment by PanJiaChen** [comment]
Looking forward to the release of a new version ::smile:

**Comment by lulucas** [comment]
> Looking forward to the release of a new version 😄

node_modules/postcss-merge-longhand installed from npm,

"version": "4.0.7"

borders.js line 106 seems to be old, missing fixed code, something wrong ???

const isValueCustomProp = value => !!~value.search(/var\s*\(\s*--/i);

**Comment by lulucas** [comment]
@andyjansson 

postcss-merge-longhand installed from npm,

"version": "4.0.7"

borders.js line 106 seems to be old, missing fixed code, something wrong ???

const isValueCustomProp = value => !!~value.search(/var\s*(\s*--/i);
