### ISSUE TITLE
version bump to include border fix

### ISSUE THREAD

**Issue by dadamssg** [cssnano/cssnano#643]
Can we get a version bump?

The lack of [this](https://github.com/cssnano/cssnano/commit/d181d30c560386f406de3c9322855b32e88848b4) is currently breaking my production build. I'm using [optimize-css-assets-webpack-plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin/blob/master/package.json#L33) which is dependent on `cssnano@^4.1.0`. Going from 4.1.4 to 4.1.5 breaks because of the border bug.

I have no way to fix this until a new version drops :/

**Comment by evilebottnawi** [comment]
@dadamssg WIP, in future please use `lock` file to avoid this problem

**Comment by evilebottnawi** [comment]
Done in https://github.com/cssnano/cssnano/releases/tag/v4.1.7
