### ISSUE TITLE
[src=""] is minified to [src] 

### ISSUE THREAD

**Issue by kurtextrem** [cssnano/cssnano#647]
This is my config:
```
		require('cssnano', {
			preset: [
				'default',
				{
					discardComments: { removeAll: true },
					minifySelectors: false,
				},
			],
		})
```

cssnano version: 4.1.7

It minifies `selector[src='']` to `selector[src]`, which effectively breaks functionality (The first one checks for an empty src, the latter one checks for 'is there a src attribute')

**Comment by evilebottnawi** [comment]
@kurtextrem Looks you have something other what minify, maybe you still use version plugin. Can't reproduce using locally and on playground https://cssnano.co/playground/

**Comment by kurtextrem** [comment]
If I comment out the cssnano require, it doesn't minify the css / minify the selector.

**Comment by evilebottnawi** [comment]
@kurtextrem Can you create minimum reproducible test repo?

**Comment by kurtextrem** [comment]
Before doing that, do you have any idea which plugins touch selectors? minify-selectors doesn't seem to be the one doing this, as I've added a return statement and it doesn't do anything. The selector is still being touched.

**Comment by evilebottnawi** [comment]
@kurtextrem try to disable plugin step by step

**Comment by kurtextrem** [comment]
This is my config now:
```
		require('cssnano', {
			preset: [
				'default',
				{
					rawCache: false,
					calc: false,
					colormin: false,
					convertValues: false,
					discardComments: false,
					discardDuplicates: false,
					discardEmpty: false,
					discardOverridden: false,
					mergeLonghand: false,
					mergeRules: false,
					minifyFontValues: false,
					minifyGradients: false,
					minifyParams: false,
					minifySelectors: false,
					normalizeCharset: false,
					normalizeDisplayValues: false,
					normalizePositions: false,
					normalizeRepeatStyle: false,
					normalizeString: false,
					normalizeTimingFunctions: false,
					normalizeUnicode: false,
					normalizeUrl: false,
					normalizeWhitespace: false,
					orderedValues: false,
					reduceInitial: false,
					reduceTransforms: false,
					svgo: false,
					uniqueSelectors: false,
					//discardComments: { removeAll: true },
					//minifySelectors: false,
				},
			],
		}),
```
and it still removes the selector, is there anything cssnano does on its own?

**Comment by kurtextrem** [comment]
I have tested all other css minifiers on the market together with their postcss plugins and all do the same. They remove the `=''`. So I guess this is either a postcss-loader issue, a cssloader or a postcss issue... Hm.

**Comment by kurtextrem** [comment]
Honestly, no idea why this happens. If I don't minify the css, the selector isn't minified. If I add clean-css/cssnano/csso it is.
