### ISSUE TITLE
postcss-merge-longhand should preserve case of CSS custom properties

### ISSUE THREAD

**Issue by p-a** [cssnano/cssnano#648]
CSS custom properties are unlike other properties [case-sensitive](https://www.w3.org/TR/css-variables-1/#defining-variables)

postcss-merge-longhand however lowercases all properties which f.ex. turns

`.foo {
 border: 1px rgba(var(--camelCase),1);
}`

into

`.foo{border:1px rgba(var(--camelcase),1)}`

The culprit seems to be [parseWsc.js](https://github.com/cssnano/cssnano/blob/v4.1.7/packages/postcss-merge-longhand/src/lib/parseWsc.js#L27#L27)

Rather than bluntly lowercasing any match, it should try not to do that for custom properties.
I guess an easy workaround would be to just bailout if the string includes two consecutive dashes.

**Comment by evilebottnawi** [comment]
@p-a oh, it is bug, feel free to send a PR
