### ISSUE TITLE
Performance: Takes 4-6 seconds to load

### ISSUE THREAD

**Issue by pacifier007** [cssnano/cssnano#651]
I am using cssnano 4.1.4 with gulp (not the gulp plugin) and it's taking ~4seconds to load everytime:

```
console.time("Loading plugins"); // start measuring

const gulp = require('gulp');
const cssnano = require('cssnano');

console.timeEnd('Loading plugins');
```

And the result is usually 4-6seconds: `Loading plugins: 6321.839ms`

This is on MBP Retina with the extremely fast SSDs - it takes even longer on the standard SSDs. I read through the old issues but all I could find was that it'd be fixed in v4 which I'm already using.

**Comment by evilebottnawi** [comment]
@pacifier007 feel free to investigate problem and send a PR

**Comment by pacifier007** [comment]
I have tried it on multiple machines, isolated (without gulp) but the problem seems to persist. It just seems like cssnano is loading too much.

How much does it take for everyone else here? Anyone can share the times they're seeing? Knowing the MacOS version and Node version will be a great help.

**Comment by evilebottnawi** [comment]
@pacifier007 need enable/disable plugins step by step and search what is plugin has problem with perf, when send a PR with fix

**Comment by evilebottnawi** [comment]
@pacifier007 Looks `gulp` require many time to loading, locally `cssnano` only take `1.3`-`1.4`ms

**Comment by evilebottnawi** [comment]
But i agree it is very many, we should reduce time minimum on 2x
