### ISSUE TITLE
Configure cssnano options using browserlist

### ISSUE THREAD

**Issue by leimonio** [cssnano/cssnano#657]
`ccsnano` offers some configurable optimizations, like `calc`. Is there a way to use the browserlist in order to be able to configure these optimizations?

To give some more context, using webpack with `optimize-css-assets-webpack-plugin` for production builds results in transforming `calc(100vh - 5rem - calc(10rem + 100px))` to `calc(100vh - 5rem - 10rem + 100px)`.

This is not happening though when disabling `calc` optimizations on default preset
```js
preset: [`default`, { calc: false }]
```

**Comment by evilebottnawi** [comment]
@leimonio `browserslist` not related to `calc` optimization, You example is valid. What is problem? Which brosers is not supported this optimization?

**Comment by leimonio** [comment]
I'm trying to find out if there is a way to enable/disable `calc` optimization based on some configuration. To be more specific I'm trying to solve this problem https://github.com/gatsbyjs/gatsby/issues/9858 

Which is the best way to configure this optimization in a more dynamic way for the end user?

**Comment by evilebottnawi** [comment]
@leimonio hm, bug in `postcss-calc`
/cc @andyjansson

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/postcss/postcss-calc/issues/67, thanks for issue, sorry for delay
