### ISSUE TITLE
Add check to ensure `parent` is defined

### ISSUE THREAD

**Issue by jhpratt** [cssnano/cssnano#658]
See ben-eb/postcss-convert-values#39. When I was finding the source of my error, that is where it led me. It has since been archived, so I'm copying the issue to here.

**Comment by evilebottnawi** [comment]
@jhpratt can you provide link on problem place?

**Comment by jhpratt** [comment]
@evilebottnawi I'm not sure where exactly the problem is, as it's in the `node_modules/postcss-convert-values` directory (which is why I originally filed in the other repo). As that repo was closed in favor of this, I refiled here.

**Comment by evilebottnawi** [comment]
@jhpratt looks we rewrite this module, better avoid use this, also we don't have npm access to this module so we can't fix, sorry

**Comment by evilebottnawi** [comment]
@andyjansson hm, maybe we should migrate this module as unsafe optimization?

**Comment by andyjansson** [comment]
What? Why?

**Comment by evilebottnawi** [comment]
@andyjansson This is a minification and for some they can be safe.

**Comment by jhpratt** [comment]
Confirming what @andyjansson said. I was using cssnano (not `postcss-time-machine`, not sure where that came from) as the last plugin in my stack. It worked on its own, so I essentially added a second pass solely for minification. I'm not sure _why_ that worked, but it did. The error thrown is when it was all in a single pass.

I could attempt to narrow this to a test case, but given that it's a single-line fix — just adding `parent &&` at the beginning of the check — it hardly seems necessary.

**Comment by andyjansson** [comment]
> I was using cssnano (not postcss-time-machine, not sure where that came from) as the last plugin in my stack. 

From [this](https://github.com/ben-eb/postcss-convert-values/issues/27#issuecomment-351889104)

**Comment by jhpratt** [comment]
Ah, yeah. Still originates in cssnano, though. It's nothing specific to the
other plugin — my most recent instance of that was not even using that.

Jacob Pratt

**Comment by andyjansson** [comment]
Alright. You sure that none of the prior plugins manipulate the AST in such a way that the `parent` disappears? It *should* always be there. Does it work when you only have cssnano in your plugin stack?

**Comment by jhpratt** [comment]
Hmm...I stand corrected. I completely forgot I was using `postcss-time-machine`. Disabling that makes everything work as expected. I'll file an issue over there.

**Comment by jonathantneal** [comment]
I might need some help understanding what I’ve done that’s not allowed by cssnano.

https://github.com/jonathantneal/postcss-time-machine/blob/master/index.js#L146-L198

**Comment by jonathantneal** [comment]
I think that’s the issue. I’ll try to rewrite this plugin tonight, otherwise patch the issue and release a patch update. I didn’t realize how long it had been since it had been refactored.

**Comment by jonathantneal** [comment]
This has been fixed in PostCSS Time Machine. If someone can confirm that against this issue, it can be closed here.

**Comment by jhpratt** [comment]
Thanks for the quick turnaround @jonathantneal! I was honestly surprised to see it was your plugin that was the issue, but I guess we all get caught every now and then :smile:

I just tested it by placing cssnano back in with the main plugin stack, and no errors ensued. LGTM!
