### ISSUE TITLE
"not" notation when using @support API

### ISSUE THREAD

**Issue by SelfishLucho** [cssnano/cssnano#662]
Hi! I tried to find documentation or some sort of report issue but was not able to, If someone could pin point on where I should look to find my issue. I know that i can work around this but still would like to know how cssnano categories this.

Im trying to use the "not" notation when using [@support](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) API, however doesn't seem to trigger properly when using cssnano. Is there an option possibly I'm missing here that I should use or something needed to take in consideration when running nano?

Here is a [codepen](https://codepen.io/SelfishLucho/project/editor/ZvKKxO) on the css I'm trying to run

**Comment by evilebottnawi** [comment]
@SelfishLucho can you provide examples?

**Comment by SelfishLucho** [comment]
@evilebottnawi the codepen :), or do you want me to update it here?

**Comment by evilebottnawi** [comment]
@SelfishLucho what is broken? `@support` cannot be nested

**Comment by SelfishLucho** [comment]
@evilebottnawi When using `@support not (rule)`, "not" notation is not being taken in consideration by cssnano

**Comment by SelfishLucho** [comment]
@evilebottnawi Ok I try to use it without nesting it

**Comment by evilebottnawi** [comment]
@SelfishLucho can't reproducible :confused: here link on playground https://cssnano.co/playground/

**Comment by SelfishLucho** [comment]
@evilebottnawi Seems like it's actually including the "not" notation, but I will try without nesting that might be causing my issue. Is there a way find what compiling options the playground is using?

**Comment by evilebottnawi** [comment]
@SelfishLucho no options `safe` mode

**Comment by SelfishLucho** [comment]
@evilebottnawi Thanks for quick answer, I'll update with a more detailed question on my issue

**Comment by evilebottnawi** [comment]
Tests added for not notation https://github.com/cssnano/cssnano/pull/708 and all works as expected.
