### ISSUE TITLE
cssnano can't work with css module

### ISSUE THREAD

**Issue by LastStranger** [cssnano/cssnano#665]
![image](https://user-images.githubusercontent.com/29811304/49992167-39007300-ffbe-11e8-8261-b05eae95c15d.png)
![image](https://user-images.githubusercontent.com/29811304/49992187-487fbc00-ffbe-11e8-8353-8780d1e8f044.png)
when I use the CSS module, my index.css file's background image URL can't be resolved, if I remove cssnano from my postcss.config.js, then everything works fine. So I believe cssnano has some conflict with CSS module.

**Comment by evilebottnawi** [comment]
@LastStranger what version `css-loader` your are use? Please provide minimum reproducible test repo

**Comment by LastStranger** [comment]
"css-loader": "^1.0.1","cssnano": "^4.1.7", "webpack": "^4.26.1", I believe all my devDependencies are the recent version. I don't know how to provide you minimum reproducible test repo. This is the error down below. If I remove cssnano, everything works as I expect. If I don't use CSS module and with cssnanno added, the background image in css file can be resolved well.

![image](https://user-images.githubusercontent.com/29811304/49997909-d0b98d80-ffcd-11e8-97ba-13fa9b879296.png)

**Comment by evilebottnawi** [comment]
@LastStranger please update `css-loader` to `2` version, `1` version very buggy

**Comment by LastStranger** [comment]
OhOhOhOh, it solved. excellent, bro. Thank you so much, happy weekends

**Comment by evilebottnawi** [comment]
@LastStranger :+1:
