### ISSUE TITLE
Bug or feature with mergeLongheads for border

### ISSUE THREAD

**Issue by Dekkee** [cssnano/cssnano#667]
We got some kind templates in css and we use macros instead of values during build. After updating cssnano from 3.7.1 to 4.1.7 it starts to produce bad css.
All steps reproducible in playground.

### Input:
`
.some-class {
  border-width: __1__;
  border-color: __2__;
  border-style: solid;
}
`
### Output:

`
.some-class{border:solid}
`
### Expected: 

`
.some-class{border: __1__ solid __2__}
`

also there are some strange behavior with next css:
1. Input:
`
.some-class {
  border-width: __1__;
  border-color: red;
  border-style: solid;
}
`
Output:
`
.some-class{border:__1__ solid red}
`
1. Input: 
`
.some-class {
  border: __1__ solid __2__;
}
`
Output:
`
.some-class{border:solid __2__}
`

Is this a bug?

**Comment by evilebottnawi** [comment]
Because it is invalid `css`, we don't support invalid css, you should use `cssnano` as plugin for `webpack` (https://github.com/intervolga/optimize-cssnano-plugin) or put `cssnano` as last in postcss plugins, thanks
