### ISSUE TITLE
orderedValues transform fail with env()

### ISSUE THREAD

**Issue by kanongil** [cssnano/cssnano#673]
Input
```css
border-bottom:env(safe-area-inset-bottom) solid transparent;
```

Output (with env missing):
```css
border-bottom:solid transparent;
```

cssnano@4.1.8

**Comment by evilebottnawi** [comment]
@kanongil bug, feel free to send a PR

**Comment by kanongil** [comment]
Hmm, the rule doesn't really work when `env()` is used, as the actual value is evaluated at runtime. Ie. it could be any of the positions. The same actually goes for `calc()`, and I guess any other function.

I suspect that the solution is to disable the transform for the expression, if it contains any functions.

**Comment by evilebottnawi** [comment]
@kanongil can you provide link how we can reproduce problem?

**Comment by evilebottnawi** [comment]
Fixed https://github.com/cssnano/cssnano/pull/755
