### ISSUE TITLE
Incorrect handling of `@page :first`

### ISSUE THREAD

**Issue by MrMitch** [cssnano/cssnano#677]
Hi,

While trying to debug an issue in another package (https://github.com/symfony/webpack-encore/issues/498), it seems the root cause might come from an incorrect output produced by `cssnano`.

The [:first](https://developer.mozilla.org/fr/docs/Web/CSS/:first) pseudo-class can be used with `@page` to specify a set of rules that will only be applied to the first page of a printed document (using `@media print {}`).

The correct syntax of the selector is `@page :first` (according to the doc on MDN https://developer.mozilla.org/fr/docs/Web/CSS/:first) and `cssnano` seems to handle it erroneously.

The **`:`** before `first` is turned into a **`,`** as seen here : 

![demo from the playground](https://user-images.githubusercontent.com/850046/51404298-4ecffd80-1b53-11e9-8035-69f53e5b7faf.png)

I'm not sure how/where to look in the code to try and fix this, please let me know if there is anything more I can do to help or if I'm mistaken and this is an error on my part.

**Comment by MrMitch** [comment]
This used to work when the other project used `cssnano@3.10.0` but it breaks now that it has switched to `cssnano@^4.10.0`. I was hoping to provide some more detailed info regarding what commit might have introduced the behavior change but I couldn't really understand how to handle the `cssnano` repo.

Could you provide some guidance on how I could see the ouput of `cssnano` given a certain input file (lets say `style.css`) using the code in this repo ?

**Comment by evilebottnawi** [comment]
Looks like a bug, feel free to send a PR with fix

**Comment by MrMitch** [comment]
Hi @evilbottnawi,

Thank you for your reply.
I'd love to try and work on that but I'm having difficulties understanding how the repo is structured and how to handle it.
Is there a guide on how to setup the dev environment (apart from cloning and running `yarn install`) and/or how to start hacking on the project ?

**Comment by evilebottnawi** [comment]
@MrMitch Here documentation https://github.com/cssnano/cssnano/blob/master/CONTRIBUTING.md

**Comment by MrMitch** [comment]
@evilebottnawi thanks, I had already seen that, it didn't really help. I'll try to spend some time on it over the weekend.

**Comment by Lyrkan** [comment]
Hi there,

In case someones needs a workaround in the meantime: the issue doesn't seem to happen when `minifyParams` is disabled: https://runkit.com/embed/tmpvfbk3wldh

**Comment by evilebottnawi** [comment]
It should be very easy fix, jsut don't have time on this right now

**Comment by MrMitch** [comment]
@Lyrkan thank you, I was able to identify the part of the code that causes the issue, I'm preparing a PR at the moment.

@evilebottnawi no problem, I'm on it.
