### ISSUE TITLE
Online playground not working

### ISSUE THREAD

**Issue by GeassCoder** [cssnano/cssnano#683]
https://npm.runkit.com/cssnano when clicking run it gives error...

**Comment by evilebottnawi** [comment]
@GeassCoder it is not official playground, here official https://cssnano.co/playground/

**Comment by GeassCoder** [comment]
@evilebottnawi Thanks! I came across that link on the github page https://github.com/cssnano/cssnano. Please update it as it is confusing.

**Comment by evilebottnawi** [comment]
@GeassCoder oh, thanks for link, can you send a PR with fix link?

**Comment by GeassCoder** [comment]
@evilebottnawi Sure. Will do soon.

**Comment by evilebottnawi** [comment]
@GeassCoder thanks!
