### ISSUE TITLE
Exception On Invalid CSS

### ISSUE THREAD

**Issue by bentleyo** [cssnano/cssnano#714]
Hey there! I'm not sure if this is an issue, but I recently ran into a situation where `cssnano` crashed due to malformed CSS. In particular there was some CSS like this:

```
.timeline-item {
    padding:
}
```

You can replicate this in the online playground:
https://cssnano.co/playground/

I'm not familiar with this plugin so it took me a little while to track down from the exception message:
`TypeError: Cannot read property 'toLowerCase' of undefined`

**Comment by evilebottnawi** [comment]
@bentleyo yep, small bug, something need more checks, feel free investigate and send a PR

**Comment by indolentdeveloper** [comment]
I know the reason for this. canMerge.js has lines 

node.value.toLowerCase() === 'initial' which causes , Cannot read property 'toLowerCase' of undefined error.

I can create . PR if no one is doing it already.

**Comment by evilebottnawi** [comment]
PR welcome :+1:

**Comment by evilebottnawi** [comment]
I think we need add tests for cssnano package with default and advanced preset

**Comment by evilebottnawi** [comment]
Fixed https://github.com/cssnano/cssnano/pull/770/
