### ISSUE TITLE
[postcss-colormin] rgba(0, 0, 0, 0) conversion to transparent not always valid

### ISSUE THREAD

**Issue by 06b** [cssnano/cssnano#715]
Originally posted on /ben-eb/colormin#43 (but I'm assuming that project is deprecated and issues related to colormin should be made here) and related to issue #630

> Even if browser supports the keyword transparent. It's not always valid for all rules. The color property for example does not have transparent as a value. Which mean IE10 does not allow transparency for color, but will allow rgba(0, 0, 0, 0). This seems less of and issue for other browsers.
> https://www.w3.org/TR/CSS21/colors.html#propdef-color

Another example in which transparent not being valid is Firefox appears to ignore `background-color: transparent` on inputs & textareas when using High Contrast Mode in Windows, but it respects `background-color: rgba(0,0,0,0)`

**Comment by evilebottnawi** [comment]
@06b can you provide example, we can handle this on our level

**Comment by 06b** [comment]
Here's an example which I've tested in the cssnano playground:

**Input:**
```
/* Firefox when Windows High Contrast Mode is enabled: Firefox will ignore `transparent` but respect `rgba(0,0,0,0)` */
textarea { background-color: rgba(0,0,0,0); }

/* Edge when Windows High Contrast Mode is enabled: Edge will ignore `rgba(0,0,0,0)` but respect `transparent` */
@media screen and (-ms-high-contrast: active) {
 textarea {
    background-color: transparent;
  }
}
```

**Output:**
```
textarea{background-color:transparent} 
@media screen and (-ms-high-contrast:active){textarea{background-color:transparent}}
```

**Expected Output:**
```
textarea{background-color:rgba(0,0,0,0)} 
@media screen and (-ms-high-contrast:active){textarea{background-color:transparent}}
```

Let me know if you need anything else.

**Comment by evilebottnawi** [comment]
@06b Can find any information about this bug https://caniuse.com/#search=background-color, we can avoid tranformation based on browserslist, but we need list of problems browsers

**Comment by evilebottnawi** [comment]
For me it is look as firefox bug

**Comment by 06b** [comment]
From the related issue #630  it looks like there is a stackoverflow post related to rgba & transparent - https://stackoverflow.com/questions/32479188/whats-the-difference-between-rgba0-0-0-0-and-transparent

It looks like transparent is considered a true color in CSS Color Levels 3 but wasn't a true color in CSS Level 2 (Revision 1) - From [Historical Note from MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#transparent_keyword). 

So based off of that - I would assume that browsers should treat rgba(0,0,0,0) & transparent as the same but Firefox & Edge (and IE) appear to treat them both differently (at least this is what I can confirm in high contrast mode)

@evilebottnawi Let me know if this helps. I'll try to see if I can find more information on rgba & transparent and will also look to see if I can find any browser bugs already submitted on this.

**Comment by evilebottnawi** [comment]
@06b thanks for investigate, anyway you can send a PR with fix, if we can't find list of bugs browsers, we should disable this modification by default.

**Comment by 06b** [comment]
So after creating [multiple test cases](https://github.com/06b/High-Contrast-Mode-Reduced-Test-Cases) and testing high contrast mode with different browsers, I'm in agreement with you that this is most likely a firefox bug.

This [test](https://github.com/06b/High-Contrast-Mode-Reduced-Test-Cases/tree/master/02-transparent%20!important) shows the issue which appears to be present within Firefox Quantum (So Firefox 57 & above) as pre-Quantum Firefox/browsers based on the legacy Gecko engine (Tested with Firefox ESR 52.9.2 as that was the last Firefox ESR that was based on the legacy Gecko) don't appear to have the issue. I also quickly tested this theory with SeaMonkey 2.49.4, Waterfox 56.2.8, Pale Moon 28.4.0 while typing this reply.

I'm going to submit a bug to Firefox and I'll link to it once it's created.

**Comment by evilebottnawi** [comment]
@06b thanks for investigate

**Comment by evilebottnawi** [comment]
Thanks for investigate, close in favor firefox bug, disabled optimization increase optimized size and can't be solved on cssnano size, anyway feel free to feedback
