### ISSUE TITLE
Fix dependency on js-yaml version that has a code injection vulnerability

### ISSUE THREAD

**Issue by em0ney** [cssnano/cssnano#729]
Hi there,

Thanks for making cssnano!

you have a dependency on `svgo` which in turn has a dependency on `js-yaml`. Please see this report of a `High` severity vulnerability in this module.

https://www.npmjs.com/advisories/813

**Comment by em0ney** [comment]
```
├─┬ cssnano@4.1.10
│ ├─┬ cosmiconfig@5.1.0
│ │ └── js-yaml@3.12.2
│ └─┬ cssnano-preset-default@4.0.7
│   └─┬ postcss-svgo@4.0.2
│     └─┬ svgo@1.2.1
│       └── js-yaml@3.13.1
```

**Comment by evilebottnawi** [comment]
Feel free to send a PR, as workaround right now - regenerate your lock file

**Comment by BernardA** [comment]
This issue keeps on coming back.

I run npm audit fix a few times. It shows as resolved and then next time I install a package or run another npm command it will resurface. 

Running npm update js-yaml --depth 5, as advised by npm audit does not solve either.

**Comment by evilebottnawi** [comment]
update your deps and lock file

**Comment by BernardA** [comment]
I just did that and once the update install finished npm reported the vulnerabilities back again.
