### ISSUE TITLE
discardComments => removeAll => true  does not discard special comments

### ISSUE THREAD

**Issue by tomciopp** [cssnano/cssnano#751]
So I'm running into the following issue and I don't know why I can't get cssnano to delete all comments from my build. (Side note why are "special" comments kept at all?!) 

Here's my setup

`webpack.config.js` => rules
```javascript
  {
    test: /\.(sa|sc|c)ss$/,
    include: path.resolve(__dirname, "./css"),
    use: [
      {
        loader: miniCssExtractPlugin.loader,
        options: {
          hmr: process.env.NODE_ENV === 'development',
        },
      },
      "css-loader",
      "postcss-loader",
      "sass-loader"
    ]
  }
```

`postcss.config.js`
```javascript
module.exports = ({ file, options, env }) => ({
  map: false,
  plugins: {
    "postcss-import": {},
    "postcss-flexbugs-fixes": {},
    "postcss-preset-env": {
      stage: 3,
      browsers: ["last 2 versions", "> 1%"]
    },
    "cssnano": { "discardComments": { "removeAll": true } }
  }
});
```

`package.json` => devDependencies
```json
  "css-loader": "^2.1.1",
  "cssnano": "^4.1.10",
    ....
   "mini-css-extract-plugin": "^0.6.0",
   "postcss-clean": "^1.1.0",
    "postcss-discard-comments": "^4.0.2",
    "postcss-flexbugs-fixes": "^4.1.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "postcss-import": "^12.0.1",
    "postcss-load-config": "^2.0.0",
    "postcss-loader": "^3.0.0",
    "postcss-preset-env": "^6.6.0",
```

This has been quite frustrating as it makes no sense to me why I would still have comments in my minimized files. Any help would be greatly appreciated.

**Comment by evilebottnawi** [comment]
Don't use `cssnano` and postcss-loader, use https://github.com/NMFR/optimize-css-assets-webpack-plugin

**Comment by tomciopp** [comment]
@evilebottnawi This worked! Is there any way to update docs to reflect this?

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by ben-eb** [comment]
Important comments are skipped by default as they often contain licence information. This is consistent with https://github.com/jakubpawlowicz/clean-css#how-to-preserve-a-comment-block.

**Comment by evilebottnawi** [comment]
Here other problem, webpack have multiple steps when bundled, minify js/css/html/other on module level (`postcss-loader`) is invalid because other loaders/plugins can add new css assets or modify currents so it should be used only on minimize level

**Comment by tomciopp** [comment]
@ben-eb I understand the sentiment for keeping "important" comments, I just think the tradeoffs are absolutely not worth it. Practically no one is reading your source code in search of license violations. Furthermore licenses like the GPL should have a separate attribution section within a legal page or terms of use for any commercial product.

In practice a million sites will just have the following at the top of their css files.

    /*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */ 

Perhaps it would be just better for me to convince project owners to get rid of their important comments altogether.

**Comment by ben-eb** [comment]
I'm quite happy with the default behaviour; for instance Apache 2 licenses require the attribution notices to be preserved, so by stripping them you are violating the terms of the license. If you think that it's fine to do that then you can already change the behaviour.

More here: https://webmasters.stackexchange.com/questions/57362/is-it-legal-and-ethical-to-remove-license-notices-from-third-party-code/57364

**Comment by tomciopp** [comment]
@ben-eb Stripping the comments typically does not violate the license since the works created are "derivative". It would only be a violation if the thing you were distributing 

https://en.wikipedia.org/wiki/Apache_License#Licensing_conditions
https://en.wikipedia.org/wiki/Derivative_work

**Comment by ben-eb** [comment]
I don't understand the problem here. Since cssnano is an automated tool, it can't know that the code does or does not violate license terms by removing the comments. That's why the behaviour is opt-in.

If I go the other way and strip all important comments by default, I'm going to get authors of projects that put the comments in there telling me that this tool should not do that.

So I'm leaving the choice down to each consumer to do as they see fit.

**Comment by tomciopp** [comment]
@ben-eb Fair enough, I'm barking up the wrong tree. I should have beef with people who are wasting bandwidth by adding unimportant important comments.

**Comment by neox5** [comment]
for everyone looking for an answer in 2020:
```javascript
cssnano: {
  preset: ["default", { discardComments: { removeAll: true } }],
},
```

**Comment by ckken** [comment]
> for everyone looking for an answer in 2020:
> 
> ```js
> cssnano: {
>   preset: ["default", { discardComments: { removeAll: true } }],
> },
> ```

Comments are not automatically removed

**Comment by panpansh** [comment]
perfect using grunt thanks

```json
options: {
    processors: [
        require('cssnano')({
            preset: ["default", { discardComments: { removeAll: true } }],
        })
    ],
    map: false
},
```
