### ISSUE TITLE
line-height: 0px != line-height: 0

### ISSUE THREAD

**Issue by JamesCoyle** [cssnano/cssnano#768]
I'm using Vue CLI 3 which I'm told uses CSS Nano to perform the minification of the CSS resources for production builds. 

The following: 
```css
line-height: 0px;
    /* or */
line-height: 0rem;
```

Is transformed into 
```css
line-height: 0;
```

While both `0` and `0px` render the same, they are different values when used for `line-height`: `0px` is an explicit length value, `0` is 0% of the current `font-size`. In [this example](https://jsfiddle.net/xav85921/), you can see that `0px` can transition to `200px` whereas `0` cannot (seems to transition in Edge but not in FF or Chrome).

**Comment by evilebottnawi** [comment]
hm, looks you are right, PR weolcome

**Comment by evilebottnawi** [comment]
oh, it is bug in Edge, what version of Edge you are use?

**Comment by JamesCoyle** [comment]
The transformation from `0px` to `0` is breaking the animation in Chrome and FF but for some reason Edge seems to still animate despite this. I'm not sure what the specification says regarding this case (I feel like it _should_ animate) but the transformation CSS Nano is making is breaking the animation in some browsers and I personally feel it shouldn't be transforming a length value to a non-length value.

**Comment by evilebottnawi** [comment]
@JamesCoyle 

> The transformation from 0px to 0 is breaking the animation in Chrome and FF

Can reproduce using your example, all work fine in FF and Chrome

**Comment by JamesCoyle** [comment]
My team have all tested [that example](https://jsfiddle.net/xav85921/) in Chrome (stable, dev, and canary), FF, and Edge. In both Chrome and Firefox across multiple devices the left box animates correctly and the right one jumps into position.

**Comment by evilebottnawi** [comment]
@JamesCoyle yep, bug, thanks for clarify, feel free to send a PR, if you need fix it asap
