### ISSUE TITLE
Selectors with comment leads to unclosed comment error

### ISSUE THREAD

**Issue by ssivanatarajan** [cssnano/cssnano#777]
CSS nano reorders the selector in alphabetical order. if the selectors having comments it leads to unclosed comment error

please find the below result from css nano playground.
input:
```
.newbackbtn,/*.searchall,*/.calNav{
padding:5px;
}
```
output:
```
*/.calNav,.newbackbtn,/*.searchall{padding:5px}
```

**Comment by evilebottnawi** [comment]
Please provide example

**Comment by ssivanatarajan** [comment]
@evilebottnawi added example

**Comment by evilebottnawi** [comment]
Thanks

**Comment by ben-eb** [comment]
@evilebottnawi postcss-unique-selectors produces the incorrect output but I think it's a bug in PostCSS:

https://github.com/postcss/postcss/blob/558bc79e564f795c1502cf9bce712405e0193e1f/lib/rule.es6#L38-L40

`rule.selectors` does not account for comment tokens. We would have to rewrite postcss-unique-selectors to use postcss-selector-parser instead I think.

**Comment by evilebottnawi** [comment]
Maybe we still report bug in postcss?

**Comment by ben-eb** [comment]
I think it's a breaking change because it affects the `list.comma` utility which is used in a lot of plugins. 😞

**Comment by evilebottnawi** [comment]
I think we still should report

**Comment by ben-eb** [comment]
@evilebottnawi Seems it is a known issue: https://github.com/postcss/postcss/issues/1204
