### ISSUE TITLE
postcss-svgo fragments are removed from url

### ISSUE THREAD

**Issue by vincaslt** [cssnano/cssnano#807]
if I have a URL in the form of: `url(data:image/svg+xml;base64,BASE64ENCODEDSVG#css-caret)` the fragment part (`#css-caret`) will get removed which will result in my SVG icon not being shown in the minimized build.

From what I've checked in the code `svg = Buffer.from(svg, 'base64').toString('utf8');` will omit the fragment part, and when it's converted back, it's never added. Maybe it makes sense to check the url for fragment part, and add it back again after transformations are done by svgo?

**Comment by evilebottnawi** [comment]
@vincaslt look bug, feel free to send a PR
