### ISSUE TITLE
Upgrade browserslist to the latest (4.7.0)

### ISSUE THREAD

**Issue by ArtemZag** [cssnano/cssnano#813]
Currently cssnano uses browserslist version "^4.0.0".
Would be nice to update it to "^4.7.0".

**Comment by evilebottnawi** [comment]
Update your deps

**Comment by ArtemZag** [comment]
@evilebottnawi, there is no browserslist in my deps.
The only package which depends on old version of browserslist is cssnano.
![image](https://user-images.githubusercontent.com/1687370/64337633-75f71480-cfe8-11e9-8a6f-86fa056cfc09.png)

**Comment by evilebottnawi** [comment]
yarn upgrade

**Comment by ArtemZag** [comment]
@evilebottnawi , seems you are right. when I add cssnano to empty project it adds correct dependency. I'll try to run "yarn upgrade" on my project. Sorry.
