### ISSUE TITLE
postcss-merge-longhand compatibility with postcss-js

### ISSUE THREAD

**Issue by buz-zard** [cssnano/cssnano#815]
Hi, I'm trying to use `postcss-merge-longhand` with `postcss-js` and it doesn't seem to work. Is this expected?

Here's a demo link - https://codesandbox.io/s/icy-cloud-772zw

**Comment by evilebottnawi** [comment]
It is expected, we support only pure css

**Comment by buz-zard** [comment]
@evilebottnawi I see. Though I noticed that `postcss-convert-values` works fine with `postcss-js`, so I was wondering would consider a MR with added support for the `postcss-merge-longhand`? I might look into that.
