### ISSUE TITLE
postcss-colormin: code in "readme" contains an error

### ISSUE THREAD

**Issue by EmeraldWeb** [cssnano/cssnano#818]
I added an example archive.

```
TypeError: colormin is not a function
```

And postcss-colormin cannot be used as simple postcss plugin, because is
```Error: [object Object] is not a PostCSS plugin```
I think these problems are related, so maybe it’s good to add the following archive, but i think it's excess.

[postcss-colormin.zip](https://github.com/cssnano/cssnano/files/3608734/postcss-colormin.zip)

**Comment by evilebottnawi** [comment]
Feel free to send a PR
