### ISSUE TITLE
postcss-colormin: incorrect "colormin"'s color conversion

### ISSUE THREAD

**Issue by EmeraldWeb** [cssnano/cssnano#819]
I added an example archive.

```rgba(128, 128, 128, .5)``` converted to float percent:
```hsla(0,0%,50.2%,.5)```, but must be integer percent, like this:
```hsla(0,0%,50%,.5)```

[postcss-colormin.zip](https://github.com/cssnano/cssnano/files/3609108/postcss-colormin.zip)

**Comment by evilebottnawi** [comment]
50.2% !== 50%

**Comment by ben-eb** [comment]
@evilebottnawi I think it's correct, but it might not be optimal? `hsl` colours are [defined](https://drafts.csswg.org/css-color/#the-hsl-notation we have) as:

```
hsl() = hsl( <hue> <percentage> <percentage> [ / <alpha-value> ]? )
<hue> = <number> | <angle>
```

Where [`<percentage>`](https://drafts.csswg.org/css-values-3/#percentage-value) is defined as a number immediately followed by a percent sign. [Number is defined as follows](https://drafts.csswg.org/css-values-3/#number), note it can be float/integer.

The question remains, does casting this value to an integer (50.2 => 50) instead lose significant colour information? Could we make that optimisation?
