### ISSUE TITLE
The merge rules are not working

### ISSUE THREAD

**Issue by raky291** [cssnano/cssnano#820]
The merge rules are not working

css code:
```
.a {
  color: red;
}
.b {
  color: blue;
}
.c {
  color: red;
}
```

result:
```
.a{color:red}.b{color:#00f}.c{color:red}
```

expected:
```
.a,.c{color:red}.b{color:#00f}
```

But if I delete the middle code it works

css code:
```
.a {
  color: red;
}
.c {
  color: red;
}
```

result:
```
.a,.c{color:red}
```

**Comment by ben-eb** [comment]
@evilebottnawi We should probably add this to a FAQ. https://github.com/cssnano/cssnano/issues/805#issuecomment-513194030

**Comment by evilebottnawi** [comment]
Closed in favor https://github.com/cssnano/cssnano/issues/805#issuecomment-513194030
