### ISSUE TITLE
Postcss-svgo returns TypeError: Cannot read property 'toFixed' of undefined

### ISSUE THREAD

**Issue by djmtype** [cssnano/cssnano#821]
Since postcss-svgo utilizes svgo 1.3.0, my project is returning `TypeError: Cannot read property 'toFixed' of undefined` upon compiling some, but not all, base64 svgs inside my project. Once I manually roll back to svgo 1.2.2, the issue is resolved. 

There seems to be a closed svgo issue that should probably be re-opened. [https://github.com/svg/svgo/issues/990](https://github.com/svg/svgo/issues/990)

Is there an older postcss-svgo package that includes svgo v1.2.2 by default?

**Comment by strarsis** [comment]
@djmtype: It would be very helpful if you could provide a sample SVG that causes this issue.

**Comment by h3llc0r3** [comment]
Hi @djmtype @strarsis ,
we ran into the same issue with multiple svgs while updating our built system. We temporarily disabled svgo for cssnano.

Example, you'll see some **NaN** in the cssnano result: 
**cssnano turned off**
background-image: url("data:image/svg+xml,%3Csvg width='14' height='14' viewBox='0 0 14 14' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M13.88 5.051a.897.897 0 00-.837-.584H9.417a.298.298 0 01-.28-.199L7.834.578a.894.894 0 00-1.674 0l-.003.01-1.298 3.68a.298.298 0 01-.28.2H.951A.893.893 0 00.38 6.046l3.087 2.562a.298.298 0 01.093.323l-1.297 3.891a.894.894 0 001.375 -9.996l3.185-2.336a.298.298 0 01.352 0l3.183 2.335a.893.893 0 001.377-1.003L10.436 8.93a.299.299 0 01.093-.324l3.093-2.565a.894.894 0 00.258-.99z' fill='%23d98a28'/%3E%3C/svg%3E");

**cssnano turned on**
background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg width='14' height='14' viewBox='0 0 14 14' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M13.88 5.051a.897.897 0 0-.837-.584 NaNH9.164a.298.298 0 1-.28-.199 NaNL7.753 NaNa.894.894 0 0-1.674 0 NaNL4.483 NaN 4.859 NaNa.298.298 0 1-.28.2 NaNH.471a.893.893 0 .38 6.046 NaN NaNlNaN NaNa.298.298 0 1.093.323 NaN NaNlNaN NaNa.894.894 0 1.375 1.004 NaN NaNlNaN NaNa.298.298 0 1.352 0 NaN NaNlNaN NaNa.893.893 0 1.377-1.003 NaN NaNlNaN NaNa.299.299 0 1.093-.324 NaN NaNlNaN NaNa.894.894 0 .258-.99 NaN NaNz' fill='%23d98a28'/%3E%3C/svg%3E");

**Comment by djmtype** [comment]
Sadly updating to the latest version of cssnano v4.1.10 did not work for me. It failed with the usual error. Even updating postcss-svgo to v4.0.2 in conjunction was no help. Sage v9.0.9 will not compile base64 svgs successfully with `yarn build:production`.

For example, this throws a 'toFixed' error: 

```
background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Cpath d='M11.157 12a4.573 4.573 0 1 1-9.147 0 4.573 4.573 0 0 1 9.147 0zm10.833 0a4.573 4.573 0 1 1-9.147 0 4.573 4.573 0 0 1 9.147 0z' fill='%23ffffff' /%3E%3C/svg%3E");
```

**Comment by joselcc** [comment]
have you tried adding `"svgo": "1.3.0"` to your dependencies? 
https://github.com/svg/svgo/issues/1174

**Comment by djmtype** [comment]
I was using svgo v1.3.0 – that's the issue. [Please read my very first comment.](https://github.com/cssnano/cssnano/issues/821#issue-498473439)

**Comment by Tarka-Dhal** [comment]
Same problem.

**Comment by ludofischer** [comment]
Cannot reproduce it with cssnano 5.0.2 and the SVGs posted in https://github.com/svg/svgo/issues/990, I assume svgo  fixed it.
