### ISSUE TITLE
Converts 360deg to 1turn

### ISSUE THREAD

**Issue by RyanPWalker** [cssnano/cssnano#823]
I've noticed that when building with this npm, it converts my rotate animations from 360deg to 1turn. The css `turn` property is [not supported in many browsers](https://caniuse.com/#feat=mdn-api_css_turn) so this should not be used.  `turn` doesn't work in every browser I've tried including chrome.

Playground Input:
```
.class {
  transform: rotate(360deg);
}
```
Actual output:

```
.class{transform:rotate(1turn)}
```

Expected output

```
.class{transform:rotate(360deg)}
```

**Comment by evilebottnawi** [comment]
It is JS api and not related to css

**Comment by RyanPWalker** [comment]
What exactly does that mean and how is this not related?  It's a cssnano issue.

**Comment by evilebottnawi** [comment]
Your link refers on javascript API, it is not related to cssnano, turn supports almost all browsers

**Comment by nojvek** [comment]
cssnano just broke my site because of `rotateZ(360deg)` -> `rotate(1turn)` conversion. How do I tell css-nano to only remove duplicate rules and styles. Don't change the actual semantics? chrome doesn't do the right thing on `rotate(1turn)`

I thought cssnano was a safe transformer for its default rules, but apparently not.

**Comment by anikethsaha** [comment]
@nojvek can you submit a new issue. 

although the transformation is valid but I think we need to check the browser compatibility for this as firefox doesn't support that at all. 


>  How do I tell css-nano to only remove duplicate rules and styles. Don't change the actual semantics?

You can 
- [exclude the `postcss-convert-values` plugin](https://github.com/cssnano/cssnano/blob/master/site/content/guides/presets.md#excluding-transforms)
- or you can use [postcss-ignore-plugin](https://github.com/anikethsaha/postcss-ignore-plugin) (experimental)
