### ISSUE TITLE
Remove postcss-svgo from postcss-preset-default

### ISSUE THREAD

**Issue by KnisterPeter** [cssnano/cssnano#826]
Hi,

`cssnano-preset-default` includes `postcss-svgo` which is deprecated and not maintained anymore.
But it is still included here and as well to make the fakt critical contains a dependency to `js-yaml` in version below `3.13.1` which in turn suffers from two security issues. One labeled as high:

https://github.com/nodeca/js-yaml/issues/475
https://github.com/nodeca/js-yaml/pull/480

This should be updated or removed from the default preset.

**Comment by evilebottnawi** [comment]
postcss-svgo not deprecated, just moved in monorepo here https://github.com/cssnano/cssnano/tree/master/packages/postcss-svgo

**Comment by KnisterPeter** [comment]
@evilebottnawi My fault sorry, but then in this repo svgo should be updated to at 1.3.0 to get the security issues fixed. I'll make a PR, but can you please reopen this?

**Comment by evilebottnawi** [comment]
Just update your lock file, no need do this because we use `^` character in `package.json`

**Comment by KnisterPeter** [comment]
I use renovate with lockfile maintainance, so I have a very up-to date lockfile.
But I still have the security warnings from github and I would like to have them closed. Is there any problem with the update?

**Comment by evilebottnawi** [comment]
Maybe you use old version or something in your deps use old version of `cssnano`, all should be fine

**Comment by KnisterPeter** [comment]
This is the output from `yarn why js-yaml`:

```sh
=> Found "svgo#js-yaml@3.7.0"
info This module exists because "microbundle#rollup-plugin-postcss#cssnano#postcss-svgo#svgo" depends on it.
info Disk size without dependencies: "412KB"
info Disk size with unique dependencies: "956KB"
info Disk size with transitive dependencies: "1.03MB"
info Number of shared dependencies: 2
```
This led me to postcss-svgo which I wanted to fix. The PR is open, if you think it is worthless, then ignore it. Its up to you.
I just wanted to help.

**Comment by evilebottnawi** [comment]
Open issue in `rollup-plugin-postcss`

**Comment by KnisterPeter** [comment]
Thats `2.1.6`.

**Comment by evilebottnawi** [comment]
Please update plugin to `4.0.2`
