### ISSUE TITLE
Error: postcss-svgo: TypeError: Cannot set property 'multipassCount' of undefined

### ISSUE THREAD

**Issue by jantimon** [cssnano/cssnano#830]
`cssnano` is using `svgo` in version 1.3.1 which is broken right now.  

Users who use `cssnano-preset-default` seem not to be able to build anymore because of the following error:

`Error: postcss-svgo: TypeError: Cannot set property 'multipassCount' of undefined`

``` 
cssnano@4.1.10
   `-- cssnano-preset-default@4.0.7
       `-- postcss-svgo@4.0.2
           `-- svgo@1.3.1
```

**Comment by shenshanyoumu** [comment]
bad news when distribute software

**Comment by kvkens** [comment]
Is there a solution? Bro

**Comment by laibao101** [comment]
I have this problem, too

**Comment by ahwgs** [comment]
I have this problem, too

**Comment by kvkens** [comment]
```bash
npm install svgo@1.3.0 -D
```
A temporary solution 😞

**Comment by toBeTheLight** [comment]
I have this problem, too. 

> write `svgo: "1.3.0"` into package.json

A temporary solution

**Comment by WanLinLin** [comment]
If you are using yarn, there is a workaround in svgo repo's issue thread.

> For people using yarn add this to your package.json
> `"resolutions": { "svgo": "1.3.0" }`

https://github.com/svg/svgo/issues/1174#issuecomment-547658450

**Comment by WanLinLin** [comment]
svgo 1.3.2 bugfix is released.

https://github.com/svg/svgo/releases/tag/v1.3.2

Reinstall the packages should work. 😄

**Comment by evilebottnawi** [comment]
Fixed in svgo
