### ISSUE TITLE
rotate3d(0) crashes out

### ISSUE THREAD

**Issue by jsg2021** [cssnano/cssnano#834]
to reproduce just put this in to the playground:

```
.foo {
	transform: rotate3d(0);
}
```

Found this when adding `optimize-css-assets-webpack-plugin` to a project.  The problem boils down to a ValueParser instance that was constructed with `"rotate3d(0)"` but gets its `nodes` mutated to have an array of `length=1` and a value of `nodes[0]===undefined`

**Comment by anikethsaha** [comment]
I added a test to validate it

```js
test(
  "should work with rotate3d(0)",
  processCSS("h1{transform:rotate3d(0)}", "h1{transform:rotate3d(0)}")
);
```

And I think its passing,

![image](https://user-images.githubusercontent.com/26347874/68457652-ca0bb880-0226-11ea-90d3-caa3b76aa162.png)

Although I faced the crashing issue in the playground!

**Comment by evilebottnawi** [comment]
Maybe it is already fixed, so need add tests and we can close this

**Comment by anikethsaha** [comment]
> ```js
> test(
>   "should work with rotate3d(0)",
>   processCSS("h1{transform:rotate3d(0)}", "h1{transform:rotate3d(0)}")
> );
> ```

Should I add this same test ?

**Comment by evilebottnawi** [comment]
Yes :+1:

**Comment by anikethsaha** [comment]
The playground is still crashing

**Comment by evilebottnawi** [comment]
@anikethsaha i think it is because we don't update playground for a long time, we can do it before release

**Comment by anikethsaha** [comment]
ok , 👍
