### ISSUE TITLE
Configuration options missing in documentation.

### ISSUE THREAD

**Issue by Omnivoreye** [cssnano/cssnano#849]
The documentation does not provivide any information on individual optimisations configuration. There is only one example with `discardComments` in _Presets_ page. I created a [question](https://stackoverflow.com/questions/59148593/how-to-configure-cssnano-for-css-minification/59148669#59148669) on SO regarding this matter.

**Comment by anikethsaha** [comment]
Preset is build by running individual plugins under the hood. So you need to check their docs. 
You can find the plugin list in the preset readme.

**Comment by Omnivoreye** [comment]
So the only way to configure wanted optimisations is o choose one of two presets, right?

**Comment by anikethsaha** [comment]
Yes . 
You can even add those single postcss plugins as well if you want specific type of optimization

**Comment by Omnivoreye** [comment]
Thanks!

**Comment by anikethsaha** [comment]
Glad to help.
You can close this issue of if its fine by you
