### ISSUE TITLE
`min-width: initial` gets incorrectly modified to `min-width: 0`

### ISSUE THREAD

**Issue by Bazeloth** [cssnano/cssnano#850]
This should be `min-width: auto`. This (sometimes) resolves to `min-width: 0`, but not at all times.

![image](https://user-images.githubusercontent.com/19928782/70234355-c2293080-1760-11ea-9a01-8431da543e85.png)

https://developer.mozilla.org/en-US/docs/Web/CSS/min-width

Caused by: https://github.com/cssnano/cssnano/tree/master/packages/postcss-reduce-initial

**Comment by evilebottnawi** [comment]
Please create reproducible example

**Comment by Bazeloth** [comment]
> Please create reproducible example

A colleague of mine will provide a reproducable example shortly.

**Comment by anikethsaha** [comment]
![image](https://user-images.githubusercontent.com/26347874/70235332-c701da80-1788-11ea-8986-97c073248830.png)

Cant reproduce this from the playground.

**Comment by chrarnoldus** [comment]
Repro: https://github.com/progressonderwijs/reduceinitalbug

**Comment by anikethsaha** [comment]
https://github.com/cssnano/cssnano/blob/c8ff54f4f6a168ca2a6f74d6fdbef5f28dc89282/packages/postcss-reduce-initial/data/fromInitial.json#L172

Need to make it `auto`. But need confirmation whether `auto` is correct minification or not.

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by Bazeloth** [comment]
> PR welcome

I'm sorry are you expecting us to fix this or..?

**Comment by anikethsaha** [comment]
> > PR welcome
> 
> I'm sorry are you expecting us to fix this or..?

if you want ....go for it....else i will do it

**Comment by Bazeloth** [comment]
You are welcome to apply a fix. We've disabled https://github.com/cssnano/cssnano/tree/master/packages/postcss-reduce-initial for now in our webpack.config.js and are able to continue.

**Comment by anikethsaha** [comment]
> You are welcome to work on a fix. We've disabled https://github.com/cssnano/cssnano/tree/master/packages/postcss-reduce-initial for now in our webpack.config.js and are able to continue.

Ok will try to fix it asap. and will let you know 👍

**Comment by Bazeloth** [comment]
Thanks for fixing this on such a short term @anikethsaha

**Comment by anikethsaha** [comment]
Glad to help

**Comment by daniel-nagy** [comment]
Is this correct? I'm seeing conflicting documentation for the initial value. https://www.w3.org/TR/CSS2/visudet.html#min-max-widths.
