### ISSUE TITLE
Wrong merge with mergeRules

### ISSUE THREAD

**Issue by Nes-si** [cssnano/cssnano#854]
Hello.
I found a problem with **mergeRules**. 

I have a CSS like this:
```
.Sites---element---1v8VV:hover .Sites---site-name---1j0wd {
    color: #fff;
}

.Sites---element---1v8VV .Sites---site-name---1j0wd {
  background: none;
  font-size: 12px;
  ....
}
```

mergeRules transform it into this:
```
.Sites---element---1v8VV:hover .Sites---site-name---1j0wd {
    color: #fff;
  background: none;
  font-size: 12px;
  ....
}
```

So when `Sites---element` is not on a hover, `Sites---site-name` does not receive its rules (`background: none`, `font-size: 12px` and others). It totally ruins all styles.

**Comment by anikethsaha** [comment]
yes it is bug, the selector list should be completely matched in order to do the merging.

**Comment by Nes-si** [comment]
I think it's a quite serious bug. Maybe at least it should be temporary switched off in the default preset if there is no way to easy fix it?

**Comment by anikethsaha** [comment]
Will submit a fix soon.

**Comment by anikethsaha** [comment]
@Nes-si did you check with the cssnano playground . It's doing the correct merging. 
Are you on the latest version ?

**Comment by Nes-si** [comment]
@anikethsaha yes, I use v4.1.10.
You can see the bug in my project [Chisel](https://github.com/beachio/chisel). `npm build` command builds the CSS in a `dist/main.min.css` file; you can switch on/off `mergeRules` in a `postcss.config.js` and compare results.

**Comment by anikethsaha** [comment]
I couldn't able to reproduce it from my setup and even from the cssnano's playground.
Can you share a minimal repo or sandbox cause the project you share is quite big and I guess its using electron which I am not used to?
It would be better to have a sandbox.

**Comment by Nes-si** [comment]
@anikethsaha hi, I've done a minimal repo: https://github.com/Nes-si/mergerRules-error-demo .
To work with it, run `npm i` and `npm run build` to create a build, then check `dist/main.min.css`. You can switch on/off `mergeRules` in `postcss.config.js`, all other optimizations are switched off.

**Comment by anikethsaha** [comment]
Put the if statement for production (https://github.com/Nes-si/mergerRules-error-demo/blob/master/postcss.config.js#L6) after the extension statement. (https://github.com/Nes-si/mergerRules-error-demo/blob/master/postcss.config.js#L47)
mean, the `cssnano` should be after `precss` in the plugin array. 
you can keep the mergerule `true` as well 
It will work fine 👍

**Comment by Nes-si** [comment]
Oh. I've confused a plugin order in array. I'm sorry.
But for me, PostCSS docs in this part isn't clear enough.
Please, close the issue.

**Comment by anikethsaha** [comment]
> Please, close the issue.

i cant,
