### ISSUE TITLE
devServer in /site does not seem to start 

### ISSUE THREAD

**Issue by nisarhassan12** [cssnano/cssnano#866]
In the /site directory after running `yarn install` I tried `yarn start` but I'm getting the following error.

![image](https://user-images.githubusercontent.com/46004116/72356315-e20e2580-370a-11ea-8b58-48b69188d017.png)

Also, the test suite in the root of the project seems to be failing.

![image](https://user-images.githubusercontent.com/46004116/72356790-a9bb1700-370b-11ea-9a1c-68c7edcb3ce3.png)

**Comment by evilebottnawi** [comment]
Feel free to send a PR with fix

**Comment by nisarhassan12** [comment]
@evilebottnawi I'm sorry! I would have made a PR but i don't the fix.

**Comment by anikethsaha** [comment]
you need to run `yarn run build:metadata` from root first then run the `start` command from `site`

better run `yarn run build:site`

**Comment by nisarhassan12** [comment]
@anikethsaha Thanks ! :slightly_smiling_face:  After i ran ```yarn run build:metadata``` I ran ```yarn run build:site``` from the root & i got this: 
![image](https://user-images.githubusercontent.com/46004116/72492084-d8d1a580-383d-11ea-83d8-b6201fb4a05b.png)

Also ```yarn start``` from the /site directory is not working.

![image](https://user-images.githubusercontent.com/46004116/72492161-11717f00-383e-11ea-89ca-8e74293f47df.png)

**Comment by anikethsaha** [comment]
I guess something to do with phenomic. Try tracing back the error
