### ISSUE TITLE
What option could cause variable to lowcase

### ISSUE THREAD

**Issue by 1Jesper1** [cssnano/cssnano#902]
In LESS specified variable: `@mainColor: ~"##mainColor##";` results in `##maincolor##`.

**Comment by anikethsaha** [comment]
Please fill the issue template and also, we dont support `LESS` support, it has to be compiled to raw css.

**Comment by 1Jesper1** [comment]
@anikethsaha Thanks for the fast reply. I will investigate this.

**Comment by 1Jesper1** [comment]
This the css: `.test {
	border-bottom: 7px solid ##mainColor##;
}` this will be: `.test{border-bottom:7px solid ##maincolor##}` in playground: https://cssnano.co/playground/

**Comment by 1Jesper1** [comment]
**Describe the bug**
CSS template variable to lowercase

**To Reproduce**
Steps to reproduce the behavior:
This the css: .test { border-bottom: 7px solid ##mainColor##; } this will be: .test{border-bottom:7px solid ##maincolor##} in playground: https://cssnano.co/playground/

**Expected behavior**
No transform on template variable name.

**Comment by anikethsaha** [comment]
`test { border-bottom: 7px solid ##mainColor##; }` I think this is an invalid CSS.  and for sure this is not css variable. 

With css variable, cssnano doesnt lowercase the variables. check the demo below.
[demo](https://cssnano.netlify.app/playground#eyJpbnB1dCI6Ii8qIHdyaXRlIHlvdXIgY3NzIGJlbG93ICovXHJcblxyXG5cclxuY3tcclxuICAgIC0tbWFpbkNvbG9yIDogJ3JlZCc7XHJcbiAgICBjb2xvciA6IHZhcigtLW1haW5Db2xvciApO1xyXG59IiwiY29uZmlnIjoiLy8gY3NzbmFubyBjb25maWdcbntcbiAgXCJwcmVzZXRcIiA6IFwiZGVmYXVsdFwiLFxufVxuIn0=)

**Comment by 1Jesper1** [comment]
@anikethsaha You are right, we overwrite this ##mainColor## later on, so I named it CSS template variable.

Test: [demo](https://cssnano.netlify.app/playground/#eyJpbnB1dCI6Ii8qIHdyaXRlIHlvdXIgY3NzIGJlbG93ICovXHJcblxyXG5cclxuY3tcclxuICAgIC0tbWFpbkNvbG9yIDogJ3JlZCc7XHJcbiAgICBjb2xvciA6ICMjbWFpbkNvbG9yIyM7XHJcbiAgICBib3JkZXItYm90dG9tOiAgM3B4IHNvbGlkICMjbWFpbkNvbG9yIyM7XHJcbn0iLCJjb25maWciOiIvLyBjc3NuYW5vIGNvbmZpZ1xue1xuICBcInByZXNldFwiIDogXCJkZWZhdWx0XCIsXG59XG4ifQ==)

**Comment by anikethsaha** [comment]
> we overwrite this ##mainColor## later on

how you are overwriting?

what is CSS template variable ? is it in css specs ?

```css
c{
    --mainColor : 'red';
    color : ##mainColor##;
    border-bottom:  3px solid ##mainColor##;
}
```

this is an invalid css, so it will lead to invalid modification. CSSNANO expects plain raw CSS without any "to be compiled" css and also we only support CSS that is in the specs.

**Comment by 1Jesper1** [comment]
Thanks, I understand. I will use a workaround: [demo](https://cssnano.netlify.app/playground/#eyJpbnB1dCI6Ii8qIHdyaXRlIHlvdXIgY3NzIGJlbG93ICovXHJcblxyXG5cclxudGVzdHtcclxuICAgIC0tbWFpbkNvbG9yIDogJ3JlZCc7XHJcbiAgICBib3JkZXItYm90dG9tLXdpZHRoOiAgM3B4IDtcclxuXHJcbn1cclxuXHJcbnRlc3R7XHJcbiAgICBib3JkZXItYm90dG9tLWNvbG9yOiAgIyNtYWluQ29sb3IjIztcclxuICAgIGJvcmRlci1ib3R0b20tc3R5bGU6ICBzb2xpZCA7XHJcbn0iLCJjb25maWciOiIvLyBjc3NuYW5vIGNvbmZpZ1xue1xuICBcInByZXNldFwiIDogXCJkZWZhdWx0XCIsXG59XG4ifQ==)

**Comment by anikethsaha** [comment]
let me know if you need any help.
