### ISSUE TITLE
[Bug] : TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by hdxqnljs** [cssnano/cssnano#903]
![image](https://user-images.githubusercontent.com/20278807/80355987-6005cf00-88ab-11ea-9b97-85bb4e0b0e67.png)
![image](https://user-images.githubusercontent.com/20278807/80356166-a4916a80-88ab-11ea-8d50-7e2aba16b5fe.png)
help me,  pls

**Comment by anikethsaha** [comment]
please fill the issue template.
share your code, config and environment .

**Comment by hdxqnljs** [comment]
![image](https://user-images.githubusercontent.com/20278807/80371221-1ecde900-88c4-11ea-853e-5be2f47a567f.png)
I figure out why this error occurs;
it is my problem, not yours;
i think I need stricter code inspection;
Sorry for wasting your time;
I have closed it；
Thanks for your reply.

**Comment by anikethsaha** [comment]
just a suggestion: use linters for these static analyses. they help a lot 👍 .
