### ISSUE TITLE
cssnano config outside `postcss.config.js` has no effect

### ISSUE THREAD

**Issue by elementalhub** [cssnano/cssnano#904]
**Describe the bug**
I need to disable the colormin plugin. 'colormin: false' in cssnano config does not do anything. 
I'm using cssnano with postCSS and webpack.

**To Reproduce**
This is my cssnano config:
```
preset: ['default', {
    colormin: false, // ! doesn't work
}]

```

**Expected behavior**
I expect to be able to disable the colormin plugin. However colors are still being minified (#ff0000 -> red)

**Desktop (please complete the following information):**
- CSSNANO Version [4.1.10] 
- Plugins/presets versions: 
cssnano-preset-default@^4.0.7
postcss-colormin@^4.0.3
- Add the output of `npx envinfo && npm ls cssnano` here
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 65.63 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - ~/.nodenv/shims/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.7.0 - ~/.nodenv/shims/npm
  Managers:
    Homebrew: 2.2.4 - /usr/local/bin/brew
    Maven: 3.3.9 - /Applications/apache-maven-3.3.9/bin/mvn
    RubyGems: 2.5.2 - /Applications/MAMP/Library/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.21.0 - /usr/bin/git
    Clang: 1100.0.33.16 - /usr/bin/clang
    Subversion: 1.5.0 - /usr/local/bin/svn
    FFmpeg: 2.7.2 - /usr/local/bin/ffmpeg
  Servers:
    Apache: 2.2.34 - /Applications/MAMP/Library/bin/apachectl
  Virtualization:
    Docker: 19.03.8 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Emacs: 22.1.1 - /usr/bin/emacs
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.0 - /usr/bin/vim
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.13.7 - /usr/local/bin/go
    Java: 1.8.0_111 - /usr/bin/javac
    Perl: 5.24.0 - /Applications/MAMP/Library/bin/perl
    PHP: 7.2.1 - /Applications/MAMP/bin/php/php7.2.1/bin/php
    Python: 2.7.13 - /Applications/MAMP/Library/bin/python
    Ruby: 2.3.3 - /Applications/MAMP/Library/bin/ruby
  Databases:
    MySQL: 5.6.38 - /Applications/MAMP/Library/bin/mysql
    PostgreSQL: 12.1 - /usr/local/bin/postgres
    SQLite: 3.24.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 81.0.4044.129
    Chrome Canary: 84.0.4131.0
    Firefox: 74.0.1
    Safari: 13.1

Any help is greatly appreciated. Thank you!

**Comment by anikethsaha** [comment]
can you try `exclude` like this

```js
{
  "preset" : ["default",{"colormin" : {"exclude" : true}}]
}

```

**Comment by elementalhub** [comment]
I tried that as well, does not work.


-- 
Stefanie Hein
e/ement:s

Anklamer Straße 38
10115 Berlin
0049 163 454 19 46

steffi@the-elements.de
the-elements.de <http://www.the-elements.de/>

**Comment by anikethsaha** [comment]
umm, 😕 

let me check in the master, it might have fixed but not released .

**Comment by anikethsaha** [comment]
This is working fine in `master` version. in the next release, it will be fixed.

**Comment by elementalhub** [comment]
Great, thanks for the help and update. When will the next release be?

**Comment by anikethsaha** [comment]
soon

**Comment by cathrinevaage** [comment]
Is this for the `colormin` plugin only, or will it be applicable for every plugin?
I took a peak at the default preset in master, and I can't see anything that implies there is an `exclude` option, which would make sense if it was only for `colormin`.

**Comment by ludofischer** [comment]
5.0.0 has been released https://www.npmjs.com/package/cssnano/v/5.0.0 which should contain the fix

**Comment by jaszfalvitamas** [comment]
Hi there!

I tried to disable SVGO using this guide: https://cssnano.co/docs/presets, but neither the cssnano.config.js nor the package.json version work for me. I always get this error:
Error: postcss-svgo: Error in parsing SVG: Unquoted attribute value

I'm using yarn, and forced both cssnano and postcss to the latest version. Any help would be greatly appreciated on how to disable this plugin!

**Comment by ludofischer** [comment]
> I'm using yarn, and forced both cssnano and postcss to the latest version. I also have a webpack.config.js due to Symfony's webpack encore. Any help would be greatly appreciated on how to disable this plugin!
What cssnano version are you using exactly?

**Comment by jaszfalvitamas** [comment]
cssnano@5.0.0 is installed to node_modules.

**Comment by ludofischer** [comment]
@jaszfalvitamas Have you got `postcss.config.js`? Try to put the configuration in there instead of `cssnano.config.js`.  In  [this test  repository I have created](https://github.com/ludofischer/cssnano-config-test) `cssnano.config.js` has no effect but `postcss.config.js` does.

**Comment by ludofischer** [comment]
I do not understand the use case for `cssnano.config.js`. `postcss.config.js` takes precedence. So its use limited to configuring a tool that invokes cssnano without exposing a postcss config AND without exposing its own config (for example https://github.com/webpack-contrib/css-minimizer-webpack-plugin has got its own config)

**Comment by jaszfalvitamas** [comment]
Here's what worked for me:
I searched through @symfony/webpack-encore for postcss stuff, and found an option named `Encore.enablePostCssLoader();`
Having that line added to my webpack.config.js AND creating a postcss.config.js I managed to disable the svgo loader. So on my end, issue seems to be resolved. Sorry for the inconvinience!
