### ISSUE TITLE
[Bug] : 错误报告

### ISSUE THREAD

**Issue by SEA-DH** [cssnano/cssnano#907]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (from [cssnano-playground](https://cssnano.co/playground/))

**Desktop (please complete the following information):**
- CSSNANO Version [e.g. 22] 
- Plugins/presets versions
- Add the output of `npx envinfo && npm ls cssnano` here

**Additional context**

**Comment by anikethsaha** [comment]
fill the template please
