### ISSUE TITLE
Equal sign is added to end of empty query string variable

### ISSUE THREAD

**Issue by mustafa0x** [cssnano/cssnano#913]
- https://cssnano.co/playground/
- In:    `* {background: url(https://example.com/img?a)}`
- Out: `*{background:url(https://example.com/img?a=)}`

**Comment by anikethsaha** [comment]
This is intentional behavior, we are normalizing the URL (done by the [`postcss-normalize-url`](https://github.com/cssnano/cssnano/tree/master/packages/postcss-normalize-url) plugin from the preset) using [normalize-url](https://github.com/sindresorhus/normalize-url).

**Comment by mustafa0x** [comment]
Seems to be inconsistent then:

- In:    `* {background: url(/img?a)}`
- Out: `*{background:url(/img?a)}`

**Comment by anikethsaha** [comment]
I guess `/img?a` is an invalid url.

**Comment by mustafa0x** [comment]
It's a relative URL.

https://google.com/#q=relative+URL

**Comment by anikethsaha** [comment]
![image](https://user-images.githubusercontent.com/26347874/85145370-1792de00-b26a-11ea-88ec-efc4a2079ab6.png)

Invalid for `normalize-Url` .

**Comment by mustafa0x** [comment]
It doesn't support processing relative URLs.

https://github.com/sindresorhus/normalize-url/issues/56

CSS of course supports them.

**Comment by anikethsaha** [comment]
cssnano is build time, not runtime. So it cant resolve it to absolute

**Comment by mustafa0x** [comment]
I'm not sure how that relates to the issue.

In any case, I filed a bug in the normalize repo. https://github.com/sindresorhus/normalize-url/issues/112
