### ISSUE TITLE
[Bug] : dot-prop version with security vulnerability a transitive dependency of cssnano-preset-default

### ISSUE THREAD

**Issue by karlhorky** [cssnano/cssnano#931]
**Describe the Bug**

A version of `dot-prop` before `5.1.1` is a transitive dependency of `cssnano-preset-default@4.0.7` (the latest published version):

![Screen Shot 2020-07-31 at 10 43 10](https://user-images.githubusercontent.com/1935696/89019371-7cd3f780-d31d-11ea-8876-9767666459cf.png)

This results in security vulnerability warnings on any project that uses this version: https://github.com/advisories/GHSA-ff7x-qrg7-qggm

![Screen Shot 2020-07-31 at 10 42 42](https://user-images.githubusercontent.com/1935696/89019423-9117f480-d31d-11ea-87db-5120d25eb6fd.png)

**To Reproduce**

1. Install latest version of `cssnano-preset-default`
2. Get a security vulnerability warning

**Expected Behavior**

The transitive version of `dot-prop` should be `5.1.1` or higher.

**Temporary Workaround**

Use [Yarn Resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to pin to `dot-prop@5.1.1`.

**Desktop (please complete the following information):**
- CSSNANO Version 4.1.10
- cssnano-preset-default@4.0.7
- Add the output of `npx envinfo && npm ls cssnano` here

**Comment by karlhorky** [comment]
More context here: https://github.com/cssnano/cssnano/issues/916

**Comment by karlhorky** [comment]
Apparently another workaround mentioned by @anikethsaha is to use `cssnano-preset-default@nightly`: https://github.com/cssnano/cssnano/issues/916#issuecomment-667015250

**Comment by anikethsaha** [comment]
It looks like an dependencies from `postcss-selector-parser` . 

Can you backtrack that from where we are getting `dot-prop` ?

**Comment by karlhorky** [comment]
One of the dependency chains is like this:

1. `cssnano-preset-default`
2. `postcss-merge-rules@^4.0.3`
3. `postcss-selector-parser@^3.0.0`

**Comment by karlhorky** [comment]
Here's the output of `yarn why postcss-selector-parser`:

```
=> Found "postcss-merge-rules#postcss-selector-parser@3.1.1"
info This module exists because "react-scripts#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-merge-rules" depends on it.
=> Found "postcss-minify-selectors#postcss-selector-parser@3.1.1"
info This module exists because "react-scripts#optimize-css-assets-webpack-plugin#cssnano#cssnano-=>
=> Found "stylehacks#postcss-selector-parser@3.1.1"
info This module exists because "react-scripts#optimize-css-assets-webpack-plugin#cssnano#cssnano-preset-default#postcss-merge-longhand#stylehacks" depends on it.
```

**Comment by evilebottnawi** [comment]
What is version of `cssnano` do you use?

**Comment by evilebottnawi** [comment]
We wait postcss@8 for new release

**Comment by karlhorky** [comment]
> What is version of `cssnano` do you use?

From the description above:

CSSNANO Version 4.1.10

**Comment by evilebottnawi** [comment]
It is fixed https://github.com/postcss/postcss-selector-parser/blob/v3.1.2/package.json#L41, can you regenerate lock file?

**Comment by evilebottnawi** [comment]
You need to update transitive dep

**Comment by karlhorky** [comment]
Works, thanks! Deleted the `postcss-selector-parser` entry in `yarn.lock` and ran `yarn` and now have the new version.

Closing.

**Comment by evilebottnawi** [comment]
Great!
