### ISSUE TITLE
[Bug] Prototype pollution in dependency "dot-prop"

### ISSUE THREAD

**Issue by JanErikGunnar** [cssnano/cssnano#934]
**Describe the bug**
Prototype pollution security issue in outdated dependency "dot-prop" 4.2.0

https://npmjs.com/advisories/1213

**To Reproduce**
1. Add dependency to cssnano 4.1.10 using npm install
2. Run npm audit

**Expected behavior**
No errors reported by npm audit

Let me know if further information is required

**Comment by anikethsaha** [comment]
Please run nom audit fix as of now. 

This package is coming from upstream for us. So we need to wait for their release and then we can update that. 
But still the next release for cssnano will be after postcss@8 . 
In the meantime you can use the cssnano nightly tay that is up to date with the `master`

**Comment by evilebottnawi** [comment]
Fixed, please update your deps
