### ISSUE TITLE
Update eslint to v7.x.x

### ISSUE THREAD

**Issue by anikethsaha** [cssnano/cssnano#939]
Currently, we are using the old version ([5.16.0](https://github.com/cssnano/cssnano/blob/master/package.json#L41) - 2  major versions behind ). As our codebase is quite huge, I am noticing a very slow linting operation  ([`fixlint`](https://github.com/cssnano/cssnano/blob/master/package.json#L7)) lately, both in my local machine and in the cloud (`gitpod`).

I would prefer to update to the latest version of eslint i.e `v7.6.0`. There are few breaking changes and some changes in the config file as well and few deprecated rules as well.

We also need to update the plugins (`react`, `import`, `prettier`), and the parser (`babel-eslint`). 

_step wise will be updated soon here for better contribution experience_

**Comment by evilebottnawi** [comment]
Let's do it :+1:

**Comment by anikethsaha** [comment]
https://github.com/cssnano/cssnano/pull/959
