### ISSUE TITLE
[Bug] : Docs links are broken

### ISSUE THREAD

**Issue by shumbo** [cssnano/cssnano#942]
**Describe the bug**

It seems that the entire documents are moved under `/docs`, but the links in the markdown files did not get updated. Hence if we click the links on a document, we see 404.

**To Reproduce**
1. Go to the page in the documents with a link (e.g. https://cssnano.co/docs/optimisations/#__docusaurus:~:text=autoprefixer, https://cssnano.co/docs/Introduction#what-is-cssnano:~:text=our%20getting%20started%20guide)
2. Click the link
3. See 404 error

**Expected behavior**

Links should have `/docs` at the top and navigate us to the correct pages.

**Screenshots**
N/A

**Desktop (please complete the following information):**

N/A

**Additional context**

I couldn't really tell the change of the URL was intentional. If the change was on purpose and the markdowns need updating, I can help replace the links.

Thanks.

**Comment by anikethsaha** [comment]
fixed in https://github.com/cssnano/cssnano/commit/4027ed7a7cc2f19887bd488b5db953ebab0d3458
