### ISSUE TITLE
[Feature Request] Include postcss-normalize-display-values

### ISSUE THREAD

**Issue by felixfbecker** [cssnano/cssnano#945]
**Is your feature request related to a problem? Please describe.**
In the latest spec (out for a while now) the `display` property values were split into two values, outside and inside. Imo this is a lot more intuitive than the previous variations with `inline-` prefix or without. Unfortunately, it is not supported yet by any browsers, but it is what is documented when you look up `display` on MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/display

**Describe the solution you'd like**
There's a PostCSS plugin that does this: https://github.com/cssnano/cssnano/tree/master/packages/postcss-normalize-display-values
It seems like it just needs to be included.

**Describe alternatives you've considered**
Including this in autoprefixer, but it's not about prefixes.  https://github.com/postcss/autoprefixer/issues/1319

**Additional context**

**Are you willing to work on this ?**

Depends on the guidance and work needed to do this because I'm not familiar with the codebase.

**Comment by anikethsaha** [comment]
Thanks for the issue. 

I am not sure whether I am getting the request or not. Can you please explain a bit more. Are you recommending to add `display-*` to the transformation list ?

**Comment by felixfbecker** [comment]
Basically, `display: inline flex` should be transformed to `display: inline-flex` when using `postcss-env`.

**Comment by anikethsaha** [comment]
Thanks, 

Yeah make sense, but I think we should probably use browser list's env browsers and then do the transformation so that it doesnt break the old browsers versions and also the browser this doesn't support.

**Comment by felixfbecker** [comment]
Definitely in favor of using browserlist, but no modern browser supports this yet, so this would _effectively_ run for every browser. It could transform to two statements too to get browsers to fall back.

The plugin I linked has a hardcoded transform mapping: 

https://github.com/cssnano/cssnano/blob/1665e459ecea23e6167757ac8b2aba728eafb1bd/packages/postcss-normalize-display-values/src/lib/map.js#L24-L44

**Comment by anikethsaha** [comment]
> Definitely in favor of using browserlist, but no modern browser supports this yet, so this would _effectively_ run for every browser.

If a browser doesnt supports it, it would not transform the property at all. We need to implement this. There are few other plugins in cssnano that does like this.

**Comment by ludofischer** [comment]
I don't think this is in scope for cssnano, as cssnano cares only about minification. You can use other PostCSS plugins together with cssnano to support extra features.
