### ISSUE TITLE
[Bug] [Docs]: Optimisations - wrong link to `Presets`

### ISSUE THREAD

**Issue by sobaw98247** [cssnano/cssnano#946]
**Describe the bug**
`404` after clicking on link in docs.

**To Reproduce**
1. Go to https://cssnano.co/docs/what-are-optimisations
2. Click on _presets guide_ in _You can read more about presets in our presets guide._
3. You are redirected to https://cssnano.co/presets with `404`

**Expected behavior**
Redirect to https://cssnano.co/docs/presets

**Screenshots**
![image](https://user-images.githubusercontent.com/66990562/91955519-993fc700-ed03-11ea-80f1-8387feda9201.png)

**Comment by anikethsaha** [comment]
Thanks for reporting. 

PR welcome

**Comment by anikethsaha** [comment]
fixed at https://github.com/cssnano/cssnano/commit/e2e14d6b46747816e0be0258bb656f5e614ba55e
