### ISSUE TITLE
[Bug] : Lexical error with custom property inside min/max, inside min/max, inside calc

### ISSUE THREAD

**Issue by cathrinevaage** [cssnano/cssnano#949]
**Describe the bug**
A lexical error is thrown when a custom property is insert into a min or max function, inside a min or max function, inside a calc function.
If any of the 4 components are removed or substituted, it works as expected.

**To Reproduce**
1. Instruct cssnano to process the following css:
```css
a {
  width: calc(min(max(var(--foo), 0), 100));
}
```

**Expected behavior**
It shouldn't throw errors as this is perfectly valid css.

[**Reproduction**](https://cssnano.co/playground/#eyJpbnB1dCI6ImEge1xuICAgIHdpZHRoOiBjYWxjKG1pbihtYXgodmFyKC0tZm9vKSwgMCksIDEwMCkpO1xufSIsImNvbmZpZyI6Ii8vIGNzc25hbm8gY29uZmlnXG57XG4gIFwicHJlc2V0XCIgOiBcImRlZmF1bHRcIixcbn1cbiJ9)

**Comment by evilebottnawi** [comment]
Please report this issue to `postcss-calc` repo

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/postcss/postcss-calc/issues/117
