### ISSUE TITLE
[Feature Request] Support new PostCSS 8 API

### ISSUE THREAD

**Issue by ylemkimon** [cssnano/cssnano#952]
**Is your feature request related to a problem? Please describe.**
PostCSS 8 [has been released](https://github.com/postcss/postcss/releases/tag/8.0.0) and it has [new API](https://evilmartians.com/chronicles/postcss-8-plugin-migration).

**Describe the solution you'd like**
Migrate to new PostCSS 8 API.

**Describe alternatives you've considered / Additional context**
Legacy API is still supported.

**Comment by anikethsaha** [comment]
We are working on it.

**Comment by benmccann** [comment]
It looks like this may be done now: https://github.com/cssnano/cssnano/pull/975. It's not yet released however

**Comment by ludofischer** [comment]
cssnano 5.0 release candidate uses the PostCSS 8 API. Install cssnano@next to try.
