### ISSUE TITLE
Remove ALL comments using the postcss-cli

### ISSUE THREAD

**Issue by dmuy** [cssnano/cssnano#953]
Hi,

I'm using `postcss-cli` and `cssnano` to minify css. Is there an option to remove all comments including the ones with `/*!`?

I found [this issue](https://github.com/cssnano/cssnano/issues/314) but you said it's possible using the archived `cssnano-cli` - which I don't want to use.

**Comment by evilebottnawi** [comment]
Please ask this in `postcss-cli`, we don't support this package

**Comment by dmuy** [comment]
Uh... as far as I've researched, `postcss-cli` doesn't have any option to remove comments in the css file, but the `cssnano` has. I'm asking how to use the options of `cssnano` in the npm scripts.

I'm not sure if you misunderstood my concern.

**Comment by dmuy** [comment]
I see, thanks.
