### ISSUE TITLE
[Bug] : Translate color string to lower case in border unexpectedly

### ISSUE THREAD

**Issue by devrsi0n** [cssnano/cssnano#955]
**Describe the bug**
`cssnano` translate a color string to lower case in border when using it with [fluentui](https://github.com/microsoft/fluentui).

**To Reproduce**

1. Open <https://cssnano.co/playground/#eyJpbnB1dCI6Ii8qIHdyaXRlIHlvdXIgY3NzIGJlbG93ICovXG4udGVzdCB7XG4gIGJvcmRlcjogc29saWQgMnB4O1xuICBib3JkZXItY29sb3I6ICdbdGhlbWU6bmV0cmFsVGVyaWFyeSwgZGVmYXVsdDogI2ExOWY5ZF0nO1xufSIsImNvbmZpZyI6Ii8vIGNzc25hbm8gY29uZmlnXG57XG4gIFwicHJlc2V0XCIgOiBcImRlZmF1bHRcIixcbn1cbiJ9>
2. You'll see the color string is translated to lower case.

**Expected behavior**
We expect cssnano to keep the original case.

**Screenshots**
![image](https://user-images.githubusercontent.com/7880675/93759013-05935380-fc3c-11ea-8cff-9e3e00422571.png)

**Desktop (please complete the following information):**
- CSSNANO Version 4.1.10

**Comment by anikethsaha** [comment]
Thanks for the bug


css values are case-insensitive I suppose so it wont be an issue. 

I am not getting what is `'[theme:netralTeriary, default: #a19f9d]'` ? this is not in the spec. are you using any preprocessor ?

**Comment by devrsi0n** [comment]
@anikethsaha Thanks for the response, I know `'[theme:netralTeriary, default: #a19f9d]'` isn't in the spec, it's a theme statement/syntax implemented by [fluentui](https://github.com/microsoft/fluentui). Can I create a PR to skip lower case when there is a string in the value?

**Comment by evilebottnawi** [comment]
@devrsi0n do, we parse only valid CSS syntax, you should use postcss process to create real AST from this

**Comment by devrsi0n** [comment]
Thanks @evilebottnawi, I'll disable the related `cssnano` plugins (`postcss-merge-longhand` in this scenario) since this theme string isn't a standard value and we can't create an AST from it IMO.
