### ISSUE TITLE
[Bug] : set 'cssnano perset' make VANT animate doesn't work.

### ISSUE THREAD

**Issue by zzzzzc** [cssnano/cssnano#964]
Vant is a UI library.
import vant css by plugins
```
{
  "plugins": [
    ["import", {
      "libraryName": "vant",
      "libraryDirectory": "es",
      "style": true
    }]
  ]
}
```
set preset in postcss.config.js
```
cssnano: {
      preset: 'advanced',
      autoprefixer: false,
      'postcss-zindex': false,
    },
```
<van-loading type="spinner" />
doesn't has animation effect.

comment preset code can make it work, and import vant css stylesheet into index.html can fix it too.
i wonder why this perset could stop 'vant animate'.

**Comment by zzzzzc** [comment]
The styles of other Vant components are not affected.

**Comment by zzzzzc** [comment]
eg:
   <van-loading type="spinner" />
doesn't has animation effect.

**Comment by zzzzzc** [comment]
`<van-loading type="spinner" />`

**Comment by evilebottnawi** [comment]
Sorry, I don't understand how cssnano related tot his, we compress only CSS files
