### ISSUE TITLE
[Feature Request] minify custom properties

### ISSUE THREAD

**Issue by MathGeniusJodie** [cssnano/cssnano#966]
any plans to have a feature for mangling custom property names?

**Comment by evilebottnawi** [comment]
No, it is unsafe, custom properties is hoist on the top, you can declare `:host { --foo: 10px }` in the one CSS file and use it in the other

**Comment by evilebottnawi** [comment]
You even use it in JS

**Comment by MathGeniusJodie** [comment]
it could still be an optional feature

**Comment by evilebottnawi** [comment]
It was very dangerous optional feature, so we don't have plans, feel free to send a PR

**Comment by MathGeniusJodie** [comment]
found a workaround maybe
https://www.npmjs.com/package/postcss-custom-properties-transformer

**Comment by anikethsaha** [comment]
Closing this as this is not a safe minification.
