### ISSUE TITLE
[Bug] : mergeRules something problem.

### ISSUE THREAD

**Issue by demonguyj** [cssnano/cssnano#968]
cssnano ver 4.1.10

-input css
#login {
	&.joinComplete {
		& .btn_wrap {
           width: 100%;

			& button {
				width: 100%;
				height: 50px;
			}
		}
	}
}

- output
#login{&.joinComplete{& .btn_wrap{& button{height:50px}}}}

- problem
Where is width?????

Check please.

**Comment by anikethsaha** [comment]
the input is not a valid css. Please share your postcss config if you are using any other parser or plugins

**Comment by demonguyj** [comment]
Okay I share my settings.

- my postcss config
"postcss-nested": {},
		autoprefixer: {
			grid: `autoplace`,
		},
		cssnano:
			(api.mode !== `none`) ? {
				preset: [`default`, {
					mergeLonghand: false,
					// mergeRules: false,
					normalizeWhitespace: (api.mode === `production`),
				}],
			} : false,

When I disabled mergeRules,

width is visible.

But mergeRules: true,

width is hide.

If you have any other question, ask me. Thank you.

**Comment by anikethsaha** [comment]
Please share the output with only nested function plugin

**Comment by demonguyj** [comment]
postcss-nested only output is

#login.joinComplete .btn_wrap {
			width: 100%;
		}
		#login.joinComplete .btn_wrap button {
				width: 100%;
				height: 50px;
			}


this one.

Check please :)

**Comment by anikethsaha** [comment]
It is working as expected. 

[demo](https://cssnano.co/playground#eyJpbnB1dCI6IiNsb2dpbi5qb2luQ29tcGxldGUgLmJ0bl93cmFwIHtcclxuICB3aWR0aDogMTAwJTtcclxufVxyXG4jbG9naW4uam9pbkNvbXBsZXRlIC5idG5fd3JhcCBidXR0b24ge1xyXG4gIHdpZHRoOiAxMDAlO1xyXG4gIGhlaWdodDogNTBweDtcclxufVxyXG4iLCJjb25maWciOiIvLyBjc3NuYW5vIGNvbmZpZ1xue1xuICBcInByZXNldFwiIDogWyBcImRlZmF1bHRcIiAsIHtcbiAgICBcIm1lcmdlTG9uZ2hhbmRcIjogZmFsc2VcbiAgfV1cbn1cbiJ9)

Please check your config . The output you mentioned in the issue description is not a css output.
