### ISSUE TITLE
[Bug] : mergeRules something not working correctly.

### ISSUE THREAD

**Issue by quddoss** [cssnano/cssnano#973]
**Describe the bug**
Then a try to compile this code: 
https://prnt.sc/w3g7hk

after compilation I get this:
https://prnt.sc/w3g8xs

if i remove cssnano from plugins I get this:
https://prnt.sc/w3gcc5

**Question 1**
Where is my `.document__layer` with `display: flex` and where is `display: flex;`  from `.document__layer__color` ( compile result is in screen 2 )

**Question 2**
If I remove `&__layer` from .scss file and compile them I get this:
https://prnt.sc/w3ghhb - ( compilation works everything okay )

Why `.body` and `.document__color` rules don't merge ?

**Desktop (please complete the following information):**
- "cssnano": "^4.1.10"
- "cssnano-preset-advanced": "^4.0.7"
- https://prnt.sc/w3g76s

**Comment by QuDDoSS** [comment]
My postcss.config.js

https://prnt.sc/w3gp1x

**Comment by anikethsaha** [comment]
Please share the output of the final css without using the cssnano in your postcss config.

**Comment by QuDDoSS** [comment]
Look at screen 3

**Comment by QuDDoSS** [comment]
`.body {
  -webkit-animation: none;
  display: flex;
  border: 0;
  color: #C55;
  animation: none;
}

.document {
  display: inline-flex;
}

.document__layer {
  display: flex;
}

.document__layer__color {
  -webkit-animation: none;
  display: flex;
  border: 0;
  color: #C55;
  animation: none;
}`

**Comment by ludofischer** [comment]
I cannot reproduce this on current cssnano 5.1.14. I've processed the original Sass with Dart Sass to obtain CSS, then fed the result to cssnano with the default preset. The final result contains all the expected declarations.
