### ISSUE TITLE
[Bug] : cssnano-preset-lite cannot be consumed by commonjs

### ISSUE THREAD

**Issue by 43081j** [cssnano/cssnano#976]
If you install `cssnano-preset-lite` and have a config like this (`postcss.config.js`):

```ts
module.exports = {
  plugins: {
      tailwindcss: {},
      cssnano: {preset: 'lite'}
  }
};
```

it results in this:

```
/node_modules/cssnano-utils/dist/index.js:1
import rawCache from './rawCache.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

and yet `cssnano: {preset: 'default'}` works just fine...

looks like you shipped an ES module but postcss doesn't use ESM, so it can't be consumed.

**Comment by alexander-akait** [comment]
How you run cssnano?

**Comment by alexander-akait** [comment]
What is version are you used?

**Comment by 43081j** [comment]
it was a brand new repo i made today, so:

```
+ cssnano@4.1.10
+ cssnano-preset-lite@1.0.0
+ postcss-cli@8.3.1
+ postcss@8.2.1
```

i use postcss cli:

```bash
$ postcss -r test.css
```

the default preset works fine, but lite does not.

for now, i used the plugins directly (which the lite preset wraps), rather than using cssnano at all

**Comment by anikethsaha** [comment]
Looks like a bug. But  not sure why.  our playground is working fine with lite preset. But I can reproduce this [demo](https://codesandbox.io/s/cssnano-issue-976-repro-bg5dc)

**Comment by 43081j** [comment]
it looks like cssnano-utils is only used by cssnano-preset-lite, but _not_ cssnano-preset-default.

cssnano-utils is published as an ES module, whereas the presets are published as commonjs modules.

**Comment by 43081j** [comment]
aha, got some progress:

* cssnano-utils 1.0 is ESM
* cssnano-utils 4.x is CJS

`npm i cssnano-utils` pulls in the CJS one (4.x).
`npm i cssnano-preset-lite` pulls in the ESM one (1.x).

so i suppose the build process in `master` is already correct but whatever it used to be was wrong (when 1.0 was published)

**Comment by anikethsaha** [comment]
I guess we need to do patch release for both.

**Comment by alexander-akait** [comment]
@anikethsaha Can you do release?

**Comment by aniketh-deepsource** [comment]
I will try to do it by next weekend

**Comment by anikethsaha** [comment]
I will try by next weekend

**Comment by anikethsaha** [comment]
Fixed https://github.com/cssnano/cssnano/commit/5716f2a892178c0c816e93440dea7b79ee1bba1e

try installing `cssnano-preset-lite@1.0.1`

See [sandbox](https://codesandbox.io/s/cssnano-issue-976-repro-bg5dc?file=/output.css)
