### ISSUE TITLE
[Feature Request] When is the next release?

### ISSUE THREAD

**Issue by henricook** [cssnano/cssnano#979]
Hi cssnano team,

We recently spent quite some time trying to figure out why an `opacity: 50%` wasn't working on a remote deployment but was working locally, the answer was remotely we have a build process that uses css nano and the opacity was getting converted to 1% because of a bug

I noticed this is fixed in a merged MR but there's not been a release since 2019 - would you be able to release soon to prevent others going through this pain?

MR I refer to: https://github.com/cssnano/cssnano/pull/881

**Comment by alexander-akait** [comment]
@ludofischer @anikethsaha Should we do something for our playground, we migrate on PostCSS 8 so I think we can do release

**Comment by anikethsaha** [comment]
yea, dependencies update and changes in this filehttps://github.com/cssnano/cssnano/blob/master/site/src/components/editor/postcss_runner.js
not much it should be similar to the one done in cssnano's core runner

**Comment by ludofischer** [comment]
I've managed to go as far as publishing a 5.0.0-alpha.0 GitHub  release https://github.com/cssnano/cssnano/releases and generated a changelog on this branch https://github.com/cssnano/cssnano/tree/5.x.x. But I definitely lack the permissions to publish on npm.

**Comment by anikethsaha** [comment]
great.
here is my twitter handle https://twitter.com/__ANIX__, ping me there I will give permission for `cssnano-bot`. and then you can do the release using lerna
Also, I am submitting a PR to delete deprecated packages. we need to include that before release

**Comment by anikethsaha** [comment]
@ludofischer ⬆️

**Comment by ludofischer** [comment]
Are you also going to update the website or do you prefer I submit a pull request for that?

**Comment by anikethsaha** [comment]
I guess we can update the website after release. Its just updating the dep version and then running the `deploy` script

**Comment by ludofischer** [comment]
My idea would be
1. publish a release candidate
2. update the website and the playgound to use the release candidate
3. publish final if nothing breaks

How should we handle the repository branches? We can't change master without a review, so I was thinking of updating the `package.json` version in a separate branch, then opening a pull request to merge it to master. Also I think we can skip the currently tagged alpha as it includes the `css-util` packages that have been deleted in the mean time.

**Comment by ludofischer** [comment]
The next release candidate (cssnano 5.0.0-rc.0) is availabe on npm on the next branch.

**Comment by ludofischer** [comment]
cssnano 5.0.0 has been published to npm: https://www.npmjs.com/package/cssnano/v/5.0.0
