### ISSUE TITLE
[Bug] : 

### ISSUE THREAD

**Issue by dagda1** [cssnano/cssnano#989]
Installing the latest version of `cssnano` does not contain latest code that stops users ability to upgrade to postcss version 8.

**To Reproduce**

```sh
mkdir test
cd ./test
yarn add cssnano@latest
cat node_modules/postcss-discard-overridden/src/index.js
```
**Expected behavior**
I would expect to see [this code](https://github.com/cssnano/cssnano/blob/master/packages/postcss-discard-overridden/src/index.js).

Instead, I see the code that is not compatible with postcss 8 even though I have installed version `4.0.1` of `postcss-discard-overriden`.

```js
function isOverridable (name) {
    return ~OVERRIDABLE_RULES.indexOf(postcss.vendor.unprefixed(name.toLowerCase()));
}
```

`vendor` as I am sure you know has been removed in postcss 8.  The latest code in github has fixed this but what I have installed with yarn does not have this code.

**Comment by anikethsaha** [comment]
use `cssnano@nigghtly` till we are releasing the new version

**Comment by alexander-akait** [comment]
cssnano supported PostCSS v8 only in master, release will be soon, right now you need to use postcss v7

**Comment by dagda1** [comment]
@alexander-akait thank you for the ultra fast reply!
