### ISSUE TITLE
[Bug] : your playground crashes when clicking "run" on invalid css

### ISSUE THREAD

**Issue by danieltroger** [cssnano/cssnano#991]
To reproduce:
1. go to https://cssnano.co/playground/
2. enter:
```
.crashes {
  font-size: 15pt
  background: red;
}
```
3. click "run"

Expected behaviour: editor does not turn white and need a page reload

![Screen Shot 2021-02-05 at 11 56 20](https://user-images.githubusercontent.com/4047180/107025116-3ddd9d80-67a9-11eb-8187-20aa7b7fcc2f.jpg)

**Comment by anikethsaha** [comment]
Feel free to submit a fix
