### ISSUE TITLE
Remove postcss-svgo from the default preset

### ISSUE THREAD

**Issue by nex3** [cssnano/cssnano#992]
The svgo package which postcss-svgo uses has a large number of outstanding bugs, a number of which I've personally seen result in changes to the rendering of SVGs embedded in CSS files. In addition, the project seems to have been abandoned, with 59 open pull requests and no commits since December 2019. In light of this, I believe it is no longer on track to meet the default preset's goal of never changing input CSS in a way that could cause rendering differences, and as such it should no longer be enabled by default.

**Comment by alexander-akait** [comment]
Yep, I agree, sometimes I think we need to switch on https://github.com/cssnano/cssnano/tree/master/packages/cssnano-preset-lite by default, it is faster and it is safe (only spaces, comments and empty rules)

**Comment by nex3** [comment]
I get a lot of value out of having a broader set of defaults that encompasses everything that's believed to do safe optimizations independent of semantics, but as long as that's also available as a preset I'd be happy.

**Comment by yisibl** [comment]
I am happy to tell you that svgo has [found a new maintainer](https://github.com/svg/svgo/issues/1320#issuecomment-778660127)(@TrySound ), and we have [re-established security as the core idea](https://github.com/svg/svgo/issues/1360), and look forward to working with the PostCSS community.

It would be better if @ben-eb had time to re-maintain [postcss-svgo](https://github.com/ben-eb/postcss-svgo). Ben-eb is also an excellent open source contributor to the PostCSS community.

**Comment by ben-eb** [comment]
@yisibl I'm afraid it's not possible right now, my work for the time being has little to do with CSS and so I can't justify any current contributions to this project.

By the way note that postcss-svgo moved to here as part of the monorepo and I will be clearing out archived repositories soon: https://github.com/cssnano/cssnano/issues/994

**Comment by nex3** [comment]
@yisibl @TrySound Once svgo is in a place where you feel like it should be safe to apply to arbitrary SVGs, let me know and I'll run a test over all of Google's screenshot tests to see if anything breaks in practice.

**Comment by yisibl** [comment]
@ben-eb @nex3 Thanks.

**Comment by ludofischer** [comment]
If things are so bad with the previous SVGO version, we could update to SVGO 2 for the 5.0.0 release. @anikethsaha @alexander-akait any thoughts?

**Comment by anikethsaha** [comment]
Yea I think we should include the SVGO v2 as even if there are breaking changes, it wont be an issue.

👍

**Comment by alexander-akait** [comment]
@anikethsaha Yes, PR welcome

**Comment by ludofischer** [comment]
PR to update SVGO to newly maintained version 2: https://github.com/cssnano/cssnano/pull/1016 SVG experts are welcome to suggest improvements.

**Comment by ludofischer** [comment]
Closing this since SVGO is maintained again. We could open an issue for changing the default preset to lite though (as https://github.com/cssnano/cssnano/issues/992#issuecomment-774459335 suggests).
