### ISSUE TITLE
Intent to delete archived repositories

### ISSUE THREAD

**Issue by ben-eb** [cssnano/cssnano#994]
Hello 👋 

It's been a while since I archived a lot of the old repositories since we switched over to the monorepo. I'd quite like to clean up my account seeing as a lot of these are duplicated here and the others have long been deprecated. If it's alright with you I'll delete these repositories on the 7th of March:

* https://github.com/ben-eb/postcss-minify-trbl
* https://github.com/ben-eb/postcss-minify-font-weight
* https://github.com/ben-eb/postcss-font-family
* https://github.com/ben-eb/postcss-discard-font-face
* https://github.com/ben-eb/postcss-minify-font-values
* https://github.com/ben-eb/postcss-normalize-charset
* https://github.com/ben-eb/postcss-zindex
* https://github.com/ben-eb/postcss-unique-selectors
* https://github.com/ben-eb/postcss-reduce-transforms
* https://github.com/ben-eb/postcss-reduce-initial
* https://github.com/ben-eb/postcss-ordered-values
* https://github.com/ben-eb/postcss-minify-selectors
* https://github.com/ben-eb/postcss-minify-gradients
* https://github.com/ben-eb/postcss-discard-comments
* https://github.com/ben-eb/stylehacks
* https://github.com/ben-eb/postcss-reduce-idents
* https://github.com/ben-eb/postcss-merge-idents
* https://github.com/ben-eb/postcss-discard-unused
* https://github.com/ben-eb/postcss-discard-empty
* https://github.com/ben-eb/postcss-colormin
* https://github.com/ben-eb/postcss-discard-duplicates
* https://github.com/ben-eb/postcss-normalize-url
* https://github.com/ben-eb/postcss-minify-params
* https://github.com/ben-eb/css-size
* https://github.com/ben-eb/postcss-merge-rules
* https://github.com/ben-eb/postcss-merge-longhand
* https://github.com/ben-eb/cssnano-cli
* https://github.com/ben-eb/gulp-cssnano
* https://github.com/ben-eb/postcss-convert-values
* https://github.com/ben-eb/postcss-svgo

I'm giving you this notice period in case you would like to make a backup of any of the issues in these repositories, but I suspect most of the activity has made its way back to here. 🙂 

Thanks!

**Comment by alexander-akait** [comment]
Yep, I think you can remove them without problems
