### ISSUE TITLE
[Bug] : postcss-merge-rules should only merge well-known and well-supported selectors

### ISSUE THREAD

**Issue by nex3** [cssnano/cssnano#999]
If a style rule has a single selector that the browser doesn't understand, the entire style rule is ignored (in my opinion, this is the worst behavior in CSS, but that's neither here nor there). This means that any time `postcss-merge-rules` combines two rules, there's a risk that one of those rules isn't understood and this causes *both* rules to be ignored, changing the behavior of the CSS.

For example:

```css
p {color: blue}
:nonsense {color: blue}
```

Cssnano currently merges these rules, converting this to:

```css
p,:nonsense {color: blue}
```

Which [doesn't color the text](https://codepen.io/nex3/pen/vYyJyjr).

Note that this isn't just an issue for *invalid CSS*—even valid selectors that aren't yet supported by the browser rendering the CSS will break. As such, I think selectors should *only* be merged if they contain a specific set of known, well-supported selectors (possibly enhanced with browserslist if that's feasible).

**Comment by ludofischer** [comment]
Confirmed in 5.0.0-rc.2
